### ISSUE TITLE
uv venv activate

### ISSUE THREAD

**Issue by katterfelto** [astral-sh/uv#3118] opened 2024-04-18 08:42 UTC
I am really liking `uv`, great job!

This is a feature request, would it be possible to activate the virtual environment using `uv`. It would make the activation the same across platforms. I use python on windows far less than Linux, so switching takes extra time to remember the correct activation command.

I would also like it to work like `uv pip install` (which targets the parent `.venv` folder from sub folders) so if I'm in a sub folder of a project it finds the parent environment.

**Comment by zanieb** [comment] 2024-04-19 00:23
Hi! Glad you like the tool :)

This is a duplicate of #1910 

Some additional discussion in https://github.com/astral-sh/uv/issues/2887

**Closed by zanieb** 2024-04-19 00:23 UTC
