### ISSUE TITLE
Add ability to update a project's version via the command line

### ISSUE THREAD

**Issue by valentincalomme** [astral-sh/uv#6854] opened 2024-08-30 07:20 UTC
I love the new features in `uv`. One feature that I found myself wanting was the ability to do something like `uv version minor` or `uv version 1.2.3` to update the version of my package.

Essentially, looking for something similar to the `poetry version` command: https://python-poetry.org/docs/cli/#version

It would allow me to not have to use external packages like `bump2version`

**Comment by zanieb** [comment] 2024-08-30 12:06
Duplicate of https://github.com/astral-sh/uv/issues/6298

Glad you like the new features :)

**Closed by zanieb** 2024-08-30 12:06 UTC
