### ISSUE TITLE
uv pip without venv

### ISSUE THREAD

**Issue by combiz** [astral-sh/uv#2042] opened 2024-02-28 10:55 UTC
We often use docker-based dev containers. In these, we typically skip creating a venv; with pip we can install the packages and freeze them without one. With uv, working with a venv seems to be enforced -- is this the case?

```
$ pip freeze
absl-py==2.1.0
agate==1.7.1
[...]
$ uv pip freeze
error: Failed to locate a virtualenv or Conda environment (checked: `VIRTUAL_ENV`, `CONDA_PREFIX`, and `.venv`). Run `uv venv` to create a virtualenv.
```

**Comment by carlosjourdan** [comment] 2024-02-28 11:38
I ran into the same issue, and as a work arround I had to create and activate a virtual env within the docker file with code that looks like the snippet below. Maybe it can serve you too.

```docker
ENV VIRTUAL_ENV=/bin/venv
RUN uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
```

**Comment by AlexWaygood** [comment] 2024-02-28 12:23
Thanks! We're aware this is an issue. Closing as a duplicate of https://github.com/astral-sh/uv/issues/1526 :)

**Closed by AlexWaygood** 2024-02-28 12:23 UTC
