### ISSUE TITLE
`requires-python` normalization is unintuitive

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4719] opened 2024-07-02 02:29 UTC
E.g., `python_version <= '3.9' or python_version > '3.9'` doesn't simplify out, nor does `python_version < '3.9' or python_version >= '3.9'`.

Related to #4714.

**Comment by charliermarsh** [comment] 2024-07-02 02:30
If this were a Python package, it would actually be correct not to normalize these, due to pre-release handling and other details of PEP 440. But we generally want to ignore that stuff with `requires-python`.

**Comment by charliermarsh** [comment] 2024-07-02 12:19
I think this can be solved alongside https://github.com/astral-sh/uv/issues/4714.

**Comment by ibraheemdev** [comment] 2024-07-02 14:51
Is this a duplicate of https://github.com/astral-sh/uv/issues/4272?

**Comment by charliermarsh** [comment] 2024-07-02 20:15
@ibraheemdev - Yeah, thank you.

**Closed** 2024-07-04 20:06 UTC
Labels: bug
