### ISSUE TITLE
feature: uv activate

### ISSUE THREAD

**Issue by hoegge** [astral-sh/uv#9918] opened 2024-12-15 18:25 UTC
It would be really cool, if uv had an activate feature, that would make activating an environement easier:

`uv activate`

to activate the default ´venv´ environment or 

`uv activate venv2`

to activate a venv with another name instead of having to write the long

`source .venv/bin/activate`

**Comment by samypr100** [comment] 2024-12-15 19:04
👋 this is a duplicate of https://github.com/astral-sh/uv/issues/1910, I'll be closing this issue in favor of that one.

**Closed by samypr100** 2024-12-15 19:04 UTC

**Comment by hoegge** [comment] 2024-12-16 07:59
> 👋 this is a duplicate of https://github.com/astral-sh/uv/issues/1910, I'll be closing this issue in favor of that one.

Sorry. Searched for it before posting but was apparently not good at searching.

Thanks
