### ISSUE TITLE
No longer reinstalls editable paths

### ISSUE THREAD

**Issue by Nomelas** [astral-sh/uv#5703] opened 2024-08-01 18:43 UTC
Looks like starting with version 0.2.28 (0.2.27 works fine), local editable packages are no longer being rebuilt. This is problematic for entry_points as you need to reinstall the editable package in order for the entry script to be created.

It looks like now it maintains a cached version that is even reinstalled if I try to pip install directly first (outside of uv) and then run uv pip commands to isntall it, it reverts back to the old version.

My workflow has been to run `uv pip sync requirements.txt` which contains `-e file:.` to reinstall the package, but that no longer works.

**Comment by charliermarsh** [comment] 2024-08-01 18:45
Thanks -- this is duplicate of #5484 so gonna redirect there.

My advice is that if you want your package to _always_ be rebuilt, you should set `reinstall = ["package-name"]` in a `uv.toml` or `pyproject.toml` file.

**Comment by charliermarsh** [comment] 2024-08-01 18:45
Feel free to chime in on #5484.

**Closed by charliermarsh** 2024-08-01 18:45 UTC

**Comment by charliermarsh** [comment] 2024-09-10 01:44
We have a new API whereby you can add additional files to consider when invalidating the cache. You can also include the current Git commit (i.e., invalidate whenever the SHA changes).

Looks like this:

```toml
[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "requirements.txt" }, { git = true }]
```

See: https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata.
