### ISSUE TITLE
uv 0.5.0 sh installer fail in github workflow

### ISSUE THREAD

**Issue by andgineer** [astral-sh/uv#8928] opened 2024-11-08 09:25 UTC
0.5.0 version fails to install in github workflow

curl -LsSf https://astral.sh/uv/install.sh | sh

downloading uv 0.5.0 x86_64-unknown-linux-gnu
sh: 1027: _force_install_dir: parameter not set
Error: Process completed with exit code 2.

version 0.4.30 installs ok

curl -LsSf https://astral.sh/uv/0.4.30/install.sh | sh
downloading uv 0.4.30 x86_64-unknown-linux-gnu
installing to /home/runner/.cargo/bin
  uv
  uvx
everything's installed!

in both cases github runner

Ubuntu
  22.0
  LTS

**Comment by my1e5** [comment] 2024-11-08 11:35
Duplicate of https://github.com/astral-sh/uv/issues/8919

**Comment by zanieb** [comment] 2024-11-08 13:11
The CI job looks ~7hrs ago when there was a brief disruption.

**Closed by zanieb** 2024-11-08 13:11 UTC

**Comment by andgineer** [comment] 2024-11-08 15:07
now it works
