### ISSUE TITLE
problem with relative includes in requirements file

### ISSUE THREAD

**Issue by detlefla** [astral-sh/uv#1470] opened 2024-02-16 10:10 UTC
Incompatibility: If pip-compile is invoked for a file requirements/dev.in and this file includes `-r common.in`, the included file will be searched in the same directory (requirements/) where the including file is located. `uv pip compile requirements/dev.in` obviously tries (and fails) to resolve the include from the caller's working directory.

**Comment by hauntsaninja** [comment] 2024-02-16 10:57
Duplicate of #1367 (and already fixed on main)

**Closed** 2024-02-16 12:14 UTC
