### ISSUE TITLE
`uv` cannot reproduce `pip install ".[others]"` (unless `-e` is specified)

### ISSUE THREAD

**Issue by kelvindecosta** [astral-sh/uv#2050] opened 2024-02-28 18:32 UTC
## Overview

`uv` currently doesn't account for `pip install ".[dev]"`, a command used to install a local package/project with additional, in this case `dev`, dependencies defined in `pyproject.toml`.

Unless this type of installation is a bad practice, I think `uv` should be able to emulate this `pip` command.

## Actual Behavior

When running:

```
uv pip install ".[dev]"
```

the following output is shown:

```
error: Failed to parse `.[dev]`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
.[dev]
^
```

With `--verbose`:

```
 uv::requirements::from_source source=.[dev]
error: Failed to parse `.[dev]`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
.[dev]
^
```

It works flawlessly when using the `-e` flag:

```
 uv::requirements::from_source source=-e .[dev]
    0.005651s DEBUG uv_interpreter::virtual_env Found a virtualenv through CONDA_PREFIX at: /home/kelvin/.miniconda/envs/dotlas
    0.005755s DEBUG uv_interpreter::interpreter Cached interpreter info for Python 3.9.16, skipping probing: /home/kelvin/.miniconda/envs/dotlas/bin/python
    0.005773s DEBUG uv::commands::pip_install Using Python 3.9.16 environment at /home/kelvin/.miniconda/envs/dotlas/bin/python
Audited 1 package in 16ms
```

## Expected Behavior

Running `pip install ".[dev]"` on its own works, so I'm assuming that `uv` should handle this too.

## System Info

```
# uname -a
Linux vision 5.10.179-1-MANJARO #1 SMP PREEMPT Wed Apr 26 19:18:39 UTC 2023 x86_64 GNU/Linux
```

```
# uv --version
uv 0.1.11
```

**Comment by zanieb** [comment] 2024-02-28 18:35
Thanks for the great writeup! This is a duplicate of #313

**Closed by zanieb** 2024-02-28 18:35 UTC

**Comment by kelvindecosta** [comment] 2024-02-28 20:06
Ah sorry about that, I couldn't find it via the search. Thank you!

**Comment by charliermarsh** [comment] 2024-03-10 13:28
@eirnym -- I'm not sure what you're referring to exactly but yes, extras are supported just file with local paths:

```
pip install "black[d] @ scripts/editable-installs/black_editable"
```

**Comment by eirnym** [comment] 2024-03-10 13:55
if extras are supported and installing from local repository is supported, why `.[others]` is not supported?

**Comment by charliermarsh** [comment] 2024-03-10 14:04
Take a look at #313. We do not support `uv pip install .` right now -- if it's a non-editable install, it needs to include the package name syntax, like `uv pip install "my-project @ .`".

So, similarly if we don't support `uv pip install .`, then `uv pip install .[others]` wouldn't work either.

`uv pip install "my-project @ ."` and `uv pip install "my-project[others] @ ."` work.

**Comment by eirnym** [comment] 2024-03-10 20:18
Package name can be taken from pyproject/seruptools

**Comment by eirnym** [comment] 2024-03-10 20:24
By the way, package name is required as well as for `-e .` installation.

**Comment by zanieb** [comment] 2024-03-11 14:52
We do not require the package name for `-e .` installs (we infer it there). We'll infer package names everywhere in #313.
