### ISSUE TITLE
Centralized location for virtual environments

### ISSUE THREAD

**Issue by callegar** [astral-sh/uv#6504] opened 2024-08-23 09:46 UTC
Apparently, uv wants the virtual environment for a project to reside inside a `.venv` directory in the project itself. Other tools (e.g., poetry,  pdm) let one use a single location for all the virtual environments corresponding to many projects (e.g. `~/.local/share/pdm/venvs`). While there are certainly situations where having everything related to a project self contained in there, in other cases a central location for virtual envs may have advantages (e.g. ease deduplication).

I wonder if this is supported or planned.

**Comment by chrisrodrigue** [comment] 2024-08-23 14:43
Dupe of #1495 and #5229

**Closed** 2024-08-23 15:18 UTC
