### ISSUE TITLE
add a build system?

### ISSUE THREAD

**Issue by DinhHuy2010** [astral-sh/uv#9382] opened 2024-11-23 10:24 UTC
I wondering what if uv include its own PEP 518-compatible build system? (e.g. no need for external build systems like setuptools), similar to poetry?

**Comment by Lingepumpe** [comment] 2024-11-23 10:34
Duplicate of issue #3957

**Closed** 2024-11-23 13:01 UTC

**Comment by DinhHuy2010** [comment] 2024-11-24 03:18
@charliermarsh  wait what?

**Comment by charliermarsh** [comment] 2024-11-24 03:18
We're already working on our own build backend. It's tracked in https://github.com/astral-sh/uv/issues/3957.
