### ISSUE TITLE
uv compile does not ignores git or http locations as constraints

### ISSUE THREAD

**Issue by shayanhoshyari** [astral-sh/uv#1561] opened 2024-02-17 02:10 UTC
See the following minimal example

```
# constraints.txt
segment_anything @ git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588
```

```
# requirements.in.txt
segment_anything
```

Then run

```
uv pip compile requirements.in.txt -c constraints.txt 
```

This produces the wrong output
```
# This file was autogenerated by uv v0.1.3 via the following command:
#    uv pip compile requirement.in.txt -c constraint.txt
segment-anything==1.0
```

Expectation i.e. `pip-compile --constraint=constraint.txt  requirement.in.txt --output-file=requirements.txt` is
```
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --constraint=constraint.txt  requirement.in.txt
#
segment-anything @ git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588
    # via
    #   -c constraint.txt
    #   -r requirement.in.txt
```

**Comment by charliermarsh** [comment] 2024-02-17 02:13
Thank you, we'll fix this. I believe it's a duplicate of https://github.com/astral-sh/uv/issues/1467.

**Closed by charliermarsh** 2024-02-17 02:13 UTC
