### ISSUE TITLE
Can't install package with dependency group without editable mode

### ISSUE THREAD

**Issue by noaonoszko** [astral-sh/uv#1815] opened 2024-02-21 14:55 UTC
## uv version
0.1.6

## Platform
Darwin

## Description

This works:

```bash
pip install ".[dev]"
```

and this works:

```bash
uv pip install -e ".[dev]"
```

but this doesn't:

```bash
uv pip install ".[dev]"
```

I get

```bash
 uv::requirements::from_source source=.[dev]
error: Failed to parse `.[dev]`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
.[dev]
^
```

when running with `--verbose`.

I'm installing my package from a pyproject.toml and the dependency groups are defined under `[project.optional-dependencies]`.

**Comment by charliermarsh** [comment] 2024-02-21 14:59
Thanks, this is a duplicate of https://github.com/astral-sh/uv/issues/313. You can use `uv pip install "package-name @ .[dev]"` for now, but we'll lift this restriction in the future.

**Closed by charliermarsh** 2024-02-21 14:59 UTC

**Comment by charliermarsh** [comment] 2024-03-22 21:26
This is supported as of `v0.1.24`. You can `uv pip install .[dev]` directly, without including a package name.
