### ISSUE TITLE
Add required-version settings

### ISSUE THREAD

**Issue by TomerBin** [astral-sh/uv#8823] opened 2024-11-05 07:14 UTC
Ruff supports setting a version specifier that is enforced at runtime. It might be beneficial to have this feature in UV as well. [Ruff required-version](https://docs.astral.sh/ruff/settings/#required-version)

An additional improvement could be to automatically install the required version of UV, if possible.

**Comment by my1e5** [comment] 2024-11-05 11:49
Duplicate of https://github.com/astral-sh/uv/issues/8605?

**Closed** 2024-11-05 12:47 UTC
