### ISSUE TITLE
Create venv from script metadata

### ISSUE THREAD

**Issue by satwell** [astral-sh/uv#8652] opened 2024-10-29 01:54 UTC
Being able to `uv run` a script with PEP 723 metadata is really cool.

But it seems like uv is missing a way to create a venv for the script.  Having a venv with script dependencies is useful for development, so that my editor can provide auto-completion, type checking, etc.

My workaround is to maintain the same dependency list in a separate `pyproject.toml` file, which lets me easily sync to a venv.  But that means I need to maintain the same dependency list in two places, which is not ideal.

**Comment by zanieb** [comment] 2024-10-29 01:55
#8609 would be a step towards this

**Comment by gnosys-nmercer** [comment] 2024-10-29 05:00
May be duplicate of #6637

**Comment by bgrove-s7** [comment] 2024-10-29 13:42
> Being able to `uv run` a script with PEP 723 metadata is really cool.
> 
> But it seems like uv is missing a way to create a venv for the script. Having a venv with script dependencies is useful for development, so that my editor can provide auto-completion, type checking, etc.
> 
> My workaround is to maintain the same dependency list in a separate `pyproject.toml` file, which lets me easily sync to a venv. But that means I need to maintain the same dependency list in two places, which is not ideal.

This would be a hugely helpful feature.

**Comment by zanieb** [comment] 2024-10-29 13:51
Let's track in the other issue.

**Closed** 2024-10-29 13:50 UTC
Labels: duplicate, enhancement, needs-design
