### ISSUE TITLE
Pulling packages from different Channels: bioconda, conda-forge

### ISSUE THREAD

**Issue by yassineS** [astral-sh/uv#9930] opened 2024-12-16 05:31 UTC
There's no documented way of adding channels such as bioconda and conda-forge to a project. There are a lot of packages that are only available through these.

**Comment by konstin** [comment] 2024-12-16 10:14
Duplicate of https://github.com/astral-sh/uv/issues/1703

**Closed by konstin** 2024-12-16 10:14 UTC
