### ISSUE TITLE
Support using uv pip install in a non-activated venv

### ISSUE THREAD

**Issue by cwiede** [astral-sh/uv#1831] opened 2024-02-21 21:06 UTC
Sometimes it is handy to intentionally not activate a venv. With normal pip this is not an issue, but with uv pip this doesn't work (yet?):
```
$ python3 -m venv /tmp/venv --clear
$ /tmp/venv/bin/pip install uv
Collecting uv
  Using cached uv-0.1.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.3 MB)
Installing collected packages: uv
Successfully installed uv-0.1.6
$ /tmp/venv/bin/uv pip install numpy
error: Failed to locate a virtualenv or Conda environment (checked: `VIRTUAL_ENV`, `CONDA_PREFIX`, and `.venv`). Run `uv venv` to create a virtualenv.
```

Setting the venv directory via VIRTUAL_ENV variable works, but it seems to be unnecessary:
```
$ VIRTUAL_ENV=/tmp/venv /tmp/venv/bin/uv pip install numpy
Resolved 1 package in 91ms
Installed 1 package in 72ms
 + numpy==1.26.4
```

**Comment by hauntsaninja** [comment] 2024-02-21 21:12
Duplicate of https://github.com/astral-sh/uv/issues/1396

**Comment by charliermarsh** [comment] 2024-02-21 21:12
Thanks!

**Closed by charliermarsh** 2024-02-21 21:12 UTC

**Comment by zanieb** [comment] 2024-02-21 21:29
@cwiede note you can do `tmp/venv/bin/python -m uv ...` and it will detect the environment

**Comment by hardikdava** [comment] 2024-02-22 15:28
@zanieb how can i use it in docker container?
