### ISSUE TITLE
Configuration request: UV_NO_BINARY env var

### ISSUE THREAD

**Issue by heitorPB** [astral-sh/uv#6428] opened 2024-08-22 12:38 UTC
Pip has the environment variable `PIP_NO_BINARY` to not install binary packages and instead compile them. This env var has the same behavior as `--no-binary` flag for `pip install`.

`uv pip install` has the `--no-binary` flag, but not the env var (not in the [docs](https://docs.astral.sh/uv/configuration/environment/)).

I'd like to request the env var `UV_NO_BINARY`, with the same syntax/functionality as `PIP_NO_BINARY` and the `--no-binary` flag.

**Comment by notatallshaw** [comment] 2024-08-23 01:00
Think this is a duplicate of https://github.com/astral-sh/uv/issues/4291

**Comment by konstin** [comment] 2024-08-23 07:22
Closing in favor of https://github.com/astral-sh/uv/issues/4291

**Closed by konstin** 2024-08-23 07:22 UTC
Labels: configuration
