### ISSUE TITLE
`uv export --script` being able to export the requirements of a script to a `requirements.txt`

### ISSUE THREAD

**Issue by samster25** [astral-sh/uv#9657] opened 2024-12-05 07:36 UTC
It would be very useful to be able to export the requirements from a script to a `requirements.txt` file. 

This is especially the case when you need to work with a tool that doesn't support `uv` and expects a `requirements.txt` to set up the environment like with ray.

```
# set up script
uv init --script example.py --python 3.12
# add numpy
uv add --script example.py 'numpy'

# this is what would be nice
uv export --script example.py > requirements.txt
```

**Comment by my1e5** [comment] 2024-12-05 10:21
Duplicate of 
- https://github.com/astral-sh/uv/issues/8609

**Comment by zanieb** [comment] 2024-12-05 15:11
Thanks @my1e5 !

**Closed by zanieb** 2024-12-05 15:11 UTC
Labels: duplicate
