### ISSUE TITLE
Sometimes uv cannot update itself inside a virtual env (Windows)

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/uv#3239] opened 2024-04-24 14:33 UTC
There are some circunstances where uv cannot update itself. I believe I've seen this work before, but currently I am unable to perform the command from inside an env.

- OS: Windows 11
- uv installed 0.1.35, upgrading to 0.1.37
- The env was created by `python -m uv venv`
- I dont have a system `uv` in my PATH outside the env

Virtual env was enabled and the executable is the one running on the virtualenv which means it is replacing the same file that is running.
It is not an issue with admin file permission since `pip install uv` does work on the same shell.

```
uv pip install uv --upgrade
Resolved 1 package in 1.82s
Downloaded 1 package in 2.24s
error: failed to remove file `C:\Data\pproject\env\Lib\site-packages\../../Scripts/uv.exe`
  Caused by: Access is denied. (os error 5)
```

If it is related to the file being open by the process, it would be possible to name it `uv.exe.tmp` and then trigger a new process to rename it?

**Comment by charliermarsh** [comment] 2024-04-24 15:03
I think this is a duplicate of https://github.com/astral-sh/uv/issues/1368.

**Comment by charliermarsh** [comment] 2024-04-24 15:03
But yeah definitely a bug related to trying to replace the currently-running executable.

**Closed** 2024-04-24 15:03 UTC
