### ISSUE TITLE
why is `.python-version` a mandatory file?

### ISSUE THREAD

**Issue by YoniChechik** [astral-sh/uv#9494] opened 2024-11-28 07:41 UTC
Can we have a uv setting in pyproject.toml that declers the python version (`dev python version` perheps)? This way we can remove this almost empty file.

Thanks for uv! great effort!

**Comment by my1e5** [comment] 2024-11-28 09:07
Duplicate of 
* https://github.com/astral-sh/uv/issues/8920
* https://github.com/astral-sh/uv/issues/8247

**Closed** 2024-11-28 13:56 UTC
