### ISSUE TITLE
Can't uninstall python versions on uv 0.4.29

### ISSUE THREAD

**Issue by NovaliX-Dev** [astral-sh/uv#8751] opened 2024-11-01 11:54 UTC
I have Python 3.12.7 installed and manager by uv, and i want to uninstall it. Unfortunately, i don't manage to do so using the uv dedicated command.

Here is a list of all the commands i've tried : 
- `uv python uninstall 3.12`
- `uv python uninstall cp@3.12`
- `uv python uninstall cpython-3.12.7-linux-x86_64-gnu`
- `uv python uninstall cp@3.12.7`

All of them gives to me this output : 
```
Searching for Python versions matching: CPython 3.12.7
error: No such file or directory (os error 2)
```
With debug enabled (using `--verbose` and settings `RUST_LOG="trace"`):
```
DEBUG uv 0.4.29
TRACE Checking lock for `.local/share/uv/python` at `.local/share/uv/python/.lock`
DEBUG Acquired lock for `.local/share/uv/python`
Searching for Python versions matching: cpython-3.12.7-linux-x86_64-gnu
DEBUG Released lock at `/home/novalix/.local/share/uv/python/.lock`
error: No such file or directory (os error 2)
```

Here is all my installed python (using `uv python list --only-installed`):
```
cpython-3.13.0-linux-x86_64-gnu    /usr/bin/python3.13
cpython-3.13.0-linux-x86_64-gnu    /usr/bin/python3 -> python3.13
cpython-3.13.0-linux-x86_64-gnu    /usr/bin/python -> ./python3
cpython-3.13.0-linux-x86_64-gnu    /bin/python3.13
cpython-3.13.0-linux-x86_64-gnu    /bin/python3 -> python3.13
cpython-3.13.0-linux-x86_64-gnu    /bin/python -> ./python3
cpython-3.13.0-linux-x86_64-gnu    .local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/bin/python3.13
cpython-3.12.7-linux-x86_64-gnu    .local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/bin/python3.12
```

Installation information : 
- uv version : 0.4.29
- affected platforms : Fedora 41, Windows

I assume I'm doing something wrong, but i don't know what.
Thank you for your help in advance !

**Comment by NovaliX-Dev** [comment] 2024-11-01 11:58
The first two commands I've tried I would understand why they fail if i had many python installation with the same version and only the patch changing, but even though they fail the error they give is very confusing

**Comment by vincexu1026** [comment] 2024-11-01 12:14
I also had same experience, i failed uninstall cpython@3.13 and 3.12 by uv uninstall command in my windows 11 24h2.

**Comment by NovaliX-Dev** [comment] 2024-11-01 12:35
I will update the title of the issue accordingly.

**Comment by charliermarsh** [comment] 2024-11-01 13:30
It looks like a bug but the trace is really spartan, it's hard to know _what_ we're failing to find there.

**Comment by charliermarsh** [comment] 2024-11-01 13:31
Are you able to reproduce this with a Dockerfile?

**Comment by NovaliX-Dev** [comment] 2024-11-01 13:35
I'm not really at ease with dockerfiles to be honest...

**Comment by zanieb** [comment] 2024-11-01 13:52
Closed by https://github.com/astral-sh/uv/pull/8725 already — sorry about that.

**Closed** 2024-11-01 13:55 UTC
Labels: needs-mre
