### ISSUE TITLE
Using git versioning with a workspace module yields unwanted changes to uv.lock

### ISSUE THREAD

**Issue by wlach** [astral-sh/uv#10054] opened 2024-12-20 11:58 UTC
I'm maintaining various libraries inside a monorepo using uv's wonderful [workspaces feature](https://docs.astral.sh/uv/concepts/projects/workspaces/).

Our pyproject.toml looks something like this:

```
[project]
name = "monorepo"
version = "0.1.0"
dependencies = ["mymodule[tests]"]

[tool.uv.workspace]
members = ["src/*"]

[tool.uv.sources]
mymodule = { workspace = true }
```

`mymodule` uses git-based versioning using [setuptools-git-versioning](https://pypi.org/project/setuptools-git-versioning). This gives it a new version like `0.1.post31+git.fc7087bf` which we want for various internal reasons which I won't go into here. Unfortunately since that version is linked to the repository, making *any* change will result in its `uv sync` thinking it needs to update version of the module. The relevant section in `uv.lock` which continuously gets updated is:

```
[[package]]
name = "mymodule"
version = "0.1.post31+git.fc7087bf"
source = { editable = "src/mymodule" }
dependencies = [ ... ]
```

It would be great if we could somehow just skip writing the version for editable modules inside `uv.lock`, since it really shouldn't matter (they're just going to get installed via the filesystem anyway).

**Comment by wlach** [comment] 2024-12-20 12:20
I thought this might be related, but appears not to be (I get the same issue with the latest version of uv, 0.5.11 as of this writing): https://github.com/astral-sh/uv/pull/9549

**Comment by my1e5** [comment] 2024-12-20 13:47
* Duplicate of https://github.com/astral-sh/uv/issues/7533

**Comment by wlach** [comment] 2024-12-20 14:07
ah yep, you're totally right

**Closed** 2024-12-20 14:06 UTC
