### ISSUE TITLE
RFE: Add `uv build`

### ISSUE THREAD

**Issue by gotmax23** [astral-sh/uv#6739] opened 2024-08-28 04:08 UTC
It would be great to have a `uv build` command that could be used to build a plain sdist and/or wheel from a source tree.

**Comment by andrlik** [comment] 2024-08-28 12:22
Would also be great if it mimicked Rye's build command with the option to encrypt your PyPI token with a password.

**Comment by zanieb** [comment] 2024-08-28 12:34
Duplicate of https://github.com/astral-sh/uv/issues/1510 and https://github.com/astral-sh/uv/issues/5507

Sorry, I know these aren't always easy to find.

**Closed by zanieb** 2024-08-28 12:34 UTC

**Comment by gotmax23** [comment] 2024-08-28 12:42
Yup, thanks. I spent 5 minutes trying to find an existing issue and could not.

**Comment by gotmax23** [comment] 2024-08-28 12:57
> Would also be great if it mimicked Rye's build command with the option to encrypt your PyPI token with a password.

Publishing to PyPI is different than the subject of this issue — building dists.
