### ISSUE TITLE
`uv pip compile` does not include extras in the generated files

### ISSUE THREAD

**Issue by silv-io** [astral-sh/uv#2163] opened 2024-03-04 16:23 UTC
# Expected behavior

When defining dependencies with extras in the project files, `pip-compile` also puts those extras in the compiled files. 

E.g.: `"python-jose[cryptography]>=3.1.0"` turns into: `"python-jose[cryptography]==3.3.0"`

# Bug

`uv pip compile` strips the extras like this:

`"python-jose[cryptography]>=3.1.0"` turns into: `"python-jose==3.3.0"`

This might lead to issues further down the line.

# Platform

* Linux AMD64
* `uv` version: `0.1.13`

**Comment by charliermarsh** [comment] 2024-03-04 17:01
Thanks! This is a duplicate of an existing issue: https://github.com/astral-sh/uv/issues/1595. Note that including or excluding the extras doesn't have any effect, since the extras marker just adds additional dependencies, and all those dependencies are flattened anyway. `pip-tools` is changing their default to strip extras in the next release -- the behavior would be identical to uv's.

**Closed by charliermarsh** 2024-03-04 17:01 UTC
