### ISSUE TITLE
Sync virtual environment from script inline metadata

### ISSUE THREAD

**Issue by tcoliver** [astral-sh/uv#8856] opened 2024-11-06 06:22 UTC
I'd love to see a way to directly create a venv from a script's inline metadata. Perhaps a `uv sync --script myscript.py` option would work. 

The use case is to simplify setting up development environments when working in a repository with one or more scripts with inline metadata. Commonly, IDE's have support for utilizing a project's .venv when resolving import paths and running dev tooling. This is easy to configure if your repository is a standard Python project. However, for a directory of scripts (which may each have distinct dependencies), venvs must be manually configured before working on any particular script in order to gain the benefit of these tools. 

My current work around is to define a top level pyproject.toml in virtual project mode with a union of all the scripts dependencies. However, this is error prone in a repo with more than a trivial number of scripts. Also, it's possible to run into version conflicts between script dependency requirements. 

Being able to quickly sync the .venv with a scripts requirements would give a quick and easy way to ensure a compatible IDE experience when working in project-less repositories.

**Comment by zanieb** [comment] 2024-11-06 15:38
This is basically a duplicate of https://github.com/astral-sh/uv/issues/6637

Thanks for explaining your use-case!

**Closed by zanieb** 2024-11-06 15:38 UTC
