### ISSUE TITLE
uv run equivalent to python -m

### ISSUE THREAD

**Issue by johnkangw** [astral-sh/uv#7297] opened 2024-09-11 16:24 UTC
Is it possible to add a flag to `uv run` to make it equivalent to what happens when we run `python -m`.  When running pytest using `uv run` it does not work because I have some relative imports I am using in some of the testing files. It works when I use a `python -m` command.

**Comment by zanieb** [comment] 2024-09-11 18:21
Hi! This is a duplicate of https://github.com/astral-sh/uv/issues/6638

**Comment by zanieb** [comment] 2024-09-11 18:21
I think we should add this though.

**Closed by zanieb** 2024-09-11 18:21 UTC

**Comment by johnkangw** [comment] 2024-09-11 18:40
Oh nice, I did not realize this was a duplicate. Thanks @zanieb
