### ISSUE TITLE
UV Python Install will not find Homebrew Installed dylibs

### ISSUE THREAD

**Issue by sonnen-coviance** [astral-sh/uv#8576] opened 2024-10-25 20:21 UTC
Currently using `uv` on a MacBook Pro with an Apple processor and am running into some issues using `uv python install`.

The issue is that C libraries installed by `homebrew` are not found by Python libraries when using Python installed through `uv python install` but are found when `uv` uses a version of python installed via homebrew.

It seems like Homebrew does some hacking during the Python install process in order to get dylibs installed via Homebrew to be found.

See:
https://github.com/Homebrew/homebrew-core/blob/ed6d3f73a6cd3d779d0254f4ae5ba39b99d3217b/Formula/python@3.10.rb#L185-L192

**Comment by zanieb** [comment] 2024-10-25 20:25
Hi! Yeah Homebrew special-cases their libraries in their Python distributions. It's unclear if we should do the same in ours.

This is a duplicate of

- https://github.com/astral-sh/uv/issues/7896
- https://github.com/astral-sh/uv/issues/7764

**Comment by zanieb** [comment] 2024-10-25 20:34
Let's track in #7764.

Yeah I can understand how that would be confusing. When does it fail? At runtime?

**Closed** 2024-10-25 20:34 UTC
Labels: duplicate

**Comment by zanieb** [comment] 2024-10-25 20:42
Unfortunately that's hard for us to add a special case error message (e.g., like we do for build errors). A minimal example can't hurt! Just post it in the other issue please.
