### ISSUE TITLE
feature request: bump project version command

### ISSUE THREAD

**Issue by phi-friday** [astral-sh/uv#6636] opened 2024-08-26 02:11 UTC
I'm replacing `rye` with `uv`.
(The following articles were referenced: https://github.com/astral-sh/rye/discussions/1342)
I've replaced most of the functionality with `uv`, or changed to other commands or packages.
But changing the version of a project is both simple and annoying.

In the past, I've changed versions like this(in github action)
`rye version <some version>`
But now I change it like this
`sed -i'' -E “s/version = \”0.0.0\“/version = \”$VERSION\“/g” pyproject.toml`

This works, but it's not satisfactory.

I'd like to know if you have any plans to provide functionality like this.
Again, I'm not saying you have to.
It doesn't matter if you don't have it, but it would be nice to have it.
Either way, I'm happy enough with `uv` for now.

**Comment by gnosys-nmercer** [comment] 2024-08-26 02:29
I like the idea of this feature.

It would be nice if it would be able to incorporate features like [bump-my-version](https://pypi.org/project/bump-my-version) where you can specify which files to do the version replace and how to search and replace the version strings using settings in the pyproject.toml file.

**Comment by zanieb** [comment] 2024-08-26 17:35
This is a duplicate of https://github.com/astral-sh/uv/issues/6298

**Closed by zanieb** 2024-08-26 17:35 UTC
Labels: duplicate
