### ISSUE TITLE
✨ How to define custom commands like `tool.rye.scripts`

### ISSUE THREAD

**Issue by jd-solanki** [astral-sh/uv#6302] opened 2024-08-21 06:28 UTC
Hi 👋🏻 

I'm really happy for UV. I always wanted better python ecosystem thanks all of you for your efforts.

I want to migrate from rye to UV as I'm starting new project and wanted to add custom command like `uv run dev` that executes `uv run fastapi dev src/backend/main.py` for me.

In Rye, I used to define it under scripts section:
```toml
[tool.rye.scripts]
dev = "uvicorn aitools.main:app --reload"
migration = "alembic revision --autogenerate -m"
migrate = "alembic upgrade head"
downgrade = "alembic downgrade -1"
```

However, It looks like UV don't have this feature or isn't documented yet.

**Comment by captnswing** [comment] 2024-08-21 09:01
I think this is done in the `[project.scripts]` table. 

See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts

**Comment by jorgebodega** [comment] 2024-08-21 09:34
It is not exactly the same. `[project.scripts]` requires a python file to be created to execute something.

To achieve this, I'm still using [poethepoet](https://github.com/nat-n/poethepoet) inherited from poetry, and it's still working.

But yes, this would be great to have inside `uv`.

**Comment by patrick91** [comment] 2024-08-21 12:42
`pdm` does it like this:

```
[tool.pdm.scripts]
start = "flask run -p 54321"
```

**Comment by zanieb** [comment] 2024-08-21 12:44
Yeah we don't support this yet, but we plan to in some way.

**Comment by anthonycorletti** [comment] 2024-08-22 19:48
this sounds really useful.

my solution for this right now is leaving scripts in a bin directory which does the trick because i don't have to remember commands or reverse-i-search forever. would love to have something like this:

```toml
# ...

[tool.uv.scripts]
clean = "rm -rf build dist *_cache"
format = "ruff format"
check = "ruff check"
test = "pytest"
dev = "uvicorn app.main:app --reload"

[tool.uv.scripts.combos]
ok = ["clean", "format", "check", "test"]

# ...
```

**Comment by patrick91** [comment] 2024-08-23 10:38
@anthonycorletti the combo stuff is interesting, mise does it like this:

```
[tasks.fetch-openapi]
run = "curl localhost:8000/api/v1/openapi.json -O"

[tasks.modify-openapi]
run = "node modify-openapi-operationids.js"
depends = ["fetch-openapi"]
```

but I wonder if this is scope creep :D

**Comment by ion-elgreco** [comment] 2024-08-25 12:30
This would be nice to have so I don't need to have separate make/just files

**Comment by my1e5** [comment] 2024-08-27 10:35
See https://github.com/astral-sh/uv/issues/5903 for task-runner solutions you can use today.

**Comment by my1e5** [comment] 2024-08-27 10:36
Duplicate of https://github.com/astral-sh/uv/issues/5903

**Closed** 2024-08-27 10:51 UTC
Labels: enhancement, projects

**Comment by Mai0313** [comment] 2025-01-16 03:33
any update?

**Comment by zanieb** [comment] 2025-01-16 03:38
@Mai0313 please don't ask for updates. See #9452.

This issue is being tracked in #5903
