### ISSUE TITLE
error   of    uv add torch

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#10237] opened 2024-12-30 12:40 UTC
## When I run  `uv add  torch torchvision torchaudio --default-index https://download.pytorch.org/whl/cu121 `  , 

![Image](https://github.com/user-attachments/assets/c3146a8a-b173-43de-b168-60d392bc874f)

--- 
##  but    `uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121  `  is   no   problem

**Comment by charliermarsh** [comment] 2024-12-30 15:29
Duplicate of #9647.

**Closed by charliermarsh** 2024-12-30 15:29 UTC
