### ISSUE TITLE
Feature Request: Add a `--format json` option to output the command's result in json

### ISSUE THREAD

**Issue by DeflateAwning** [astral-sh/uv#9128] opened 2024-11-14 19:13 UTC
It would be awesome if there was a way to force the output of the command to be in JSON.

An example use case is that it would be helpful to be able to determine from a script if any dependencies were updated/changed.

**Comment by zanieb** [comment] 2024-11-14 19:41
This is a duplicate of https://github.com/astral-sh/uv/issues/411

We're definitely interested!

**Closed by zanieb** 2024-11-14 19:41 UTC
