### ISSUE TITLE
git tag not preserved on compile requirements, converted to SHA

### ISSUE THREAD

**Issue by nmichlo** [astral-sh/uv#3938] opened 2024-05-31 12:13 UTC
The git tag is not preserved when compiling (unless I missed a config option) -- This is also an incompatibility with `pip compile` which preserves this information.

for example
```
echo "uv @ git+https://github.com/astral-sh/uv.git@0.2.5" > r.txt

uv pip compile r.txt
```

results in:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile r.txt
uv @ git+https://github.com/astral-sh/uv.git@47db418ba26dd4b720ec968b2520f2483842419d
    # via -r r.txt
```

The above should be:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile r.txt
uv @ git+https://github.com/astral-sh/uv.git@0.2.5
    # via -r r.txt
```

**Comment by charliermarsh** [comment] 2024-05-31 12:38
This is intentional — we lock to a specific revision.

**Comment by charliermarsh** [comment] 2024-06-03 01:58
Closing as "working as intended".

**Closed by charliermarsh** 2024-06-03 01:58 UTC

**Comment by nmichlo** [comment] 2024-06-04 10:35
Understood for security reasons, is there any possibility of adding a CLI flag to allow this as it does break direct 1:1 compatibility when moving from pip-compile?

**Comment by nmichlo** [comment] 2024-06-11 15:20
@charliermarsh I've run into a case where this causes an error.

If resolved and the downstream repo lists the tag, then the upstream repo that installs using this file causes a resolution error because the tag does not match the SHA.

This would be considered a bug as it generates an invalid requirements file that can't be installed.

**Comment by charliermarsh** [comment] 2024-06-11 15:23
Can you give a concrete example? It seems _correct_ to fail there.
