### ISSUE TITLE
uv python install: pyenv-like "global" command?

### ISSUE THREAD

**Issue by arwhyte** [astral-sh/uv#7377] opened 2024-09-13 19:49 UTC
Migrating to `uv`. But I have a question that I've not been able resolve via the documentation.

`pyenv` provides a global command for establishing the preferred Python version that will be run instead of the system Python when using the terminal, etc.

```commandline
pyenv install 3.12.5
pyenv global 3.12.5
```

Does `uv` provide a similar command or a way to set the default Python so that my terminal recognizes my `uv` install of 3.12.5?

**Comment by charliermarsh** [comment] 2024-09-14 00:30
Thanks -- I believe this a duplicate of #6265.

**Comment by charliermarsh** [comment] 2024-09-14 00:30
(We do plan to provide this but it doesn't exist yet.)

**Closed by charliermarsh** 2024-09-14 00:30 UTC

**Comment by arwhyte** [comment] 2024-09-14 01:00
@charliermarsh thanks for the quick reply. Enjoyed listening to you on https://talkpython.fm/episodes/show/476/unified-python-packaging-with-uv

**Comment by charliermarsh** [comment] 2024-09-14 01:01
Thanks, I appreciate that :)
