### ISSUE TITLE
Does uv build respect the lock file?

### ISSUE THREAD

**Issue by idan-rahamim-lendbuzz** [astral-sh/uv#9252] opened 2024-11-19 21:42 UTC
Is it possible to build packages with pinned dependencies from the lock file.
In poetry it's not supported
https://github.com/python-poetry/poetry/issues/2778

**Comment by charliermarsh** [comment] 2024-11-19 22:57
Are you referring to pinning the versions in the built wheel's metadata? Or using pinned dependencies _while building_ (like, pinned build dependencies)?

**Comment by charliermarsh** [comment] 2024-11-20 00:11
I believe this is a duplicate of https://github.com/astral-sh/uv/issues/8729.

**Closed by charliermarsh** 2024-11-20 00:11 UTC
