### ISSUE TITLE
Error messages should omit `a==1`-to-`a==1{marker}` relationships

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5612] opened 2024-07-30 17:23 UTC
See: https://github.com/orgs/astral-sh/projects/11/views/8?pane=issue&itemId=70300371

**Comment by zanieb** [comment] 2024-07-30 17:45
Is this a dupe of https://github.com/astral-sh/uv/issues/5618 now?

**Comment by charliermarsh** [comment] 2024-07-30 17:46
Oh sorry.

**Comment by charliermarsh** [comment] 2024-07-30 17:46
Wait mine was first :)

**Closed** 2024-07-30 17:45 UTC
Labels: error messages

**Comment by zanieb** [comment] 2024-07-30 17:48
His is better :)
