### ISSUE TITLE
The requirements.txt file generated does not match pyproject.toml

### ISSUE THREAD

**Issue by iphils** [astral-sh/uv#1437] opened 2024-02-16 05:43 UTC
I tried to generate a set of locked dependencies from an input of pyproject.toml file so that I could use that to install the dependencies ( as I cannot perform a command like "uv poetry install" )

but the requirements.txt file generated was essentially blank.
Not sure why.
[requirements.txt](https://github.com/astral-sh/uv/files/14306346/requirements.txt)

**Comment by charliermarsh** [comment] 2024-02-16 05:44
Are you able to share the exact command you ran?

**Comment by iphils** [comment] 2024-02-16 05:51
This is the command 
`uv pip compile pyproject.toml -o requirements.txt `

And the toml file is from the below project:
https://github.com/cognitedata/cdf-project-templates

**Comment by charliermarsh** [comment] 2024-02-16 06:04
So I think the issue here is that the `pyproject.toml` for that file uses Poetry's custom metadata syntax for its dependencies, but `uv` only supports reading the standardized metadata under `[project.dependencies]`. You can see an example of what that looks like here: https://github.com/python-trio/trio/blob/ea8f4be2454f7aaf984852f60ff7ce2b966e695e/pyproject.toml#L38.

**Comment by EnriqueSoria** [comment] 2024-02-16 08:55
> So I think the issue here is that the `pyproject.toml` for that file uses Poetry's custom metadata syntax for its dependencies, but `uv` only supports reading the standardized metadata under `[project.dependencies]`. You can see an example of what that looks like here: https://github.com/python-trio/trio/blob/ea8f4be2454f7aaf984852f60ff7ce2b966e695e/pyproject.toml#L38.

Is adding support for poetry [dependency groups](https://python-poetry.org/docs/managing-dependencies/#dependency-groups) (or something similar) within your plans?

**Comment by hauntsaninja** [comment] 2024-02-19 18:52
Duplicate of #1619 , #1630 and others

**Comment by AlexWaygood** [comment] 2024-02-19 18:55
Yep, folding into #1630

**Closed by AlexWaygood** 2024-02-19 18:55 UTC
Labels: question
