### ISSUE TITLE
Failure on Alpine Linux

### ISSUE THREAD

**Issue by ilanschnell** [astral-sh/uv#1496] opened 2024-02-16 14:51 UTC
On the latest Alpine 3.19.1, I tried out `uv` with apk installed Python.  I get the following error:
```
# uv pip install bitarray
error: Failed to detect the operating system version: Couldn't detect either glibc version nor musl libc version, at least one of which is required
```
Here is some system information:
```
# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
# ldd
musl libc (x86_64)
Version 1.2.4_git20230717
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
```

**Comment by charliermarsh** [comment] 2024-02-16 14:52
Thanks! I believe this is a duplicate of https://github.com/astral-sh/uv/issues/1427.

**Closed by charliermarsh** 2024-02-16 14:52 UTC
