### ISSUE TITLE
feature request: add a required version check option

### ISSUE THREAD

**Issue by mjpieters** [astral-sh/uv#8636] opened 2024-10-28 15:38 UTC
`uv` [version 0.4.27](https://github.com/astral-sh/uv/blob/main/CHANGELOG.md#0427) added support for [PEP 735 – Dependency Groups in pyproject.toml](https://peps.python.org/pep-0735/), which I very much appreciate. However, if any of our developers are still using an older version of `uv` locally, they may have issues with projects that start using the new standard syntax for dependency groups.

Please add a `required-version` option (akin to the [option for Ruff](https://docs.astral.sh/ruff/settings/#required-version)) with the following semantics:

> `required-version`
> 
> Enforce a requirement on the version of uv, to enforce at runtime. If the version of uv does not meet the requirement, uv will exit with an error.
> 
> Useful for unifying results across many environments, e.g., with a pyproject.toml file.
>
> Accepts a [PEP 440](https://peps.python.org/pep-0440/) specifier, like ==0.3.1 or >=0.3.1.
> 
> **Default value**: null  
> **Type**: str
> **Example usage:**
> ```toml
> # pyproject.toml
> [tool.uv]
> required-version = ">=0.4.27"
> ```
> ```toml
> # uv.toml
> required-version = ">=0.4.27"
> ```

**Comment by mkniewallner** [comment] 2024-10-28 19:02
Duplicate of https://github.com/astral-sh/uv/issues/8605.

**Closed** 2024-10-28 19:16 UTC
