### ISSUE TITLE
uv activate as a shortcode for `source .venv/bin/activate`

### ISSUE THREAD

**Issue by dmi3kno** [astral-sh/uv#9603] opened 2024-12-03 11:09 UTC
I would appreciate a short command which could abstract the environment activation

```{bash}
uv activate [environment]
```
which would by default (without the environment specified) resolve to

```{bash}
source .venv/bin/activate
```

This would simplify the workflow and make `uv` easier to adopt in teaching.

**Comment by my1e5** [comment] 2024-12-03 11:22
Duplicate of many
* https://github.com/astral-sh/uv/issues/8106
* https://github.com/astral-sh/uv/issues/8118
* https://github.com/astral-sh/uv/issues/9166

**Closed** 2024-12-03 11:29 UTC

**Comment by zanieb** [comment] 2024-12-03 15:15
Please read #9452 next time.

**Comment by dmi3kno** [comment] 2024-12-03 16:06
I apologized. And I am sorry again. Please forgive me. I closed the issue within 15 min I think. I did do a search but failed to find it. **I am sorry**

**Comment by zanieb** [comment] 2024-12-03 16:13
It's not a big deal, duplicates happen all the time. I'm referring you to #9452 as a resource — it includes a link to this specific request _because_ GitHub search frequently fails.
