### ISSUE TITLE
`uv pip compile` does not show which dependencies are defined directly by the project

### ISSUE THREAD

**Issue by silv-io** [astral-sh/uv#2162] opened 2024-03-04 16:15 UTC
# Expected Behavior

`pip-compile` signifies which dependencies come directly from the current project itself, by putting `<project-name> (pyproject.toml)` in the `via` comment. This is very helpful in differentiating between transitive and direct dependencies.

# Bug

`uv` completely skips this output, making transitive and direct dependencies look the same.

# Platform

* Linux AMD64
* `uv` version: `0.1.13`

**Comment by zanieb** [comment] 2024-03-04 16:55
This is a duplicate of https://github.com/astral-sh/uv/issues/1343

**Closed by zanieb** 2024-03-04 16:55 UTC

**Comment by charliermarsh** [comment] 2024-05-09 14:43
Supported in the next version via https://github.com/astral-sh/uv/pull/3269.
