### ISSUE TITLE
Support getting the project version (like Rye and poetry) from the pyproject.toml

### ISSUE THREAD

**Issue by itamark-ug** [astral-sh/uv#7785] opened 2024-09-29 20:42 UTC
Hi,
In both poetry and Rye there is an option to run `poetry version` or `rye version` and get the project version from the pyproject.toml.

Here is a link to the rye docs:
https://rye.astral.sh/guide/commands/version/

Here is a link to the poetry docs:
https://python-poetry.org/docs/cli/#version

for example, for a project named my-little-helper with a version 2.0.22 the command will emit:
`my-little-helper 2.0.22`
In poetry there is also an option to add the --short option and the result will be `2.0.22`

The motivation for that is to be able to extract the version for automatic tagging a successful package build in a github action.
But I can think of other useful scenarios.

Thanks

**Comment by danyeaw** [comment] 2024-10-05 19:29
I agree that this would be really useful. A workaround to get the version could be:

```
uv tool install pyproject-parser[cli]
pyproject-info project.version
```

**Comment by itamark-ug** [comment] 2024-10-06 08:35
> I agree that this would be really useful. A workaround to get the version could be:
> 
> ```
> uv tool install pyproject-parser[cli]
> pyproject-info project.version
> ```

Thanks, we are already using it in our code, for now (till uv will support it) I will use your workaround in our build action. Thanks

**Comment by zanieb** [comment] 2024-10-06 14:42
Duplicate of https://github.com/astral-sh/uv/issues/6298

**Comment by zanieb** [comment] 2024-10-06 14:42
We're interested, but need to design the interface.

**Closed by zanieb** 2024-10-06 14:42 UTC

**Comment by david-waterworth** [comment] 2024-10-08 01:39
Note `pyproject-info project.version` returns the version with the surrounding quotes, I used `pyproject-info project.version | xargs` to remove them.

**Comment by magnus-bakke** [comment] 2025-02-19 15:33
> I agree that this would be really useful. A workaround to get the version could be:
> 
> ```
> uv tool install pyproject-parser[cli]
> pyproject-info project.version
> ```

For anyone else trying this and getting: `BadConfigError: Unexpected top-level key 'dependency-groups'. Only 'build-system', 'project' and 'tool' are allowed.`

Use a later tag from https://github.com/repo-helper/pyproject-parser/tags
This worked for me:

```
uv tool install pyproject-parser[cli]>=v0.13.0b1
pyproject-info project.version
```
