### ISSUE TITLE
UV 0.5.1 fails to build xgboost 

### ISSUE THREAD

**Issue by blbuford** [astral-sh/uv#9068] opened 2024-11-12 18:15 UTC
Here's a minimum dockerfile to reproduce the error: 
```Dockerfile
FROM python:3.11.9-slim-bookworm
RUN apt-get update \
    && apt-get install -y git build-essential cmake --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN pip install uv==0.5.1
RUN uv pip install --system --no-cache --no-binary xgboost xgboost==1.5.2
```
Changing that `uv==0.5.1` to `uv==0.5.0` makes the `docker build -f tmp/uv-fails.Dockerfile  .` pass. Also up-to-date pip works as well, so I suspect there's something with the newest version of uv. 

From what I can see about the error, somewhere in the compilation uv makes some god-awful looking path that exceeds 4096 characters and looks like: 
```
/tmp/.tmphc3YDw/sdists-v6/pypi/xgboost/1.5.2/zwaKdpTMLMT2TpKaD0bTH/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/build/temp.linux-x86_64-cpython-311/xgboost/src/xgboost/dmlc-core/src/data/basic_row_iter.h
```
Let me know if you need any more info! Thanks for taking a look.

**Comment by zanieb** [comment] 2024-11-12 18:17
Hm we changed some build behaviors in an attempt to make the file paths _shorter_, cc @charliermarsh

**Comment by charliermarsh** [comment] 2024-11-12 18:30
It may not be related -- the path here seems to be repeated infinitely for some reason (`src/build/temp.linux-x86_64-cpython-311/xgboost`).

**Comment by zanieb** [comment] 2024-11-12 18:49
Hm I can't think of another reason it'd regress though?

**Comment by charliermarsh** [comment] 2024-11-12 18:52
I didn't see that it regressed. You're right, it's probably related.

**Comment by charliermarsh** [comment] 2024-11-12 19:08
So I don't really understand the problem yet, but if you change the directory name from `src` to `xyz` in our build cache, it works...

**Comment by charliermarsh** [comment] 2024-11-12 19:10
I think the problem is that they seem to create some sort of scratch directory at `../src`. But we build from a directory named `src`. So it's specific to XGBoost...

**Comment by zanieb** [comment] 2024-11-12 19:12
That's pretty particular. It seems naughty of them to escape their build directory like that. I think it's worth opening an upstream issue?

**Comment by charliermarsh** [comment] 2024-11-12 19:13
I might be misunderstanding, it could be a problem on our end. Need to look at the source.

**Comment by charliermarsh** [comment] 2024-11-12 19:23
Ah actually, I can't replicate this with latest XGBoost:

```docker
FROM python:3.11.9-slim-bookworm
RUN apt-get update \
    && apt-get install -y git build-essential cmake --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN pip install uv==0.5.1
RUN uv pip install --system --no-cache --no-binary xgboost xgboost
```

I think this is really an issue with XGBoost that seems to have been fixed. I'm a little hesitant to make changes in light of that.

**Comment by blbuford** [comment] 2024-11-12 19:50
Bummer. Why does up-to-date pip works on that, but uv does not? E.g. this works: 
```
FROM python:3.11.9-slim-bookworm
RUN apt-get update \
    && apt-get install -y git build-essential cmake --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip && pip install --no-cache --no-binary xgboost xgboost==1.5.2
```

**Comment by zanieb** [comment] 2024-11-12 19:56
They probably do not use the same build directory naming scheme as us.

**Comment by charliermarsh** [comment] 2024-12-02 02:17
I'm going to close this as `wontfix`. Sorry about that -- I'd just prefer to avoid implementing custom workarounds for older versions of specific packages, and changing the directory name here does have some cost.

**Closed by charliermarsh** 2024-12-02 02:17 UTC
Labels: cache, upstream
