### ISSUE TITLE
uv venv: Querying Python at `/Users/fungus/.rye/shims/rye` failed

### ISSUE THREAD

**Issue by shroominic** [astral-sh/uv#2497] opened 2024-03-17 16:17 UTC
I have already installed `rye` and now installed uv but when running `uv venv` it showes me some error related to rye:

```python
❯ uv venv
  × Querying Python at `/Users/shroominic/.rye/shims/rye` failed with
  │ status exit status: 2:
  │ --- stdout:

  │ --- stderr:
  │ error: unexpected argument found
  │ ---
  ```

**Comment by zanieb** [comment] 2024-03-17 16:42
Hi @shroominic I transferred this from Ruff over to uv. I think this is a duplicate of https://github.com/astral-sh/uv/issues/1791 though.

**Closed** 2024-03-17 19:29 UTC
Labels: duplicate
