### ISSUE TITLE
uv pip compile pyproject.toml doesn't resolve any dependency

### ISSUE THREAD

**Issue by ClementWalter** [astral-sh/uv#1712] opened 2024-02-19 18:23 UTC
So I tried to migrate from `poetry` to `uv` for the repo https://github.com/kkrt-labs/kakarot but the documented command

```
uv pip compile pyproject.toml -o requirements.txt
```

doesn't return anything

```
$ uv pip compile pyproject.toml -o requirements.txt
warning: Requirements file requirements.txt does not contain any dependencies
Resolved 0 packages in 163ms
```

On the other hand, `poetry export -f requirements.txt -o requirements.txt` does write a meaningful `requirements.txt` file

**Comment by hauntsaninja** [comment] 2024-02-19 18:52
Duplicate of #1619 , #1630 and others

**Comment by AlexWaygood** [comment] 2024-02-19 18:54
> Duplicate of #1619 , #1630 and others

Agreed

**Closed by AlexWaygood** 2024-02-19 18:54 UTC
