### ISSUE TITLE
Usage of env variables inside requirements file

### ISSUE THREAD

**Issue by kennycontreras** [astral-sh/uv#5016] opened 2024-07-12 16:02 UTC
I'd like to know if this feature is possible using `uv` inside a Docker container
https://pip.pypa.io/en/stable/reference/requirements-file-format/#using-environment-variables

I have a requirements file like the following:

```
dbt-core==${DBT_VERSION}
dbt-bigquery==${DBT_BQ_VERSION}
...
```
The env variables are from `--build-arg`s when I create the Docker image. 

I've tried forcing the activation of a venv and also `--system` without much luck. 

`RUN uv pip install --system -r requirements.txt
`

The following example code (without using uv) works without a problem

```
FROM --platform=linux/amd64 python:3.10.10

ARG DBT_VERSION
ARG DBT_BQ_VERSION

COPY requirements.txt .

RUN pip install --upgrade pip setuptools
RUN pip install -r requirements.txt

```

I couldn't find anything related in the docs, so I'd like to know if someone has worked on something similar or any ideas to achieve that. 

Thanks.

**Comment by zanieb** [comment] 2024-07-12 16:10
Hi! This looks like a duplicate of the request at https://github.com/astral-sh/uv/issues/4592

**Comment by kennycontreras** [comment] 2024-07-12 16:32
> Hi! This looks like a duplicate of the request at #4592

Thanks a lot for pointing it out. It's exactly the same. Sorry for the duplicate. I'll close the issue and follow from there.

**Closed** 2024-07-12 16:34 UTC
Labels: duplicate
