### ISSUE TITLE
`uv pip uninstall uv` does not remove the uv script from a venv

### ISSUE THREAD

**Issue by layday** [astral-sh/uv#2330] opened 2024-03-10 09:15 UTC
```
$ uv pip install uv
Resolved 1 package in 26ms
Installed 1 package in 11ms
 + uv==0.1.16
$ python -c 'import uv'
$ which uv
/Users/dimitris/code/python-packaging/build/venv/bin/uv
$ uv pip uninstall uv
Uninstalled 1 package in 557ms
 - uv==0.1.16
$ python -c 'import uv'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'uv'
[1]$ which uv
/Users/dimitris/code/python-packaging/build/venv/bin/uv
$ uv --version
uv 0.1.16 (9f1452cb7 2024-03-07)
$ uname
Darwin
```

**Comment by charliermarsh** [comment] 2024-03-10 12:27
How is which uv resolving to the version in your virtualenv? You use uv in the first line, but then the subsequent invocations hit the version in your virtualenv without activating it?

**Comment by layday** [comment] 2024-03-10 12:34
The venv is loaded on `$PATH`. The first invocation is using an outer uv from pipx.

**Comment by layday** [comment] 2024-03-10 12:48
This doesn't happen if uv is installed with pip:

```
$ pip install uv
Collecting uv
  Obtaining dependency information for uv from https://files.pythonhosted.org/packages/23/bd/3b9903bfe592d56e3f69aa3f4aea05c3ccae7dc0c485d288efac54201aac/uv-0.1.16-py3-none-macosx_10_12_x86_64.whl.metadata
  Using cached uv-0.1.16-py3-none-macosx_10_12_x86_64.whl.metadata (20 kB)
Using cached uv-0.1.16-py3-none-macosx_10_12_x86_64.whl (9.9 MB)
Installing collected packages: uv
Successfully installed uv-0.1.16

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
$ cat venv/lib/python3.12/site-packages/uv-0.1.16.dist-info/RECORD
../../../bin/uv,sha256=Z70VmXLN-6IZ7SX3CeSNyxB0cMW4f-Gmx_pCt5zm2gk,24062288
uv-0.1.16.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
uv-0.1.16.dist-info/METADATA,sha256=lJtEXoPUCoaPaOmvua6SfL9ZLtnrNpycmhY9_ukSVGk,20860
uv-0.1.16.dist-info/RECORD,,
uv-0.1.16.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
uv-0.1.16.dist-info/WHEEL,sha256=XZs7YqiZZBVwjUJFDH_4SF9SM8QS2rSqm6iPIRrU0Oc,103
uv-0.1.16.dist-info/license_files/LICENSE-APACHE,sha256=QwcOLU5TJoTeUhuIXzhdCEEDDvorGiC6-3YTOl4TecE,11356
uv-0.1.16.dist-info/license_files/LICENSE-MIT,sha256=F5Z0Cpu8QWyblXwXhrSo0b9WmYXQxd1LwLjVLJZwbiI,1077
uv/__init__.py,sha256=zlgkDW2Sj6yTQT9qLPSSoQfVbPPwFT7edvToFy0xUK8,806
uv/__main__.py,sha256=LlzA8yRVILsEFDn5drFaTiopWuZ1K-_lnb2DK4P81qw,927
uv/__pycache__/__init__.cpython-312.pyc,,
uv/__pycache__/__main__.cpython-312.pyc,,
uv/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
$ uv --verbose pip uninstall uv
    0.000276s DEBUG uv_client::registry_client Using registry request timeout of 300s
 uv::requirements::from_source source=uv
    0.366555s DEBUG uv_interpreter::python_environment Found a virtualenv through VIRTUAL_ENV at: /Users/dimitris/code/python-packaging/build/venv
    0.366933s DEBUG uv_interpreter::interpreter Cached interpreter info for Python 3.12.1, skipping probing: /Users/dimitris/code/python-packaging/build/venv/bin/python
    0.366976s DEBUG uv::commands::pip_uninstall Using Python 3.12.1 environment at /Users/dimitris/code/python-packaging/build/venv/bin/python
    0.370778s DEBUG uv::commands::pip_uninstall Uninstalled uv (13 files, 4 directories)
Uninstalled 1 package in 370ms
 - uv==0.1.16
$ uv pip install uv
Resolved 1 package in 2ms
Installed 1 package in 12ms
 + uv==0.1.16
$ cat venv/lib/python3.12/site-packages/uv-0.1.16.dist-info/RECORD
/Users/dimitris/code/python-packaging/build/venv/bin/uv,sha256=bkGzI3Chbexd_nreYkHHjVyq-FS8BkdywctL1ZRs6_Y,46890608
uv-0.1.16.dist-info/INSTALLER,sha256=5hhM4Q4mYTT9z6QB6PGpUAW81PGNFrYrdXMj4oM_6ak,2
uv-0.1.16.dist-info/INSTALLER,sha256=5seyjfYzlik3jO5wuNTen-ixJCoE5KfxUnhni_eb_Oc,16
uv-0.1.16.dist-info/METADATA,sha256=lJtEXoPUCoaPaOmvua6SfL9ZLtnrNpycmhY9_ukSVGk,20860
uv-0.1.16.dist-info/RECORD,,
uv-0.1.16.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
uv-0.1.16.dist-info/WHEEL,sha256=UKfJlVeDYE_8s37Vzf6MLY2dQV893BQmlKJY1DZ8Qbk,145
uv-0.1.16.dist-info/license_files/LICENSE-APACHE,sha256=QwcOLU5TJoTeUhuIXzhdCEEDDvorGiC6-3YTOl4TecE,11356
uv-0.1.16.dist-info/license_files/LICENSE-MIT,sha256=F5Z0Cpu8QWyblXwXhrSo0b9WmYXQxd1LwLjVLJZwbiI,1077
uv/__init__.py,sha256=zlgkDW2Sj6yTQT9qLPSSoQfVbPPwFT7edvToFy0xUK8,806
uv/__main__.py,sha256=LlzA8yRVILsEFDn5drFaTiopWuZ1K-_lnb2DK4P81qw,927
uv/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
$ uv --verbose pip uninstall uv
    0.000455s DEBUG uv_client::registry_client Using registry request timeout of 300s
 uv::requirements::from_source source=uv
    0.367006s DEBUG uv_interpreter::python_environment Found a virtualenv through VIRTUAL_ENV at: /Users/dimitris/code/python-packaging/build/venv
    0.367281s DEBUG uv_interpreter::interpreter Cached interpreter info for Python 3.12.1, skipping probing: /Users/dimitris/code/python-packaging/build/venv/bin/python
    0.367316s DEBUG uv::commands::pip_uninstall Using Python 3.12.1 environment at /Users/dimitris/code/python-packaging/build/venv/bin/python
    0.372060s DEBUG uv::commands::pip_uninstall Uninstalled uv (10 files, 3 directories)
Uninstalled 1 package in 371ms
 - uv==0.1.16
```

Comparing the RECORD written by pip vs uv's:

```diff
diff --git a/pip.diff b/uv.diff
index ece3d6a..2d5861c 100644
--- a/pip.diff
+++ b/uv.diff
@@ -1,13 +1,12 @@
-../../../bin/uv,sha256=Z70VmXLN-6IZ7SX3CeSNyxB0cMW4f-Gmx_pCt5zm2gk,24062288
-uv-0.1.16.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
+/Users/dimitris/code/python-packaging/build/venv/bin/uv,sha256=bkGzI3Chbexd_nreYkHHjVyq-FS8BkdywctL1ZRs6_Y,46890608
+uv-0.1.16.dist-info/INSTALLER,sha256=5hhM4Q4mYTT9z6QB6PGpUAW81PGNFrYrdXMj4oM_6ak,2
+uv-0.1.16.dist-info/INSTALLER,sha256=5seyjfYzlik3jO5wuNTen-ixJCoE5KfxUnhni_eb_Oc,16
 uv-0.1.16.dist-info/METADATA,sha256=lJtEXoPUCoaPaOmvua6SfL9ZLtnrNpycmhY9_ukSVGk,20860
 uv-0.1.16.dist-info/RECORD,,
 uv-0.1.16.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
-uv-0.1.16.dist-info/WHEEL,sha256=XZs7YqiZZBVwjUJFDH_4SF9SM8QS2rSqm6iPIRrU0Oc,103
+uv-0.1.16.dist-info/WHEEL,sha256=UKfJlVeDYE_8s37Vzf6MLY2dQV893BQmlKJY1DZ8Qbk,145
 uv-0.1.16.dist-info/license_files/LICENSE-APACHE,sha256=QwcOLU5TJoTeUhuIXzhdCEEDDvorGiC6-3YTOl4TecE,11356
 uv-0.1.16.dist-info/license_files/LICENSE-MIT,sha256=F5Z0Cpu8QWyblXwXhrSo0b9WmYXQxd1LwLjVLJZwbiI,1077
 uv/__init__.py,sha256=zlgkDW2Sj6yTQT9qLPSSoQfVbPPwFT7edvToFy0xUK8,806
 uv/__main__.py,sha256=LlzA8yRVILsEFDn5drFaTiopWuZ1K-_lnb2DK4P81qw,927
-uv/__pycache__/__init__.cpython-312.pyc,,
-uv/__pycache__/__main__.cpython-312.pyc,,
 uv/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
```

The two notable differences appear to be that the script path is absolute for uv and that it has a duplicate INSTALLER record (though obviously only one file on disk).

**Comment by charliermarsh** [comment] 2024-03-10 12:53
Thanks!

**Comment by charliermarsh** [comment] 2024-03-10 12:59
Found the duplicate INSTALLER, just an oversight. I need to figure out how we could end up with an absolute path there. I don’t think it happens _in general_ because we have a debug assert that the path is relative… I’ll look into it today.

**Comment by charliermarsh** [comment] 2024-03-10 13:04
I have one idea for how it happens.

**Comment by charliermarsh** [comment] 2024-03-10 13:04
Also, I think we should be preferring the x86 wheels, right? That seems wrong too.

**Comment by charliermarsh** [comment] 2024-03-10 13:41
Struggling to see how this would happen. Would you mind running https://github.com/astral-sh/uv/blob/6dcd00e0315c0b4ef743d7609c517b90fa607962/crates/uv-interpreter/src/get_interpreter_info.py#L4 in your interpreter within the virtualenv and sharing the results?

**Comment by layday** [comment] 2024-03-10 13:48
```json
{
  "markers": {
    "implementation_name": "cpython",
    "implementation_version": "3.12.1",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_release": "21.6.0",
    "platform_system": "Darwin",
    "platform_version": "Darwin Kernel Version 21.6.0: Mon Feb 19 20:24:34 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_X86_64",
    "python_full_version": "3.12.1",
    "python_version": "3.12",
    "sys_platform": "darwin"
  },
  "base_prefix": "/nix/store/g7gr0av2rkj57fqaklimdp769alxcfg1-python3-3.12.1",
  "base_exec_prefix": "/nix/store/g7gr0av2rkj57fqaklimdp769alxcfg1-python3-3.12.1",
  "prefix": "/Users/dimitris/code/python-packaging/build/venv",
  "base_executable": "/nix/store/g7gr0av2rkj57fqaklimdp769alxcfg1-python3-3.12.1/bin/python3.12",
  "sys_executable": "/Users/dimitris/code/python-packaging/build/venv/bin/python",
  "stdlib": "/nix/store/g7gr0av2rkj57fqaklimdp769alxcfg1-python3-3.12.1/lib/python3.12",
  "scheme": {
    "platlib": "/Users/dimitris/code/python-packaging/build/venv/lib/python3.12/site-packages",
    "purelib": "/Users/dimitris/code/python-packaging/build/venv/lib/python3.12/site-packages",
    "include": "/Users/dimitris/code/python-packaging/build/venv/include/site/python3.12",
    "scripts": "/Users/dimitris/code/python-packaging/build/venv/bin",
    "data": "/Users/dimitris/code/python-packaging/build/venv"
  },
  "virtualenv": {
    "purelib": "lib/python3.12/site-packages",
    "platlib": "lib/python3.12/site-packages",
    "include": "include/site/python3.12",
    "scripts": "bin",
    "data": ""
  }
}
```

**Comment by layday** [comment] 2024-03-10 14:02
I'm not sure if https://github.com/astral-sh/uv/issues/1952 is related - I haven't installed uv with nix.

**Comment by charliermarsh** [comment] 2024-03-10 14:05
I don't think it would matter how you install uv. The issue is what we query from the running environment and the Python interpreter.

**Comment by layday** [comment] 2024-03-10 18:41
Is there anything I can do to help, keeping in mind that I know next to nothing about Rust? 😛

**Comment by charliermarsh** [comment] 2024-03-10 18:48
If I put up a branch, is there any chance you'd be willing to check it out, `cargo build`, and run with some debug logging?

**Comment by layday** [comment] 2024-03-10 18:56
Sure!

**Comment by charliermarsh** [comment] 2024-03-10 19:00
Ok let me make sure I cover everything that might be useful :joy:

**Comment by layday** [comment] 2024-03-10 22:07
FWIW I'm able to repro this with scripts from other packages.  For non-script data files, the path is kept relative.  Unsure if this is of any help, but if I'm reading the code in https://github.com/astral-sh/uv/blob/cd484d5d9b3192ddb63ba4d1cde4bdcd20bac086/crates/install-wheel-rs/src/wheel.rs#L398 correctly, then it doesn't matter what the `sysconfig` paths are - the bin directory path is hardcoded per plat.

**Comment by charliermarsh** [comment] 2024-03-10 22:36
Oh sorry, I think I was only looking at entrypoints, and not files in `data`. Let me revisit...

(BTW, I think the version you linked is stale. That line doesn't exist on `main`.)

**Comment by charliermarsh** [comment] 2024-03-10 22:37
But I think the uv binary is in `data`, not `scripts`?

**Comment by charliermarsh** [comment] 2024-03-10 22:39
Okay I think I can reproduce.

**Comment by charliermarsh** [comment] 2024-03-10 22:40
Now just trying to figure out why I couldn't reproduce this earlier. Maybe I made a mistake earlier. Anyway I can fix this now! Thanks.

**Comment by charliermarsh** [comment] 2024-03-10 22:56
Fixed in the next release, thank you and sorry for the confusion, I think my earlier debugging led me astray but pointing to that codepath was helpful.

**Closed** 2024-03-10 23:02 UTC
Labels: bug, needs-mre
