### ISSUE TITLE
Support pip's --target

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#2752] opened 2024-04-01 03:53 UTC
The recipe for making a Python zipapp is something like this:

```console
$ mkdir tmp
$ pip install --no-compile --target=tmp . dep_1 dep_2
$ cd tmpdir
$ python -m zipapp --compress --python=/usr/bin/env python3 --main=myapp.__main__:main --output=../myapp.pyz
```

However, uv is missing the `--target` option from pip. It would also be nice (for implementing this in a cross-installer way, inside something like nox) if `--no-compile` as a no-op in UV, rather than an error.

**Comment by zanieb** [comment] 2024-04-01 14:32
This is a duplicate of https://github.com/astral-sh/uv/issues/1517, could you chime in there instead?

**Comment by zanieb** [comment] 2024-04-01 14:33
Regarding `--no-compile` we can definitely do that we have other arguments like that, that would be better tracked in a separate issue.

**Closed by zanieb** 2024-04-01 14:32 UTC
