### ISSUE TITLE
missing build dependencies 

### ISSUE THREAD

**Issue by gaurav-basesolve** [astral-sh/uv#7355] opened 2024-09-13 10:58 UTC
**Versions:**
_uname_ : ```linux 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux```
_python_: ```3.10```
_uv_: ```0.4.6```

**Setup**
On running `uv add toil`, pyproject.toml updates its dependency section, as shown following.
```
[project]
dependencies = [
    "toil",
]
```
And the installed libraries and `uv tree` gives this **toil** package dependencies, as shown in the following image
![image](https://github.com/user-attachments/assets/64fd4d1e-9223-4d79-8de2-abc486e1cf38)

**Issue 1**
Installing the build package from `uv build --wheel` which also stores the information in the METADATA about the dependency doesn't installs all the packages shown in the above tree image . For example, pyyaml is missing.

**Issue 2**
Also, any `[tool.uv.sources]` dependency is not included in the builds. However I did found a way to do this with `uv build`. 

```
[project]
.
.
dependencies = [
    "hello-world-python @ git+https://github.com/garimaaroraa/hello-world-python.git@master"
]

[tool.hatch.metadata]
allow-direct-references = true
```

**Comment by charliermarsh** [comment] 2024-09-13 12:53
I can't reproduce the first issue:

```
❯ uv pip install dist/foo-0.1.0-py3-none-any.whl
Resolved 25 packages in 68ms
Prepared 21 packages in 130ms
Installed 25 packages in 20ms
 + addict==2.4.0
 + blessed==1.20.0
 + certifi==2024.8.30
 + charset-normalizer==3.3.2
 + coloredlogs==15.0.1
 + configargparse==1.7
 + dill==0.3.8
 + docker==7.1.0
 + enlighten==1.12.4
 + foo==0.1.0 (from file:///Users/crmarsh/workspace/uv/foo/dist/foo-0.1.0-py3-none-any.whl)
 + humanfriendly==10.0
 + idna==3.8
 + prefixed==0.9.0
 + psutil==5.9.8
 + pypubsub==4.0.3
 + python-dateutil==2.9.0.post0
 + pyyaml==6.0.2
 + requests==2.31.0
 + ruamel-yaml==0.18.6
 + ruamel-yaml-clib==0.2.8
 + six==1.16.0
 + toil==7.0.0
 + typing-extensions==4.12.2
 + urllib3==2.2.3
 + wcwidth==0.2.13
```

Can you please include a full reproduction?

The second issue is a duplicate of #7167.

**Comment by gaurav-basesolve** [comment] 2024-09-13 13:14
For the issue 1 , @charliermarsh I was able to find the problem. It was from my side.

**Comment by charliermarsh** [comment] 2024-09-13 13:15
Okay cool, thanks for following up. We're tracking the second issue in #7167.

**Closed by charliermarsh** 2024-09-13 13:15 UTC
Labels: needs-mre
