### ISSUE TITLE
UV not found; Docker install fails with latest install and `v0.5.0`

### ISSUE THREAD

**Issue by dwillhelm** [astral-sh/uv#8948] opened 2024-11-08 16:00 UTC
Hi, love your work. 

My docker builds are failing this morning due to a `uv` installation issue. I'm following [this example](https://docs.astral.sh/uv/guides/integration/docker/#installing-uv:~:text=uvx%20/bin/-,Or%2C%20with%20the%20installer%3A,-Dockerfile) from the docs. I was able to fix it by pinning to a older version, but figured it was worthwhile to create the issue. 

In my dockerfile, using
```dockerfile
ADD https://astral.sh/uv/install.sh /uv-installer.sh
```
or 
```dockerfile 
ADD https://astral.sh/uv/0.5.0/install.sh /uv-installer.sh
```

Results in a 
```console 
RUN uv sync --frozen --no-cache

/bin/sh: 1: uv: not found 
```

Running with an older version, however, does not fail. For example 
```dockerfile 
ADD https://astral.sh/uv/0.4.17/install.sh /uv-installer.sh
```

Here's part of my `Dockerfile` just in case
```dockerfile
# this is my dockerfile
FROM python:3.11-slim

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/0.4.17/install.sh /uv-installer.sh # <-- pinning version fixed it for me! 

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.cargo/bin/:$PATH"

WORKDIR /backend
...
...

```

I resolved my issue by pinning the version, but figured others might come across the issue. Thanks

**Comment by my1e5** [comment] 2024-11-08 16:03
Duplicate of https://github.com/astral-sh/uv/issues/8925

**Comment by charliermarsh** [comment] 2024-11-08 16:03
In v0.5, we moved the default install location to `~/.local/bin`. You can view the release notes here: https://github.com/astral-sh/uv/releases/tag/0.5.0. I think the issue is you need to change this line:
```
# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.cargo/bin/:$PATH"
```

**Comment by dwillhelm** [comment] 2024-11-08 16:07
That works! Thanks!

**Closed** 2024-11-08 16:15 UTC

**Comment by charliermarsh** [comment] 2025-01-28 13:59
Sorry, where? We don't reference `/root/.cargo/bin` on that page.

**Comment by juan11iguel** [comment] 2025-01-28 16:55
> Sorry, where? We don't reference `/root/.cargo/bin` on that page.

Sorry! Just checked again and you are right, I must have misread it before

**Comment by MyNameIsNeXTSTEP** [comment] 2025-04-01 08:34
@charliermarsh @juan11iguel If not referrencd in the docs, but the issue is here and resolved, why not add to docs too 🤔 ?
