### ISSUE TITLE
Miniconda style virtual env managment

### ISSUE THREAD

**Issue by sash-a** [astral-sh/uv#6501] opened 2024-08-23 09:07 UTC
Hi there, thanks for this tool, it's been a pleasure to use!

I have a feature request that I think would be useful. In conda you can have globally accessible envs and activate them anywhere with `conda activate env_name`. These envs simply live in `~/.miniconda`. I really like this feature because I often find myself keeping an old venv while working on a feature that requires a new dependency and creating a new venv for that. I think it would be nice to be able to run `uv activate env_name` from anywhere instead of `source path/to/project/.venv/bin/activate`. This would likely require an option when creating a venv, e.g `-n <env_name>` which would then automatically store the env somewhere sensible under that name and allow for `uv activate env_name`

This definitely may be out of scope for uv, so feel free to ignore it :smile:

**Comment by zanieb** [comment] 2024-08-23 13:18
Hi! I think this is a duplicate of https://github.com/astral-sh/uv/issues/1495

**Closed by zanieb** 2024-08-23 13:18 UTC
