### ISSUE TITLE
Add documentation on how to specify pytorch as a dependency

### ISSUE THREAD

**Issue by valentincalomme** [astral-sh/uv#6498] opened 2024-08-23 08:05 UTC
Installing Pytorch has always been the bane of my existence, especially when I require the CUDA version of the package, whose wheel is not available on PyPi. Rye has such a section: https://rye.astral.sh/guide/faq/#how-do-i-install-pytorch

Could `uv` add, as part of the documentation, a guide on how to define `torch` as a dependency, knowing that:
- On MacOs, there are no CUDA version, so theoretically speaking, `pip` is sufficient
- On Linux and Windows, CUDA versions are available but need to be downloaded from a URL (i.e. https://download.pytorch.org/whl/cu124/torch-2.4.0%2Bcu124-cp312-cp312-win_amd64.whl#sha256=22bc926ac3c2f2e4f483f2a201a0ab8a701cc1104ddd74469763f652f3856ec2)

How can we gracefully deal with the different platform and hardware requirements using `uv`?

**Comment by FCamborda** [comment] 2024-08-23 08:13
+1, also if somebody knows how to include pytorch and related packages to pip compile

**Comment by baggiponte** [comment] 2024-08-23 12:44
I think it's a duplicate of #5945.

> * On Linux and Windows, CUDA versions are available but need to be downloaded from a URL (i.e. [download.pytorch.org/whl/cu124/torch-2.4.0+cu124-cp312-cp312-win_amd64.whl#sha256=22bc926ac3c2f2e4f483f2a201a0ab8a701cc1104ddd74469763f652f3856ec2](https://download.pytorch.org/whl/cu124/torch-2.4.0%2Bcu124-cp312-cp312-win_amd64.whl#sha256=22bc926ac3c2f2e4f483f2a201a0ab8a701cc1104ddd74469763f652f3856ec2))

You mean a bit like this from this index? or another? `uv pip install --extra-index-url="https://download.pytorch.org/whl/cpu" -- torch`

**Comment by zanieb** [comment] 2024-08-23 13:34
Yes this a duplicate of #5945 — I'd love help documenting this as I'm not a pytorch user.

**Closed** 2024-08-23 13:34 UTC
