### ISSUE TITLE
uv pip compile --universal gives contradictory versions of same packages

### ISSUE THREAD

**Issue by notatallshaw-gts** [astral-sh/uv#6269] opened 2024-08-20 18:54 UTC
Affected versions: uv 0.2.30 to uv 0.3.0+

Steps to reproduce:

1. Create `requirements.in`:

```
alembic==1.8.1
ipython>=8.4.0
pylint>=2.14.5
```

2. Create `constraints.txt`:

```
dill==0.3.1.1
exceptiongroup==1.0.0rc8
```

3. Run the uv command:

```
$ uv pip compile requirements.in -c constraints.txt --universal --python-version 3.10 --annotation-style line 2>/dev/null | grep "astroid=="
astroid==2.13.5           # via pylint
astroid==3.2.4 ; python_full_version < '3.11'  # via pylint
```

Which, if you try and install on Python 3.10 gives you:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because you require astroid==2.13.5 and astroid{python_full_version < '3.11'}==3.2.4, we can conclude that your requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment] 2024-08-20 18:55
I'll look now.

**Comment by notatallshaw-gts** [comment] 2024-08-20 18:56
Very slightly changing the `requirements.in` or `constraints.txt`, or moving the constraints into the requirements produces the correct:

```
astroid==2.13.5 ; python_full_version >= '3.11'  # via pylint
astroid==3.2.4 ; python_full_version < '3.11'  # via pylint
```

**Comment by charliermarsh** [comment] 2024-08-20 18:56
Wow very interesting!

**Comment by charliermarsh** [comment] 2024-08-20 18:59
It looks like #6268 fixes this.

**Comment by BurntSushi** [comment] 2024-08-20 18:59
@charliermarsh How are you so fast?!?! Indeed, I just confirmed it's fixed in #6268 too:

```
$ cargo r --manifest-path ~/astral/uv/Cargo.toml -p uv -- pip compile requirements.in -c constraints.txt --universal --python-version 3.10 --annotation-style line 2>/dev/null | grep "astroid=="
astroid==2.13.5 ; python_full_version >= '3.11'  # via pylint
astroid==3.2.4 ; python_full_version < '3.11'  # via pylint
```

**Comment by zanieb** [comment] 2024-08-20 19:01
He has two clones of the repo so he can do twice as much!

**Comment by charliermarsh** [comment] 2024-08-20 19:01
Correct

**Closed** 2024-09-03 22:41 UTC
Labels: bug, resolver
