### ISSUE TITLE
Allow setting env variables in `uvx`

### ISSUE THREAD

**Issue by miccoli** [astral-sh/uv#6971] opened 2024-09-03 14:47 UTC
I was not able to pass environment variables to utilities run with `uvx`.

I noticed this problem trying to run `uvx weasyprint` on MacOS, which fails because it is not able to locate a homebrew installed library.

```bash
% export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
% uvx weasyprint --version

... snip ...

OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

But after installing in a venv
```bash
% uv venv
Using Python 3.12.5
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate

% uv pip install weasyprint
Resolved 14 packages in 9ms
Installed 14 packages in 19ms
 + brotli==1.1.0
 + cffi==1.17.0
 + cssselect2==0.7.0
 + fonttools==4.53.1
 + html5lib==1.1
 + pillow==10.4.0
 + pycparser==2.22
 + pydyf==0.11.0
 + pyphen==0.16.0
 + six==1.16.0
 + tinycss2==1.3.0
 + weasyprint==62.3
 + webencodings==0.5.1
 + zopfli==0.2.3
```
the command works as expected (and no `export` necessary)
```bash
% DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib .venv/bin/weasyprint --version
WeasyPrint version 62.3
```

**Comment by zanieb** [comment] 2024-09-03 15:18
That's surprising. We can look into this.

**Comment by charliermarsh** [comment] 2024-09-04 02:41
I'm not yet sure what's happening here... It does seem like we're respecting environment variables (e.g., `RUFF_CACHE_DIR=foo uvx ruff check --show-settings` does show `cache_dir = "foo"`).

**Comment by zanieb** [comment] 2024-09-04 02:51
I tried to reproduce this on macOS but failed — I think you'll need to do a bit more investigation on your end and try to get us an example we can reproduce e.g. maybe using a Docker container.

**Comment by charliermarsh** [comment] 2024-09-04 02:52
I have no trouble reproducing heh:

```
❯ uvx weasyprint --verbose

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/bin/weasyprint", line 7, in <module>
    from weasyprint.__main__ import main
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/weasyprint/__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/weasyprint/css/__init__.py", line 28, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 431, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 420, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/crmarsh/.cache/uv/archive-v0/iLLdmcx9aXJ9J2ThHhFPC/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

**Comment by zanieb** [comment] 2024-09-04 02:58
Did you set the variable?

```
❯ export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
❯ uvx weasyprint --version

Installed 14 packages in 19ms
WeasyPrint version 62.3
```

**Comment by charliermarsh** [comment] 2024-09-04 03:02
Yeah I did

**Comment by charliermarsh** [comment] 2024-09-04 03:03
(Be sure to `uv tool uninstall weasyprint` if you didn't.)

**Comment by charliermarsh** [comment] 2024-09-04 03:05
(Although looks like `uvx` did the install so nevermind.)

**Comment by zanieb** [comment] 2024-09-04 13:05
I wonder if you just don't have the libs it needs installed with Brew? I'm confused that you could reproduce but I couldn't :D

**Comment by miccoli** [comment] 2024-09-04 14:51
A little more investigation from my side...:

- The problem arises only with the *managed* python, not the *system* one:

```
% uvx --python-preference only-system weasyprint --version
WeasyPrint version 62.3
% uvx --python-preference only-managed weasyprint --version

... snip ...

OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

- The managed version, in a `venv`, works as expected, i.e. throws an error without `DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib` but is fine with this setting.

- brew python works without setting `DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib`

Could be the point here that the correct environment should be set when the python interpreter is invoked, not afterwards?

**Comment by zanieb** [comment] 2024-09-04 14:56
From what you've said there, I think this sounds like correct behavior?

I presume brew's Python links to `/opt/homebrew/lib` by default, so it's expected it works without a variable and the it sounds like the managed Python version requires you to explicitly provide the variable (which makes sense, how can it know about Brew?) and providing it works.

Am I missing something?

**Comment by zanieb** [comment] 2024-09-04 16:29
`DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib uvx weasyprint` should work and I thought you said it did above "... but is fine with this setting."

>  because in a only-managed virtual env, DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib waesyprint works as expected.

What does it mean to have a only-managed virtual env? It works with `uv add`?

**Comment by miccoli** [comment] 2024-09-04 16:57
Sorry if my wording was not clear, `only-managed` and `only-system` refer  to the `--python-preference`

Let me explain with some more examples, which I think you can reproduce:

`only-managed`:
```
% uv venv --python-preference only-managed
Using Python 3.12.5
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
% uv pip install weasyprint
Resolved 14 packages in 8ms
Installed 14 packages in 23ms
 + brotli==1.1.0
 + cffi==1.17.0
 + cssselect2==0.7.0
 + fonttools==4.53.1
 + html5lib==1.1
 + pillow==10.4.0
 + pycparser==2.22
 + pydyf==0.11.0
 + pyphen==0.16.0
 + six==1.16.0
 + tinycss2==1.3.0
 + weasyprint==62.3
 + webencodings==0.5.1
 + zopfli==0.2.3
% DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib .venv/bin/weasyprint --version
WeasyPrint version 62.3
% .venv/bin/weasyprint --version

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----
```

`only-system`:
```
% uv venv --python-preference only-system
Using Python 3.12.5 interpreter at: /opt/homebrew/opt/python@3.12/bin/python3.12
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
% uv pip install weasyprint
Resolved 14 packages in 5ms
Installed 14 packages in 17ms
 + brotli==1.1.0
 + cffi==1.17.0
 + cssselect2==0.7.0
 + fonttools==4.53.1
 + html5lib==1.1
 + pillow==10.4.0
 + pycparser==2.22
 + pydyf==0.11.0
 + pyphen==0.16.0
 + six==1.16.0
 + tinycss2==1.3.0
 + weasyprint==62.3
 + webencodings==0.5.1
 + zopfli==0.2.3
% .venv/bin/weasyprint --version
WeasyPrint version 62.3
```

As expected, `weasyprint` script runs
- under homebrew managed python *without*  `DYLD_FALLBACK_LIBRARY_PATH`
- under uv managed python **only with** `DYLD_FALLBACK_LIBRARY_PATH`

So the problem is not within weasyprint, or the python interpreters... it is on how `uvx` loads the uv-managed python interpreter, which is somehow *unaware* of `DYLD_FALLBACK_LIBRARY_PATH`.

**Comment by zanieb** [comment] 2024-09-04 17:07
The problem is that I cannot reproduce the `uvx` behavior you are seeing:

```
❯ DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib uvx --python-preference only-managed --no-cache weasyprint
Installed 14 packages in 17ms
usage: weasyprint [-h] [-e ENCODING] [-s STYLESHEETS] [-m MEDIA_TYPE] [-u BASE_URL] [-a ATTACHMENTS]
                  [--pdf-identifier PDF_IDENTIFIER]
                  [--pdf-variant {pdf/a-1b,pdf/a-2b,pdf/a-3b,pdf/a-4b,pdf/a-2u,pdf/a-3u,pdf/a-4u,pdf/ua-1}]
                  [--pdf-version PDF_VERSION] [--pdf-forms] [--uncompressed-pdf] [--custom-metadata] [-p] [--optimize-images]
                  [-j JPEG_QUALITY] [--full-fonts] [--hinting] [-c CACHE] [-D DPI] [-v] [-d] [-q] [--version] [-i] [-t TIMEOUT]
                  input output
weasyprint: error: the following arguments are required: input, output

❯ uvx --python-preference only-managed --no-cache weasyprint
Installed 14 packages in 17ms

....

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an i
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

**Comment by charliermarsh** [comment] 2024-09-04 17:08
If it's helpful, I can (unless I'm doing something wrong):

```
❯ DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib uvx --python-preference only-managed --no-cache weasyprint
Installed 14 packages in 15ms

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting

-----

Traceback (most recent call last):
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/bin/weasyprint", line 7, in <module>
    from weasyprint.__main__ import main
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/weasyprint/__init__.py", line 419, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/weasyprint/css/__init__.py", line 28, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 431, in <module>
    gobject = _dlopen(
              ^^^^^^^^
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 420, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
           ^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmpG93U5p/archive-v0/mjF8lpR6k77GnkTmYc5m_/lib/python3.12/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': dlopen(gobject-2.0-0, 0x0002): tried: 'gobject-2.0-0' (no such file), '/System/Volumes/Preboot/Cryptexes/OSgobject-2.0-0' (no such file), '/usr/lib/gobject-2.0-0' (no such file, not in dyld cache), 'gobject-2.0-0' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

**Comment by zanieb** [comment] 2024-09-04 17:12
@charliermarsh I am just presuming you don't have the relevant dependencies installed with Brew — does this work for you in a venv as they described? Also like... what do you see here?

```
❯ DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib uvx --python-preference only-managed --no-cache --from weasyprint bash -c 'echo "$DYLD_FALLBACK_LIBRARY_PATH"'
Installed 14 packages in 14ms
/opt/homebrew/lib
```

**Comment by charliermarsh** [comment] 2024-09-04 17:13
Honestly surprised by this but it's empty:
```
❯ DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib uvx --python-preference only-managed --no-cache --from weasyprint bash -c 'echo $DYLD_FALLBACK_LIBRARY_PATH'
Installed 14 packages in 13ms

```

**Comment by zanieb** [comment] 2024-09-04 17:15
Now that's very surprising haha umm... we're both on the same platform / os / arch. What the heck? Are you using zsh?

**Comment by charliermarsh** [comment] 2024-09-04 17:16
I'm using Zsh... Really confusing. I'm on macOS yes.

**Comment by charliermarsh** [comment] 2024-09-04 17:17
I'm also confused because when I tested yesterday, `UV_CACHE_DIR=foo uvx ruff check --show-settings` did work (reflected `foo` in the output), but now it doesn't.

**Comment by zanieb** [comment] 2024-09-04 17:18
What's your version?

```
❯ uvx --version
uv-tool-uvx 0.4.4 (3d75df6ab 2024-09-04)
```

**Comment by charliermarsh** [comment] 2024-09-04 17:18
Sorry, I was using the wrong env var above. `RUFF_CACHE_DIR=foo uvx ruff check --show-settings` _does_ reflect `foo`.

**Comment by charliermarsh** [comment] 2024-09-04 17:19
Ok, so _this_ works:

```
❯ FOO=1 uvx --python-preference only-managed --no-cache --from weasyprint zsh -c 'echo "$FOO"'
Installed 14 packages in 14ms
1
```

**Comment by charliermarsh** [comment] 2024-09-04 17:23
Ok, so _specifically_ env vars that start with `DYLD_` are getting erased:

```
❯ FALLBACK_LIBRARY_PATH=/opt/homebrew/lib uvx --python-preference only-managed --no-cache --from weasyprint zsh -c 'echo "$FALLBACK_LIBRARY_PATH"'
Installed 14 packages in 14ms
/opt/homebrew/lib

❯ DYLD_FOO=/opt/homebrew/lib uvx --python-preference only-managed --no-cache --from weasyprint zsh -c 'echo "$DYLD_FOO"'
Installed 14 packages in 15ms
```

**Comment by charliermarsh** [comment] 2024-09-04 17:24
[I know](https://hynek.me/articles/macos-dyld-env/)

**Comment by zanieb** [comment] 2024-09-04 17:28
Wow so tragic. I have SIP turned off — that's why it works for me.

**Comment by zanieb** [comment] 2024-09-04 17:44
@miccoli Sorry about all the back and forth! We'll look for a workaround here, but this is really an annoying macOS behavior.

**Comment by miccoli** [comment] 2024-09-04 20:08
> @miccoli Sorry about all the back and forth! We'll look for a workaround here, but this is really an annoying macOS behavior.

Thanks for nailing this down really really fast.

No problem on my side, once you know the problem you can live with it quite easily... I opened this issue mainly to avoid others the pain of understanding what was going on. 

BTW this is really an edge case, so there is no urgency in solving it.

**Comment by charliermarsh** [comment] 2024-09-06 00:17
@zanieb -- I'm tempted to close this, I don't know if we can actually fix it.

**Closed** 2024-09-06 00:43 UTC
Labels: bug, uv tool

**Comment by miccoli** [comment] 2024-09-06 11:15
> @zanieb -- I'm tempted to close this, I don't know if we can actually fix it.

OK for closing since this is only an edge case, and it could be overly difficult to fix (and a BIG thanks for the wonderful uv project!)

Just for the records, and because this could surface in other places too, let me just point to the exact place where the `#!/bin/sh` shebang (responsible for the `DYLD_*` sanitisation) got added in the first place:

https://github.com/astral-sh/uv/blob/8bcae5f2f693a790cbb3f4bc3e509b931d8d7cea/crates/install-wheel-rs/src/wheel.rs#L126-L160

Interestingly it appears that the shebang length limit on MacOS is 512 and not 127, so this problem could be mitigated at the cost of a more complex check on the platform... 

In <https://www.in-ulm.de/~mascheck/various/shebang/> there is a lot of info on the shebang.

I'm tempted to open a PR since it would be an excuse to finally learn rust (which is on my to do list), but this will not happen any time soon...

**Comment by agustingomes-therapieland** [comment] 2024-10-02 20:11
@miccoli I would like to thank you because today I learned `DYLD_FALLBACK_LIBRARY_PATH` can solve some of my problems.

**Comment by CHC383** [comment] 2025-11-16 08:38
Just want to share a way to set `DYLD_FALLBACK_LIBRARY_PATH` programmatically:
```python
from ctypes.macholib import dyld
dyld.DEFAULT_LIBRARY_FALLBACK.append("/opt/homebrew/lib")
```

This is from https://github.com/Kozea/CairoSVG/issues/354#issuecomment-1072905204
