### ISSUE TITLE
Support for installing remotely hosted dependency files (requirements.txt, lock files, constraints, overrides, etc)

### ISSUE THREAD

**Issue by ketozhang** [astral-sh/uv#2147] opened 2024-03-04 09:02 UTC
Missing feature from `uv pip` that is available in `pip` is that it cannot install a dependency file from a remote source.

## Example

Deploy an application released in GitHub releases using a lock file and a wheel file.
```console
$ export URL=https://github.com/myusername/myapp/releases/download/v1.2.3/
$ uv pip install -r $URL/requirements.txt $URL/myapp.whl
```

**Comment by johanjk** [comment] 2024-03-04 11:34
Duplicate of https://github.com/astral-sh/uv/issues/1332. See https://github.com/astral-sh/uv/pull/2081 for ongoing discussion.

**Comment by charliermarsh** [comment] 2024-03-04 14:31
Closing into other issues.

**Closed by charliermarsh** 2024-03-04 14:31 UTC
