### ISSUE TITLE
The uv pip install for current directory only works with editable mode

### ISSUE THREAD

**Issue by dbritto-dev** [astral-sh/uv#1896] opened 2024-02-23 03:37 UTC
* The command I invoked: `uv pip install .`
* The current Ruff settings:
```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "demo"
version = "2024.02.22"
dependencies = [
  "pydantic[email]",
  "email-validator",
]
requires-python = ">=3.10"
description = "Demo"
readme = "README.md"
classifiers = [
  "Programming Language :: Python"
]
[project.optional-dependencies]
dev = ["ruff", "nox", "pytest"]
```
* The current Ruff version: 0.2.2

> **Note:** the same command with editable mode, works without any problem. Ref command: `uv pip install -e .`

<img width="618" alt="image" src="https://github.com/astral-sh/ruff/assets/1697714/a4134b2a-4d86-4a3e-b6ec-04a098a0ee0b">

**Comment by charliermarsh** [comment] 2024-02-23 03:40
Hey sorry -- we currently support `uv pip install "demo @ ."` or `uv pip install -e .` but we'll lift this restriction in the future. (It's a duplicate of https://github.com/astral-sh/uv/issues/313.)

**Closed by charliermarsh** 2024-02-23 03:40 UTC

**Comment by dbritto-dev** [comment] 2024-02-23 03:53
@charliermarsh sure, thanks

**Comment by charliermarsh** [comment] 2024-03-22 21:26
This is supported as of `v0.1.24`. You can `uv pip install .` directly, without including a package name.

**Comment by dbritto-dev** [comment] 2024-03-22 22:27
@charliermarsh thanks a lot
