### ISSUE TITLE
Virtualenv created using `uv venv` should contain pre-installed `uv`

### ISSUE THREAD

**Issue by hkad98** [astral-sh/uv#1869] opened 2024-02-22 14:17 UTC
Hi,
I want to replace the pip installation with uv, but I discovered that it would be beneficial if the `uv venv` produced an environment with preinstalled `uv`. I know that I can use `uv venv --seed`, but it does not install uv.  I use Makefile to bootstrap venv, install requirements, and do other things. To ensure that everything works fine, I do this:

```
python3.11 -m venv .venv --upgrade-deps
.venv/bin/pip3 install -r dev-requirements.txt
.venv/bin/pre-commit install
```

When I started replacing this, I found out that I am missing uv being part of virtual env, and I cannot simply do the:

```
uv venv
.venv/bin/uv pip install -r dev-requirements.txt
.venv/bin/pre-commit install
```

**Comment by zanieb** [comment] 2024-02-22 18:48
Hi! This is a duplicate of https://github.com/astral-sh/uv/issues/1632

**Closed by zanieb** 2024-02-22 18:48 UTC
