### ISSUE TITLE
Compatibility with Nix(OS)?

### ISSUE THREAD

**Issue by gkze** [astral-sh/uv#1418] opened 2024-02-16 03:41 UTC
Hi, very excited to try this tool. Unfortunately Nix doesn't expose common executables on standard paths (`/bin/ls`, `/bin/ld`, etc.) so I'm not sure how to proceed. Any advice? I'm going to try to change the logic to perform a `$PATH`-based lookup, but not sure if absolute paths are desired. Would appreciate advice.

**Comment by timleslie** [comment] 2024-02-16 03:45
I believe this is a dupe of #1395.

**Comment by charliermarsh** [comment] 2024-02-16 03:46
Yeah I definitely want to fix this.

**Comment by charliermarsh** [comment] 2024-02-16 04:08
I'm gonna merge into #1395.

**Closed by charliermarsh** 2024-02-16 04:08 UTC
