### ISSUE TITLE
Adding progressbar to indicate the download status and ETA especially for packages with >=10MB

### ISSUE THREAD

**Issue by detrin** [astral-sh/uv#2721] opened 2024-03-28 21:38 UTC
I started using uv as it is neat and faster than pip. One feature that I miss from pip is the progressbar to indicate what part of the wheel was downloaded and what is the ETA. The progressbar has little to no value added except it is nice to watch of course. The ETA is useful, consider packages such as polars, or torch that have rather huge wheels andit can take a while to download. Sometimes my connection is poor (down to like 300 KB/s) and while those packages are downloading I use that time for something else, so it is nice to have some ETA on that. 

Would you consider adding such a feature into uv?

**Comment by zanieb** [comment] 2024-03-28 22:15
Hi! This is a duplicate of #1209 

We're interested but it's non-trivial to show the progress bars when we do concurrent operations. I'm going to close this in favor of the original issue.

**Closed by zanieb** 2024-03-28 22:15 UTC
