### ISSUE TITLE
Standalone installation script installed `uv` fails to `uv self update`

### ISSUE THREAD

**Issue by scienceplease** [astral-sh/uv#6774] opened 2024-08-28 20:54 UTC
Recent versions of `uv` have not been able to `uv self update` despite being installed via the standalone installation script. I have not been able to pinpoint the issue to anything in particular on my system. All relevant information below:

```bash
cat /etc/redhat-release 
# Fedora release 40 (Forty)

env | grep CARGO_HOME
# CARGO_HOME=/home/username/.local/opt/rust/cargo

curl -LsSf https://astral.sh/uv/install.sh | sh
# downloading uv 0.4.0 x86_64-unknown-linux-gnu
# installing to /home/username/.local/opt/rust/cargo/bin
#  uv
#  uvx
# everything's installed!
#
# To add /home/username/.local/opt/rust/cargo/bin to your PATH, either restart your shell or run:
#
#    source /home/username/.local/opt/rust/cargo/env (sh, bash, zsh)
#    source /home/username/.local/opt/rust/cargo/env.fish (fish)

which uv
# ~/.local/opt/rust/cargo/bin/uv

uv --version
# uv 0.4.0

uv self update
# warning: Self-update is only available for uv binaries installed via the standalone installation scripts.
#
# If you installed uv with pip, brew, or another package manager, update uv with `pip install # --upgrade`, `brew upgrade`, or similar.
```

**Comment by telljmc** [comment] 2024-09-03 22:52
I am encountering a similar issue on a Macbook Pro M3.  I installed uv using the curl command.  When I attempt to update I encounter the following:

```
❯ uv self update
info: Checking for updates...
error: The installation failed. Output from the installer:
downloading uv 0.4.3 aarch64-apple-darwin
```
I tried the "--verbose" flag which resulted in exactly the same message.  I tried closing everything and rebooting with the same result.  Next up will be to do an uninstall and fresh reinstall.

**Comment by zanieb** [comment] 2024-09-03 22:54
Hm. I'm on a M3 as well and can't reproduce that.

**Comment by telljmc** [comment] 2024-09-05 17:23
> I am encountering a similar issue on a Macbook Pro M3. I installed uv using the curl command. When I attempt to update I encounter the following:
> 
> ```
> ❯ uv self update
> info: Checking for updates...
> error: The installation failed. Output from the installer:
> downloading uv 0.4.3 aarch64-apple-darwin
> ```
> 
> I tried the "--verbose" flag which resulted in exactly the same message. I tried closing everything and rebooting with the same result. Next up will be to do an uninstall and fresh reinstall.

To update, I finally had to uninstall uv 0.3.5 and reinstall uv 0.4.3.  Today I tried to update to uv 0.4.5 and I am running into the same issues as previous:

```
❯ uv self update
info: Checking for updates...
error: The installation failed. Output from the installer:
downloading uv 0.4.5 aarch64-apple-darwin
```

**Comment by lucas-labs** [comment] 2024-10-27 02:06
I'm having the same issue in Windows (installed via standalone script).

```
$ uv self update

warning: Self-update is only available for uv binaries installed via the standalone installation scripts.

If you installed uv with pip, brew, or another package manager, update uv with `pip install --upgrade`, `brew upgrade`, or similar.
```

**Comment by leehanchung** [comment] 2024-11-27 22:59
Got the same problem.

```bash
$ uv self update
warning: Self-update is only available for `uv` binaries installed via the standalone installation scripts.

If you installed `uv` with `pip`, `brew`, or another package manager, update `uv` with `pip install --upgrade`, `brew upgrade`, or similar.

$ uv self update -v
DEBUG receipt is not for this executable; assuming `uv` was installed via a package manager
warning: Self-update is only available for `uv` binaries installed via the standalone installation scripts.

If you installed `uv` with `pip`, `brew`, or another package manager, update `uv` with `pip install --upgrade`, `brew upgrade`, or similar.
han@VitaminC:~/courses/cs194-llm-agents$ uv cache prune
Pruning cache at: /home/han/.cache/uv
Removed 9 files (3.2MiB)
$ uv self update -v
DEBUG receipt is not for this executable; assuming `uv` was installed via a package manager
warning: Self-update is only available for `uv` binaries installed via the standalone installation scripts.

If you installed `uv` with `pip`, `brew`, or another package manager, update `uv` with `pip install --upgrade`, `brew upgrade`, or similar.
```

Seems like its something related to `receipt`?

**Comment by zanieb** [comment] 2024-11-27 23:12
@leehanchung Generally that means that some _other_ uv on the system was installed after the one that you're using. What does `where uv` output?

**Comment by leehanchung** [comment] 2024-11-27 23:27
> [@leehanchung](https://github.com/leehanchung) Generally that means that some _other_ uv on the system was installed after the one that you're using. What does `where uv` output?

found the issue. i had the old `~/.cargo/bin/uv`. removed and working now.

thanks!!

**Closed** 2024-12-04 01:26 UTC
Labels: bug, releases
