### ISSUE TITLE
`uv pip compile` adds setuptools (and pip) to requirements.txt

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/uv#1353] opened 2024-02-15 21:22 UTC
`pip-compile` considers dependencies on `setuptools` (and `pip`) unsafe and mentions this at the end of the generated file:

```py
# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools
```

or

```py
# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

When using `uv pip compile`, this is not the case and I get `pip` added to the requirements.txt (the `pip` dep is coming from `pip-tools` and `setuptools` from packages like `babel`, `pycountry` and `pip-tools`). But both are packages that you generally never want in a requirements.txt (except maybe in VERY specific circumstances - and in those case you probably want to vendor the versions you require instead of having them as package dependencies).

**Comment by juftin** [comment] 2024-02-21 19:27
FWIW, `--allow-unsafe` is becoming the default in the next major release of `pip-compile`: https://pip-tools.readthedocs.io/en/latest/#deprecations
> In the next major release, the --allow-unsafe behavior will be enabled by default (https://github.com/jazzband/pip-tools/issues/989). Use --no-allow-unsafe to keep the old behavior. It is recommended to pass --allow-unsafe now to adapt to the upcoming change.

**Comment by zanieb** [comment] 2024-02-21 20:14
Thanks for the additional context. If `pip-compile` is moving towards just including these by default perhaps we should too? It's _more_ safe for us since we don't rely on these packages.

**Comment by charliermarsh** [comment] 2024-02-21 20:18
(We do already "include" these by default, unless I'm misunderstanding your comment.)

**Comment by zanieb** [comment] 2024-02-21 20:41
(edited to clarify)

**Comment by hauntsaninja** [comment] 2024-02-21 21:34
In my opinion, `uv` has the right default behaviour, and soon pip-compile will have the right default behaviour too. If I were uv, I would implement https://github.com/astral-sh/uv/issues/1415 to let people do what they need to, and not change this.

**Comment by charliermarsh** [comment] 2024-02-21 21:36
Yeah, agreed.

**Comment by charliermarsh** [comment] 2024-03-04 01:50
Closing as "working as intended".

**Closed by charliermarsh** 2024-03-04 01:50 UTC
Labels: wontfix, compatibility
