### ISSUE TITLE
allow centralized venv storage like pyenv-virtualenv

### ISSUE THREAD

**Issue by wakamex** [astral-sh/uv#1578] opened 2024-02-17 08:07 UTC
This provides a few handy features:
- easily use the same venv in multiple locations
- don't worry about losing your venv when you `rm -rf` a folder

To identify which venv should be used in a folder, pyenv-virtualenv uses `.python-version`. I suggest `uv` could use `.uvenv` as follows:

```
uv venv ~/.venvs/myvenv
```
by invoking `uv venv` with a non-standard location, we know we'll want to keep track of that location, so I suggest storing it in `.uvenv` right away without forcing the user to do `echo "~/.venvs/myvenv" > .uvenv`.

I can already use a script to auto-activate my venv from this remote location upon entering a folder (like an [oh-my-zsh plugin](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh)):
```sh
if [ -f .uvenv ]; then
  source "$(cat .uvenv)/bin/activate"
fi
```

but if this were built-in behavior defined in a central location equivalent to `PYENV_ROOT` then you could just give the name:
```sh
uv venv local myvenv
```

pyenv blurb from https://github.com/pyenv/pyenv-virtualenv?tab=readme-ov-file#activate-virtualenv:
> If eval "$(pyenv virtualenv-init -)" is configured in your shell, pyenv-virtualenv will automatically activate/deactivate virtualenvs on entering/leaving directories which contain a .python-version file that contains the name of a valid virtual environment as shown in the output of pyenv virtualenvs (e.g., venv34 or 3.4.3/envs/venv34 in example above) . .python-version files are used by pyenv to denote local Python versions and can be created and deleted with the [pyenv local](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-local) command.

**Comment by hauntsaninja** [comment] 2024-02-17 09:16
I've been using a `.venv` file that contains a location to accomplish something similar for the last half decade. It's great. I think when PEP 704 was being discussed the `.venv` file was suggested and had some support

**Comment by swaldhoer** [comment] 2024-02-17 12:02
Basically a duplicate of https://github.com/astral-sh/uv/issues/1526

**Comment by zanieb** [comment] 2024-02-17 19:34
Not a duplicate of #1526, but this is a duplicate of https://github.com/astral-sh/uv/issues/1495.

**Closed by zanieb** 2024-02-17 19:34 UTC

**Comment by callegar** [comment] 2024-10-04 15:02
May I suggest the PDM model? That is nice IMHO. Via a config variable you decide if you want venvs to be generally managed centrally or locally. When they are centrally managed, PDM sorts out things nicely in an almost automatic way.
