### ISSUE TITLE
pip compile does not carry forward environment markers like sys_platform

### ISSUE THREAD

**Issue by AbdealiLoKo** [astral-sh/uv#4231] opened 2024-06-11 14:46 UTC
If I have a item in my requirement file where I have explicitly provided env markers like `sys_platform`, it does not get carried forward in the `pip compile` output.

So, when I have a dependency like `pysqlite3-binary; sys_platform=="linux"` the pip compile removed the `sys_platform` part. WHen I use pip-tools, it was not removing that.

Try:
```bash
$ echo "pysqlite3-binary; sys_platform==\"linux\"" | uv pip compile --verbose -
DEBUG Starting toolchain discovery for any Python
DEBUG Looking for exact match for request any Python
DEBUG Searching for Python interpreter in all sources
DEBUG Found CPython 3.8.19 at `/home/ali/.conda/envs/py38/bin/python3` (conda prefix)
DEBUG Using Python 3.8.19 interpreter at /home/ali/.conda/envs/py38/bin/python3 for builds
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.8.19
DEBUG Adding direct dependency: pysqlite3-binary{sys_platform == 'linux'}*
DEBUG Found stale response for: https://pypi.org/simple/pysqlite3-binary/
DEBUG Sending revalidation request for: https://pypi.org/simple/pysqlite3-binary/
DEBUG Found not-modified response for: https://pypi.org/simple/pysqlite3-binary/
DEBUG Searching for a compatible version of pysqlite3-binary{sys_platform == 'linux'} (*)
DEBUG Selecting: pysqlite3-binary{sys_platform == 'linux'}==0.5.3 (pysqlite3_binary-0.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Searching for a compatible version of pysqlite3-binary{sys_platform == 'linux'} (==0.5.3)
DEBUG Selecting: pysqlite3-binary{sys_platform == 'linux'}==0.5.3 (pysqlite3_binary-0.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/2a/ec/3007532ea336d705f3abc7961f1a1c89f2fa34733b625ac317eea5a935ea/pysqlite3_binary-0.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Searching for a compatible version of pysqlite3-binary (==0.5.3)
DEBUG Selecting: pysqlite3-binary==0.5.3 (pysqlite3_binary-0.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Tried 1 versions: pysqlite3-binary 1
Resolved 1 package in 104ms
# This file was autogenerated by uv via the following command:
#    uv pip compile -
pysqlite3-binary==0.5.3
```

And my version:
```
$ uv version
uv 0.2.10
```

**Comment by charliermarsh** [comment] 2024-06-11 14:47
This is a duplicate of #1429.

**Closed by charliermarsh** 2024-06-11 14:47 UTC

**Comment by charliermarsh** [comment] 2024-06-11 14:50
As an aside: what `pip-compile` is doing there is not really safe (as in, you should not rely on those markers). Consider `flask ; python_version > '3.8'` as your input. `pip-compile` will resolve to:

```
blinker==1.8.2
    # via flask
click==8.1.7
    # via flask
flask==3.0.3 ; python_version > "3.8"
    # via -r req.in
itsdangerous==2.2.0
    # via flask
jinja2==3.1.4
    # via flask
markupsafe==2.1.5
    # via
    #   jinja2
    #   werkzeug
werkzeug==3.0.3
    # via flask
```

So the marker is only applied to the direct dependency, not any of its downstream dependencies. Retaining the markers leads to a resolution that is still incorrect on all other platforms.

**Comment by AbdealiLoKo** [comment] 2024-06-11 17:30
1. Thanks for the note on duplicate. For some reason I did not find it ! Probably searched for the wrong keywords
2. Hmm, you're right on pip-compile. Luckily I happen to use it only for this 1 dep which does not provide osx wheels and it doesn't have any other deps !
