### ISSUE TITLE
Configuration file Support

### ISSUE THREAD

**Issue by RianKoja** [astral-sh/uv#2640] opened 2024-03-24 20:31 UTC
https://github.com/astral-sh/uv/blob/a7b251f65e6d24855185c49bcbf64fc8bdfd7861/crates/uv/src/compat/mod.rs#L161

According to this line of code, there is no support for a configuration file. Is there any method to persistently set configurations?

What I used to wiht pip was:
```
pip config set global.trusted-host <my local nentwork pypi-server IP:port>
pip config set global.index-url http://<my local nentwork pypi-server IP:port>
```

I don't want to specify this all the time. Is there a workaround? I would need this both for windows and linux.

**Comment by charliermarsh** [comment] 2024-03-24 20:36
You can specify an index URL via environment variables (UV_INDEX_URL). But in general I’d recommend participating in the conversation here, since this request is mostly a duplicate of that issue: https://github.com/astral-sh/uv/issues/1404#issuecomment-2015778851.

**Comment by charliermarsh** [comment] 2024-03-24 20:37
(Merging into that issue.)

**Closed by charliermarsh** 2024-03-24 20:37 UTC
