### ISSUE TITLE
`--directory` should resolve relative paths relative to current working directory

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5613] opened 2024-07-30 17:24 UTC

**Comment by bluss** [comment] 2024-07-30 18:02
Uv run's external command is opaque (in meaning), so it's not possible to translate those arguments. One part of the solution for uv run could be either to never change current directory, or set cwd back to the original for the child process.

**Comment by charliermarsh** [comment] 2024-07-30 20:07
I was thinking that we’d remove the current set_directory call, and then pass around a project directory as dictated by the directory flag.

**Comment by abdok96** [comment] 2024-09-12 23:27
Do you have any timeline for this change by any chance? I'm currently using the hidden `--directory` option but it would be great if it can be made public (and ideally add an environment variable for it). Also resolving the paths relative to the passed directory is causing very weird issues in different places. I think this change is the correct choice.
 
Thanks for uv it is looking great!

**Comment by zanieb** [comment] 2024-09-13 01:57
per https://github.com/astral-sh/uv/issues/6733#issuecomment-2315983710 our existing behavior matches the Git and Cargo CLIs so we're very unlikely to change it.

The pre-commit example is great though. How do people work around this in other tools? Why do you need to use `--directory` in this situation? Maybe we need an environment variable to toggle.

**Comment by abdok96** [comment] 2024-09-13 02:32
Thanks for the quick reply. 
In our case, the simplified project structure was briefly something like:

my-project/
|__ app/
|    |__ main.py
|    |__ pyproject.toml  
|__ docker/
|__ docs/
|__ bin/
|__ docker-compose.yml
|__ .pre-commit.config.yaml

We also have a local hook for mypy something like:

```
  - repo: local
    hooks:
      - id: mypy
        name: run mypy check
        language: system
        entry: uv run --directory app -- mypy
        types_or: [python, pyi]
        require_serial: true
        args:
          - --config-file=pyproject.toml
```

We want to run the mypy command from the virtual environment that has all the python dependencies so that mypy can resolve and follow all the imports when running the type checks.

Because of the behavior of `--directory` we are passing config-file as `pyproject.toml` instead of `app/pyproject.toml` but that's okay since we can control it. 

However, when the commit hook is triggered by pre-commit, we have less control.
Let's say `app/main.py` was changed, the command executed by pre-commit will be something like:
`uv run --directory app -- mypy --config-file=pyproject.toml app/main.py`

And since the paths are resolved relative to the `--directory` param, mypy won't find a module matching `app/app/main.py`.

In our case, we managed to get around it in my case by moving the `pyproject.toml` to the root directory which is probably a more suitable place.  However, there might be similar cases that are a bit harder to avoid.

**Comment by abdok96** [comment] 2024-09-13 02:50
Btw, I'm not sure if it helps, but we are in the process of migrating from poetry to uv. I can confirm that in the case of poetry, the behavior is not similar to cargo or git. It resolves paths based on the working directory.  

For example, this is the same hook I mentioned in my previous comment, before the migration to uv:

```
  - repo: local
    hooks:
      - id: mypy
        name: run mypy check
        language: system
        entry: poetry --directory app run mypy
        types_or: [python, pyi]
        require_serial: true
        args:
          - --config-file=app/pyproject.toml
```

Notice how despite the --directory param, we used to pass the `--config-file` relative to the working directory not `/app`.
I guess both options have good arguments. A toggle like you suggested might help.

**Comment by bluss** [comment] 2024-09-13 06:36
@zanieb Unlikely to implement this issue? What do you think about adding a separate flag to uv run with the behaviour intended by this issue?

**Comment by aivarannamaa** [comment] 2024-09-13 22:44
Expanding on the comment from bluss -- What about adding `--env` or `--project`, which do not change the current directory, but simply indicate where to pick up the environment?

**Comment by aivarannamaa** [comment] 2024-09-13 23:31
One more idea: if `--project` references a script with inline metadata, this script would be used as the spec for the enironment to use.

For example:

* `uv python --project my_script_with_metadata.py find` would create and report the ephemeral interpreter which would be used for running this script
* `uv tree --project my_script_with_metadata.py` would list the packages in this ephemeral env. This would a good alternative for `uv tree --script my_script.py`, which I requested under #7328

I would use both of these forms for adding `uv` mode to [Thonny IDE](https://thonny.org/).

**Comment by charliermarsh** [comment] 2024-09-14 22:15
I am open to a dedicated `--project` flag on the `uv run`, `uv sync`, `uv lock`, etc. to inform workspace discovery. \cc @zanieb

**Comment by dragly** [comment] 2024-09-18 09:38
We are also very interested in a `--project` argument where the paths can remain relative to the current working directory. Our use-case is a monorepo where we are unable to use the workspace feature of `uv` due to conflicting dependencies between projects. This is the exact use of workspaces that is discouraged in the `uv` docs today.

(Another solution for us would be if `uv` had a feature where one could define a workspace without a shared `uv.lock`, but I think the `--project` argument sounds like a general solution that could solve more issues overall).

**Comment by bluss** [comment] 2024-09-18 18:54
When I take a first look at this, I think `--project` in `uv run --project` maybe needs to be a global argument as well? Because this logic is global (happens before any subcommand) and it is about project/workspace discovery. By the simplest logic: currently it's assumed project root is CWD (or found from CWD), the update needs to start with the user provided project directory instead of CWD here.

https://github.com/astral-sh/uv/blob/e36cc99b0d17e38be2c6fb09f02eb7489536176c/crates/uv/src/lib.rs#L103-L129

**Comment by zanieb** [comment] 2024-09-18 19:01
I'm also willing to have `--project` — though Charlie said it'd be a pain to add support :)

**Comment by charliermarsh** [comment] 2024-09-18 19:52
I think project is pretty straightforward since it’s limited in scope as to what it affects. I assume it affects project discovery and maybe python-version?

**Comment by charliermarsh** [comment] 2024-09-20 20:03
I'll do it.

**Comment by zanieb** [comment] 2024-09-20 20:04
Epic. Sounds good to me. The `python-version` file stuff might be easier with https://github.com/astral-sh/uv/pull/6370

**Closed** 2024-09-21 20:19 UTC
Labels: cli

**Comment by dragly** [comment] 2024-10-09 08:50
Thanks for implementing this! It works perfectly for our needs :)

**Comment by charliermarsh** [comment] 2024-10-09 09:05
That's great to hear :)
