### ISSUE TITLE
missing target for python 3.12-linux-armv7-musl

### ISSUE THREAD

**Issue by karmingc** [astral-sh/uv#9428] opened 2024-11-25 21:38 UTC
Currently using `uv` and trying to install python 3.12, but seeing the following error when it tries to install 3.12 on armv7 architecture on alpine linux.

```
error: No download found for request: cpython-3.12-linux-armv7-musl
```

**Comment by charliermarsh** [comment] 2024-11-25 21:39
Thanks -- this is a duplicate of #6890. We don't provide musl builds right now. I suggest using a non-musl glibc, or installing Python separately.

**Closed by charliermarsh** 2024-11-25 21:40 UTC
