### ISSUE TITLE
Project version managment with uv

### ISSUE THREAD

**Issue by evan-young-icx** [astral-sh/uv#8294] opened 2024-10-17 15:52 UTC
Hello, feature request: Poetry has commands for managing the version of the project in the pyproject.toml file. I am able to execute a Poetry command to bump the version in pyproject.toml and then read that value into an environment variable and use that to label a docker image build. There doesn't seem to be any project version management in UV as yet. See Poetry Documentation at [https://python-poetry.org/docs/cli/#version](https://python-poetry.org/docs/cli/#version)

**Comment by FishAlchemist** [comment] 2024-10-17 16:38
I think this issue is a duplicate of https://github.com/astral-sh/uv/issues/6298.

**Comment by charliermarsh** [comment] 2024-10-17 16:39
Yeah, makes sense to combine into that one.

**Closed by charliermarsh** 2024-10-17 16:39 UTC
