### ISSUE TITLE
Allow setting venv location in user level config

### ISSUE THREAD

**Issue by symroe** [astral-sh/uv#6413] opened 2024-08-22 07:45 UTC
For various reasons, I don't keep my `.venv` directory in the same directory as the project (as seems to be increasingly a convention and is default in `uv` currently).

I'm coming from using `virtualenvwrapper` where I could configure a `WORKON_HOME` as the location for the envs. 

I can replicate this for each venv with something like this:

`uv venv ~/.envs/$(basename "$PWD")`

However I think a limitation of this is that `uv` isn't able to automatically activate the venv when running e.g `uv sync`. 

It would be really nice to have the location (prefix to a directory containing them, defaulting to `.`) of the envs exposed in `~/.config/uv/uv.toml`. This, ideally, would then be respected in other commands like `uv sync`.

**Comment by symroe** [comment] 2024-08-22 07:46
Related https://github.com/astral-sh/uv/issues/5229

**Comment by zanieb** [comment] 2024-08-22 14:16
I think this is a duplicate of https://github.com/astral-sh/uv/issues/1495 (and #5229)

**Comment by symroe** [comment] 2024-08-22 20:13
Yep, sorry I missed that one :+1:

**Closed** 2024-08-22 20:14 UTC
Labels: duplicate, configuration
