### ISSUE TITLE
insufficient retrying around transient errors during `uv sync` (os error 104 in this case)

### ISSUE THREAD

**Issue by jgehrcke** [astral-sh/uv#8144] opened 2024-10-12 11:19 UTC
With uv 0.4.20 while running `uv sync --locked` I saw this:

```
...
2024-10-12T10:59:36.1923265Z Resolved 309 packages in 1ms
2024-10-12T10:59:42.4248290Z error: Failed to prepare distributions
2024-10-12T10:59:42.4252642Z   Caused by: Failed to fetch wheel: validators==0.20.0
2024-10-12T10:59:42.4257462Z   Caused by: Failed to resolve requirements from `setup.py` build
2024-10-12T10:59:42.4261587Z   Caused by: No solution found when resolving: `setuptools>=40.8.0`
2024-10-12T10:59:42.4265596Z   Caused by: request or response body error
2024-10-12T10:59:42.4269481Z   Caused by: error reading a body from connection
2024-10-12T10:59:42.4273696Z   Caused by: Connection reset by peer (os error 104)
2024-10-12T10:59:42.4366532Z ##[error]Process completed with exit code 2.
...
```
Environment: github actions

The log does not reveal if any retry was attempted. Such transient errors should certainly be retried for a small-ish number of times, up to a reasonable deadline.

As I have thought and talked a lot about the relevance of retries around transient errors in distributed systems and CI: once we improve the retrying logic it would be great to have explicit logs indicating those error and retries, leading up to success.

**Comment by zanieb** [comment] 2024-10-12 15:03
cc @konstin

**Comment by charliermarsh** [comment] 2024-10-12 15:07
> ...once we improve the retrying logic it would be great to have explicit logs indicating those error and retries, leading up to success.

I believe we already have this.

**Comment by konstin** [comment] 2024-10-12 15:39
If we did retry, we show "Request failed after 3 retries" in the error chain, so this error failed our retrying and was retried as it should have been.

Currently, we only show individual retries with eventual success with `-v`, but we can certainly bump that to a warning (<https://github.com/astral-sh/uv/blob/ad638d7fa394303f09d8bd0e8bde474702dff606/crates/uv-client/src/base_client.rs#L402-L413>)

**Comment by zanieb** [comment] 2024-10-12 16:00
> ... was retried as it should have been.

I'm confused, I don't see "after 3 retries" in the error message?

**Comment by konstin** [comment] 2024-10-12 16:03
there's was a _not_ critically missing in that sentence

**Comment by notatallshaw** [comment] 2024-10-12 16:04
I see this error occasionally, and need to rerun uv, if it is retrying it would be a better user experience to include how many times it retried in the final user error message, this would allow the user to be more empathetic to uv when it happens ("hey, at least it tried!").

**Comment by notatallshaw** [comment] 2024-10-12 16:08
Oh, with context of the *not*, as I reported in https://github.com/astral-sh/uv/issues/3514#issuecomment-2341462736, I also occasionally get this error and there is no mention of a retry.

**Comment by konstin** [comment] 2024-10-12 16:08
I agree that there should be messaging about retries, but iirc the problem here specifically is that that code path isn't in our retry logic at all (streaming or range requests, at least that what it's look likes from the logs, this needs a proper investigation of course), so what's missing is hooking this into our retry logic, which will then also print proper feedback about retries.

**Comment by notatallshaw** [comment] 2024-10-16 14:32
Sorry to harp on about this, but currently I've migrated my works dev environment tooling to uv, I took a look at migrating our build tooling to uv yesterday and faced this error several times.

Our build tooling has a lower tolerance for errors because it's more difficult to recover from, so I've put migrating on hold for now. 

I'm not in a rush, I can revisit this in the future, but I imagine it will cause other users not to migrate to uv, and they won't make a GitHub issue about it.

Let me know if there's anything useful I can run to help. I can't reproduce it consistently, but I'm happy to try a few times a week.

**Comment by konstin** [comment] 2024-10-17 10:46
I'm not clear where the error originates so I'm trying to get better traces with #8285.

**Comment by jgehrcke** [comment] 2024-10-22 12:12
I am following this with keen eyes. Thanks for the efforts here @konstin and also @notatallshaw for providing quick feedback.

**Comment by jgehrcke** [comment] 2024-10-30 14:46
Another one from within GitHub Actions CI:
```
2024-10-30T13:03:46.1241709Z Resolved 308 packages in 1ms
2024-10-30T13:03:48.9208986Z error: Failed to prepare distributions
2024-10-30T13:03:48.9210096Z   Caused by: Failed to download and build `coverage==6.3`
2024-10-30T13:03:48.9210805Z   Caused by: Failed to extract archive
2024-10-30T13:03:48.9212700Z   Caused by: failed to unpack `/home/runner/_work/_temp/setup-uv-cache/sdists-v5/.tmpz4MN4L/coverage-6.3/tests/test_misc.py`
2024-10-30T13:03:48.9214805Z   Caused by: failed to unpack `coverage-6.3/tests/test_misc.py` into `/home/runner/_work/_temp/setup-uv-cache/sdists-v5/.tmpz4MN4L/coverage-6.3/tests/test_misc.py`
2024-10-30T13:03:48.9216122Z   Caused by: error decoding response body
2024-10-30T13:03:48.9216690Z   Caused by: request or response body error
2024-10-30T13:03:48.9217275Z   Caused by: error reading a body from connection
2024-10-30T13:03:48.9217925Z   Caused by: stream closed because of a broken pipe
2024-10-30T13:03:48.9255280Z ##[error]Process completed with exit code 2.
```

This was `uv sync --locked` with `0.4.28`.

Instead of `Connection reset by peer (os error 104)` here we instead see `stream closed because of a broken pipe`. This is just another variant of a transport error. Transient. A little bit of retrying would have auto-healed this in all likelihood.

**Comment by notatallshaw-gts** [comment] 2024-10-30 15:12
This week my company made a change to their network security stack meaning I am unlikely to be able to reproduce this error again. So apologies, I see there was an additional PR that landed that gives more info but I am not likely going to be able to trigger it.

**Comment by jgehrcke** [comment] 2024-11-13 14:17
@konstin @charliermarsh I'd love to help here, retrying around transient errors is a passion of mine but I have no Rust experience. Meh.

What do we think about prioritizing this relative to other things?

We keep seeing this in CI every now and then. Of course, an outer retrying watchdog thingy can always do the trick, but now that `uv` is still so young it would be cool to show to the world that we take "best-best-best-effort retrying" serious :-) :heart:

Thanks again for all the great work you're doing.

**Comment by charliermarsh** [comment] 2024-11-18 15:29
Thanks for the verbose logs. We must still be missing a site or two.

**Comment by charliermarsh** [comment] 2024-11-18 17:16
(I'll try to debug today.)

**Comment by charliermarsh** [comment] 2024-11-18 20:47
I think the issue @notatallshaw-gts is experiencing is that we aren't retrying on body errors when fetching `.metadata` files.

**Comment by notatallshaw-gts** [comment] 2024-11-18 20:55
Yes, I think I mentioned it appeared to be the metadata before (https://github.com/astral-sh/uv/issues/3514#issuecomment-2341724943), of course, no idea if others have the same issue, but I'm seeing it on a very popular corporate firewall (Palo Alto).

**Comment by charliermarsh** [comment] 2024-11-18 21:00
Yeah I have a reproduction, we just don't seem to be retrying those, but it looks like we _should_ be so still trying to understand why.

**Closed** 2024-11-19 04:15 UTC
Labels: bug, help wanted, network

**Comment by notatallshaw-gts** [comment] 2024-11-19 20:20
FYI, I still got an error on 0.5.3  but I was running docker build without `--progress=plain` 😞, so I only have the last few lines and didn't see if retried or not. I'll open a new issue if I am able to catch it again with more context.
