### ISSUE TITLE
uv pip compile support for setup.py and install_requires

### ISSUE THREAD

**Issue by falkben** [astral-sh/uv#2167] opened 2024-03-04 18:18 UTC
It seems that currently `uv pip compile` only supports `pyproject.toml` and `requirements.in`. 

Will `uv pip compile` support `setup.py`'s `install_requires`? If advertising as a drop in replacement for `pip-tools`, it might be nice to call it out one way or another.

**Comment by zanieb** [comment] 2024-03-04 21:13
Hi. This looks like a duplicate of https://github.com/astral-sh/uv/issues/1624

**Comment by falkben** [comment] 2024-03-04 21:49
That issue is for setup.cfg. I was specifically asking about setup.py

**Comment by charliermarsh** [comment] 2024-03-04 21:52
👍 It's actually the same underlying problem, so I think it makes sense to merge into that issue.

**Closed by charliermarsh** 2024-03-04 21:52 UTC

**Comment by Angeluz-07** [comment] 2024-04-11 20:15
If anyone have issues with generating requirements.txt from setup.py, try updating uv to the latest version. I did it so. Currently I am using uv version `0.1.31`

**Comment by charliermarsh** [comment] 2024-04-11 20:16
👍 We added `setup.py` and `setup.cfg` support in a recent release.

**Comment by palfrey** [comment] 2024-04-28 15:51
For the record, https://github.com/astral-sh/uv/pull/2634 / [0.1.25](https://github.com/astral-sh/uv/releases/tag/0.1.25)
