### ISSUE TITLE
potential breaking change / bug in `uv==0.1.30`

### ISSUE THREAD

**Issue by zzstoatzz** [astral-sh/uv#2941] opened 2024-04-09 18:28 UTC
the following GHA step
```
- name: Install packages
  run: |
    python -m pip install -U uv
    uv pip install --upgrade --system -e .[dev]
```

started failing after the release of `0.1.30` with
```console
Run python -m pip install -U uv
Collecting uv
  Downloading uv-0.1.30-py3-none-manylinux_2_17_x86_64.manylinux20[14](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629#step:6:15)_x86_64.whl.metadata (26 kB)
Downloading uv-0.1.30-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 125.0 MB/s eta 0:00:00
Installing collected packages: uv
Successfully installed uv-0.1.30

Notice:  A new release of pip is available: 23.0.1 -> 24.0
Notice:  To update, run: pip install --upgrade pip
Built 1 editable in 1.[17](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629#step:6:18)s
error: Attempted to wait on an unregistered task
Error: Process completed with exit code 2.
```

full CI [run](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629) (not much else as far as logs unfortunately)

pinning to `0.1.29` appeared to resolve the issue

---

#### more potentially useful context

we use the following step before the install step, pending `setup-python` support
```
      - name: UV Cache
        # Manually cache the uv cache directory
        # until setup-python supports it:
        # https://github.com/actions/setup-python/issues/822
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: uvcache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements-client.txt', 'requirements.txt', 'requirements-dev.txt') }}
```

---
I don't have a strong hypothesis for why this error is occurring, sorry. let me know if there's anything useful I can provide

**Comment by zanieb** [comment] 2024-04-09 18:30
Thanks for the report Nate!

cc @charliermarsh

**Comment by zanieb** [comment] 2024-04-09 18:37
It does reproduce in CI though, here are the verbose logs https://github.com/zanieb/prefect/actions/runs/8620667551/job/23627935783

**Comment by zanieb** [comment] 2024-04-09 18:47
Presumably we fail at https://github.com/astral-sh/uv/blob/1512e07a2e7c05b7c9fcb457f35c7ef0f25d8d9b/crates/uv-resolver/src/resolver/mod.rs#L615

**Comment by hsheth2** [comment] 2024-04-09 18:48
We're seeing this in CI for the datahub project as well. It doesn't happen reliably though - seems like it impacts ~50% of our CI workflows, despite the matrixes being pretty similar.

https://github.com/datahub-project/datahub/actions/runs/8620627386/job/23627824491?pr=10256

**Comment by zanieb** [comment] 2024-04-09 19:03
We've identified this is most likely caused by #2452 and resolved by #2943 though we're still confirming with a reproduction. This wasn't caught by our unit test suite (and you'll only see it in some cases) because the cause is a performance optimization which is only applied when backtracking occurs several times.

**Comment by zanieb** [comment] 2024-04-09 19:10
I'll leave this open until we release.

**Comment by 0x2b3bfa0** [comment] 2024-04-09 19:18
Tangential remark: I was able to reproduce consistently with Python 3.9 but not with Python 3.12.

**Comment by charliermarsh** [comment] 2024-04-09 20:05
v0.1.31 is out now, which hopefully resolves this.

**Comment by zzstoatzz** [comment] 2024-04-09 20:15
it does indeed appear to be resolved on v0.1.31 ✨ 

thanks for the quick fix!

**Closed** 2024-04-09 20:24 UTC

**Comment by charliermarsh** [comment] 2024-04-09 20:33
Awesome, thanks for reporting, glad we could resolve!
