### ISSUE TITLE
Add support for `PIP_*` environment variable

### ISSUE THREAD

**Issue by Czaki** [astral-sh/uv#1841] opened 2024-02-21 23:21 UTC
Next to provide some options as command flag, the pip allows passing part of arugumnts using environment variable.  (see https://pip.pypa.io/en/stable/topics/configuration/#environment-variables) 

It will be nice if UV support this. Either by using `PIP_*` variables or for example using `UV_*`

In my case I heay use `PIP_CONSTRAINT` with `tox` as it allow to not need redefine install command. 
Especially now it will be really nice when user could choose backend (using `tox-uv` plugin). 

We need this ase our project has over 130 dependecies and has 

```toml
filterwarnings = [
  "error:::napari", # turn warnings from napari into errors
  ...
]
```
in project settings so we need to pin test depenedcies to not have unrelated test faliture.

**Comment by hauntsaninja** [comment] 2024-02-21 23:24
Duplicate of https://github.com/astral-sh/uv/issues/1789

**Comment by charliermarsh** [comment] 2024-02-22 00:48
Agree, want to add these.

**Closed by charliermarsh** 2024-02-22 00:48 UTC
