### ISSUE TITLE
Editable package install fails after a previous uninstall

### ISSUE THREAD

**Issue by amirhosseindavoody** [astral-sh/uv#2074] opened 2024-02-29 07:35 UTC
Steps to reproduce
* Activate a conda environment.
* Install a local package that I have using `uv pip install -e .`
* Uninstall the local package using `uv pip uninstall -e .`
* Install the local package again using `uv pip install -e .`

I get the following error:
```
error: Cannot uninstall package; RECORD file not found at: path/to/site-packages/mylib-0.1.dist-info/RECORD
```

If I manually remove `path/to/site-packages/mylib-0.1.dist-info` directory, then I am able to install my local package again.

**Comment by charliermarsh** [comment] 2024-02-29 14:39
Thanks! Probably my bug from the most recent release.

**Comment by charliermarsh** [comment] 2024-02-29 15:19
Do you get this consistently? I wasn't able to reproduce.

**Comment by amirhosseindavoody** [comment] 2024-02-29 17:56
I tried this with a fresh environment and the same error happened.

Some more details about my environment setup
* I am using `pixi` as the package manager.
* Then I install `uv` for my specific environment using `pixi add uv`
* Then I use `pixi shell` to activate the environment.
* Now I run the `uv pip install -e \path\to\my\local\package`
* The local package is using pyproject.toml for setup. Something similar to [this]( https://github.com/nedbat/pkgsample/blob/main/pyproject.toml)

**Comment by charliermarsh** [comment] 2024-02-29 18:01
Thanks, will try again.

**Comment by charliermarsh** [comment] 2024-02-29 18:12
This still worked for me even when running through pixi. Is there anything else you can share about your OS, etc.?

**Comment by amirhosseindavoody** [comment] 2024-02-29 19:01
My OS is Suse 12.

I don't know what else might help.

If this is not reproducible we can close this and others will open something if it happens again.

**Comment by charliermarsh** [comment] 2024-02-29 20:50
I believe it's a real problem if you're seeing it consistently. I just need to find a way to repro.

**Comment by iwane-pl** [comment] 2024-03-01 07:22
We've run on the same error when installing `lxml`, for example. The procedure was
```
PS C:\Users\me> C:\Python3.12\python.exe -m venv venv  
PS C:\Users\me> .\venv\Scripts\activate.ps1                                                                                    
(venv) PS C:\Users\me> uv pip install lxml==5.1.0                                                                              
Resolved 1 package in 4ms                                                                                                       
Installed 1 package in 50ms                                                                                                     
 + lxml==5.1.0                                                                                                                  
(venv) PS C:\Users\me> uv pip install lxml==4.9.3                                                                              
Resolved 1 package in 4ms                                                                                                       
Installed 1 package in 51ms                                                                                                     
 - lxml==5.1.0                                                                                                                  
 + lxml==4.9.3                                                                                                                  
(venv) PS C:\Users\me> uv pip install lxml==5.1.0                                                                              
Resolved 1 package in 4ms                                                                                                       
error: Cannot uninstall package; RECORD file not found at: C:\Users\me\venv\Lib\site-packages\lxml-5.1.0.dist-info\RECORD 
```
OS info:
```
# Windows Server 2016
> (Get-CimInstance Win32_OperatingSystem).version
10.0.14393    
> python --version                                                                                        
Python 3.12.2
> uv --version                                                                                            
uv 0.1.12 (f68b2d1d5 2024-02-28)
```

**Comment by konstin** [comment] 2024-03-01 10:40
I tried on my windows desktop but i can't reproduce it there

```
PS C:\Users\Konsti\projects\uv> python.exe -m venv venv 
PS C:\Users\Konsti\projects\uv> .\venv\Scripts\activate.ps1            
(venv) PS C:\Users\Konsti\projects\uv> powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
Downloading uv 0.1.13 (x86_64-pc-windows-msvc)
Installing to C:\Users\Konsti\.cargo\bin
  uv.exe
Everything's installed!
(venv) PS C:\Users\Konsti\projects\uv> uv --version
uv 0.1.13 (9ce5170e6 2024-02-29)
(venv) PS C:\Users\Konsti\projects\uv>  uv pip install lxml==5.1.0                                 

Resolved 1 package in 228ms
Downloaded 1 package in 366ms
Installed 1 package in 65ms
 + lxml==5.1.0
(venv) PS C:\Users\Konsti\projects\uv> uv pip install lxml==4.9.3                         
Resolved 1 package in 170ms
Downloaded 1 package in 473ms
Installed 1 package in 59ms
 - lxml==5.1.0
 + lxml==4.9.3
(venv) PS C:\Users\Konsti\projects\uv> uv pip install lxml==5.1.0                 
Resolved 1 package in 2ms
Installed 1 package in 68ms
 - lxml==4.9.3
 + lxml==5.1.0
```

**Comment by iwane-pl** [comment] 2024-03-01 12:02
:thinking: 
I tried on other Windows versions too.

```
# Win10

PS C:\Users\9ld> (Get-CimInstance Win32_OperatingSystem).version
10.0.19045
PS C:\Users\9ld> C:\Python3.12\python.exe -m venv venv
PS C:\Users\9ld> .\venv\Scripts\activate.ps1
(venv) PS C:\Users\9ld> uv pip install lxml==5.1.0
Resolved 1 package in 84ms
Downloaded 1 package in 150ms
Installed 1 package in 82ms
 + lxml==5.1.0
(venv) PS C:\Users\9ld> uv pip install lxml==4.9.3
Resolved 1 package in 47ms
Downloaded 1 package in 156ms
Installed 1 package in 107ms
 - lxml==5.1.0
 + lxml==4.9.3
(venv) PS C:\Users\9ld> uv pip install lxml==5.1.0 
Resolved 1 package in 6ms
Installed 1 package in 75ms
 - lxml==4.9.3
 + lxml==5.1.0


# WinServer2019

PS C:\Users\9ld> (Get-CimInstance Win32_OperatingSystem).version
10.0.17763
PS C:\Users\9ld> C:\Python3.12\python.exe -m venv venv
PS C:\Users\9ld> .\venv\Scripts\activate.ps1
(venv) PS C:\Users\9ld> uv pip install lxml==5.1.0
Resolved 1 package in 84ms
Downloaded 1 package in 199ms
Installed 1 package in 66ms
 + lxml==5.1.0
(venv) PS C:\Users\9ld> uv pip install lxml==4.9.3
Resolved 1 package in 33ms
Downloaded 1 package in 224ms
Installed 1 package in 68ms
 - lxml==5.1.0
 + lxml==4.9.3
(venv) PS C:\Users\9ld> uv pip install lxml==5.1.0
Resolved 1 package in 7ms
error: Cannot uninstall package; RECORD file not found at: C:\Users\9ld\venv\Lib\site-packages\lxml-5.1.0.dist-info\RECORD 

# WinServer2022

PS C:\Users\9ld> (Get-CimInstance Win32_OperatingSystem).version
10.0.20348
PS C:\Users\9ld> C:\Python3.12\python.exe -m venv venv  
PS C:\Users\9ld> .\venv\Scripts\activate.ps1
(venv) PS C:\Users\9ld> uv pip install lxml==5.1.0
Resolved 1 package in 187ms
Downloaded 1 package in 158ms
Installed 1 package in 88ms
 + lxml==5.1.0
(venv) PS C:\Users\9ld> uv pip install lxml==4.9.3
Resolved 1 package in 35ms
Downloaded 1 package in 142ms
Installed 1 package in 87ms
 - lxml==5.1.0
 + lxml==4.9.3
(venv) PS C:\Users\9ld> uv pip install lxml==5.1.0
Resolved 1 package in 21ms
Installed 1 package in 110ms
 - lxml==4.9.3
 + lxml==5.1.0
```

It seems like it reproduces on older Windows versions. Updated Win10 and WinServer2022 seem unaffected, while WinServer2016 and 2019 fail.

**Comment by gozdal** [comment] 2024-03-06 18:00
As @iwane-pl noticed, this happens on Windows 2016 and 2019 but not on Windows 10 and 2022.
The difference is that after an uninstall an empty directory is left befind. E.g. if you have `lxml==5.1.0` installed and you downgrade to `lxml==4.9.3` then `site-packages` will have
```
venv\Lib\site-packages\lxml-4.9.3.dist-info
venv\Lib\site-packages\lxml-5.1.0.dist-info
```

Where 5.1.0 dir will be empty and hence the error
```
error: Cannot uninstall package; RECORD file not found at: venv\Lib\site-packages\lxml-5.1.0.dist-info\RECORD
```

Curiously enough it happens only on selected Windows version.

**Comment by charliermarsh** [comment] 2024-03-06 18:02
My guess is that this is due to delayed file deletion...? E.g., we delete a file, then test if a directory is empty, and delete the directory if so; but I believe there can be temporary inconsistencies, such that when you delete a file, it may still "exist" for some period of time, or something like that.

**Comment by gozdal** [comment] 2024-03-06 18:14
It's 100% reproducible, so I'd say it's not a race. Could try Process Monitor tomorrow to see what's happening.

**Comment by charliermarsh** [comment] 2024-03-06 18:23
Yeah what I'm describing could still be consistent with it being 100% reproducible.

**Comment by charliermarsh** [comment] 2024-03-06 18:24
I don't have a system to test this on, so the best I can do is try a refactor and ask someone here to test it.

**Comment by charliermarsh** [comment] 2024-03-07 03:22
Good news, I'm able to reproduce this on Windows 2019 in GitHub Actions! https://github.com/astral-sh/uv/pull/2259

**Comment by charliermarsh** [comment] 2024-03-07 04:35
Ok, I believe this is fixed by https://github.com/astral-sh/uv/pull/2259. If you're able to reproduce after the next release, please let me know.

**Closed** 2024-03-07 04:35 UTC
Labels: bug, needs-mre
