### ISSUE TITLE
uv pip compile skips optional dependencies

### ISSUE THREAD

**Issue by nmichlo** [astral-sh/uv#3343] opened 2024-05-03 11:38 UTC
Create `r.txt`

```
qdrant-client~=1.6.1
```

**uv**:

Now compile:

```
uv pip compile r.txt
```

Gives:

```
# This file was autogenerated by uv via the following command:
#    uv pip compile r.txt
annotated-types==0.6.0
    # via pydantic
anyio==4.3.0
    # via httpx
certifi==2024.2.2
    # via
    #   httpcore
    #   httpx
exceptiongroup==1.2.1
    # via anyio
grpcio==1.63.0
    # via
    #   grpcio-tools
    #   qdrant-client
grpcio-tools==1.63.0
    # via qdrant-client
h11==0.14.0
    # via httpcore
h2==4.1.0
    # via httpx
hpack==4.0.0
    # via h2
httpcore==1.0.5
    # via httpx
httpx==0.27.0
    # via qdrant-client
hyperframe==6.0.1
    # via h2
idna==3.7
    # via
    #   anyio
    #   httpx
numpy==1.26.4
    # via qdrant-client
portalocker==2.8.2
    # via qdrant-client
protobuf==5.26.1
    # via grpcio-tools
pydantic==2.7.1
    # via qdrant-client
pydantic-core==2.18.2
    # via pydantic
qdrant-client==1.6.9
setuptools==69.5.1
    # via grpcio-tools
sniffio==1.3.1
    # via
    #   anyio
    #   httpx
typing-extensions==4.11.0
    # via
    #   anyio
    #   pydantic
    #   pydantic-core
urllib3==1.26.18
    # via qdrant-client
```

The important difference to look for is `httpx==0.27.0`

**pip-tools v7**:

Compare this to `pip-tools`

```
pip-compile r.txt -o out.txt
```

Output

```
#
# This file is autogenerated by pip-compile with Python 3.9
# by the following command:
#
#    pip-compile --output-file=out.txt r.txt
#
annotated-types==0.6.0
    # via pydantic
anyio==4.3.0
    # via httpx
certifi==2024.2.2
    # via
    #   httpcore
    #   httpx
exceptiongroup==1.2.1
    # via anyio
grpcio==1.63.0
    # via
    #   grpcio-tools
    #   qdrant-client
grpcio-tools==1.63.0
    # via qdrant-client
h11==0.14.0
    # via httpcore
h2==4.1.0
    # via httpx
hpack==4.0.0
    # via h2
httpcore==1.0.5
    # via httpx
httpx[http2]==0.27.0
    # via qdrant-client
hyperframe==6.0.1
    # via h2
idna==3.7
    # via
    #   anyio
    #   httpx
numpy==1.26.4
    # via qdrant-client
portalocker==2.8.2
    # via qdrant-client
protobuf==5.26.1
    # via grpcio-tools
pydantic==2.7.1
    # via qdrant-client
pydantic-core==2.18.2
    # via pydantic
qdrant-client==1.6.9
    # via -r r.txt
sniffio==1.3.1
    # via
    #   anyio
    #   httpx
typing-extensions==4.11.0
    # via
    #   anyio
    #   pydantic
    #   pydantic-core
urllib3==1.26.18
    # via qdrant-client

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

The important difference to look for is `httpx[http2]==0.27.0`

ALTHOUGH, in version `v8` the `--strip-extras` flag is being added which can remove this.

**Comment by zanieb** [comment] 2024-05-03 13:15
Hi looks like a duplicate of https://github.com/astral-sh/uv/issues/2163 — the default behavior is changing in pip-tools to match ours. You can use `--no-strip-extras` if you want it.

**Closed by zanieb** 2024-05-03 13:15 UTC

**Comment by nmichlo** [comment] 2024-05-07 18:53
Oops, thank you! Didn't realise that was already added.
