### ISSUE TITLE
Duplicate package in requirements

### ISSUE THREAD

**Issue by dmwyatt** [astral-sh/uv#2639] opened 2024-03-24 20:09 UTC
```
# requirements.in
Django
django-environ
django-vite
httpx
whitenoise[brotli]
```

```
# dev-requirements.in
-c requirements.txt
mdformat-gfm
pytest
pytest-asyncio
pytest-django
pytest-httpx
```

```shell
$ uv pip compile requirements.in -o requirements.txt && uv pip compile dev-requirements.in -o dev-requirements.txt
Resolved 15 packages in 251ms
Resolved 23 packages in 6ms
```

```shell
$ uv pip sync .\requirements.txt .\dev-requirements.txt                                                                                                                             
error: Failed to determine installation plan
  Caused by: Detected duplicate package in requirements: anyio
```

Of note, `pip-tools` doesn't care about the duplicate package.  The duplicate package exists because `pytest-httpx` depends on `httpx` which depends on `anyio`.  I require `httpx` in my main requirements, and `pytest-httpx` in my dev requirements.

**Comment by zanieb** [comment] 2024-03-24 20:17
I think you probably want to include both your standard requirements and your development requirements in your development lockfile e.g.

```
pip compile requirements.in dev-requirements.in -o dev-requirements.txt
```

or in `dev-requirements.in` you should include a reference to your `requirements.in` file.

Otherwise you're creating a resolution which does not include all of your standard requirements and is not valid for performing a sync.

**Comment by charliermarsh** [comment] 2024-03-24 20:21
Yeah, this seems correct to me (unless we have a bug here), since that error message is only intended to pop up when you have the same requirement with two different versions. If the versions are different between your two lock files, we should error like this. If the versions are the same in `requirements.txt` and `dev-requirements.txt`, then I'd consider it a bug.

**Comment by dmwyatt** [comment] 2024-03-24 20:46
So, in my original post I forgot to add `-c requirements.txt` to my example `requirements.in`. I've now updated that.

The `pip-tools` [recommended way of doing](https://github.com/jazzband/pip-tools#workflow-for-layered-requirements) this is as I described in my original post. 

1. compile requirements.in
2. compile dev-requirements.in
3. sync both resulting .txt files

I certainly understand if `uv` isn't meant to be 100% compatible with `pip-tools`. Not sure if this is a case of unsupported use case or a bug.

However, this sounds like a bug:

> If the versions are the same in requirements.txt and dev-requirements.txt, 

The versions are the same:

```
# requirements.txt
anyio==4.3.0
    # via httpx
```

```
# dev-requirements.txt
anyio==4.3.0
    # via httpx
```

**Comment by charliermarsh** [comment] 2024-03-24 21:07
I’ll take a look! If they’re the same version, it should work.

**Comment by zanieb** [comment] 2024-03-24 21:54
Thanks for clarifying! This indeed sounds like a bug.

**Comment by charliermarsh** [comment] 2024-03-24 22:31
Unfortunately I'm not able to reproduce:

```
❯ cargo run pip sync requirements.txt dev-requirements.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/uv pip sync requirements.txt dev-requirements.txt`
Installed 29 packages in 62ms
 + anyio==4.3.0
 + asgiref==3.8.1
 + brotli==1.1.0
 + certifi==2024.2.2
 + django==5.0.3
 + django-environ==0.11.2
 + django-vite==3.0.3
 + h11==0.14.0
 + httpcore==1.0.4
 + httpx==0.27.0
 + idna==3.6
 + iniconfig==2.0.0
 + linkify-it-py==2.0.3
 + markdown-it-py==3.0.0
 + mdformat==0.7.17
 + mdformat-gfm==0.3.6
 + mdformat-tables==0.4.1
 + mdit-py-plugins==0.4.0
 + mdurl==0.1.2
 + packaging==24.0
 + pluggy==1.4.0
 + pytest==8.1.1
 + pytest-asyncio==0.23.6
 + pytest-django==4.8.0
 + pytest-httpx==0.30.0
 + sniffio==1.3.1
 + sqlparse==0.4.4
 + uc-micro-py==1.0.3
 + whitenoise==6.6.0
```

**Comment by charliermarsh** [comment] 2024-03-24 22:33
Can you share the exact command you ran to trigger the error, along with the input `requirements.txt` and `dev-requirements.txt` files, and your uv version?

**Comment by charliermarsh** [comment] 2024-03-26 21:03
Closing but happy to revisit if more info comes in!

**Closed by charliermarsh** 2024-03-26 21:03 UTC
Labels: needs-mre

**Comment by nilleb** [comment] 2024-04-16 07:36
@charliermarsh could you have a look at [this gist](https://gist.github.com/nilleb/352ec9e83942f06382d33d382becd5f6) please?

the problem is visible when uncommenting that aider-chat - the anyio requirement moves to 4.2.0 and uv sync does not work anymore

I hope this helps!
