### ISSUE TITLE
[Feature request] `uv` command to update package version in `pyproject.toml`

### ISSUE THREAD

**Issue by albertferras-vrf** [astral-sh/uv#6430] opened 2024-08-22 13:18 UTC
Currently, we have a command to add dependencies to `pyproject.toml` like this: `uv add package==1.2.3`
It would be nice if we could also bump our package version (project.version) through a command, too. 

I have two different use cases which would get simpler to do:
- Our CI builds and release 'dev version' packages on every commit
- We have >5 packages in some of our projects, which must all be bumped together when any of them changes (they all depend on some common lib, kind of similar to `botocore` stuff), so we have custom script to update all `version` from all packages.

**Comment by zanieb** [comment] 2024-08-22 13:33
Duplicate of https://github.com/astral-sh/uv/issues/6298

**Comment by zanieb** [comment] 2024-08-22 13:33
Totally agree though :)

**Closed by zanieb** 2024-08-22 13:33 UTC
