### ISSUE TITLE
Wishlist: let uv tool symlink manual pages

### ISSUE THREAD

**Issue by callegar** [astral-sh/uv#8209] opened 2024-10-15 10:28 UTC
For uv tool to be at feature parity with `pipx`, I think it would be good to symlink not just the executables themselves into `~/.local /bin`, but to also offer the possibility to link their manual pages (if available) into `~/.local/share/man`.

A good example is the `sympy` package that offers the `isympy` tools with a manual page.

See also https://github.com/pypa/pipx/issues/857 and https://github.com/pypa/pipx/pull/1047

**Comment by zanieb** [comment] 2024-10-15 13:53
Duplicate of https://github.com/astral-sh/uv/issues/4731

**Closed by zanieb** 2024-10-15 13:53 UTC
