### ISSUE TITLE
uv created a new venv instead of using the one I was already in

### ISSUE THREAD

**Issue by antonysouthworth-halter** [astral-sh/uv#6849] opened 2024-08-30 02:56 UTC
```bash
asdf local python 3.12.5
python -m venv venv
. venv/bin/activate
uv add ruff # <- this creates a new venv at .venv?? Why??
```

# uv version:

```bash
$ uv --version
uv 0.4.0 (d9bd3bc7a 2024-08-28)
```

# my machine

```bash
$ uname -a
Darwin Antonys-MacBook-Pro.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 x86_64 i386 Darwin
```

**Comment by antonysouthworth-halter** [comment] 2024-08-30 03:11
(yes, I know this is documented behaviour at https://docs.astral.sh/uv/concepts/projects/#project-environments, but if I ran into this issue I am betting others will end up here as well)

**Comment by zanieb** [comment] 2024-08-30 03:32
Hi! This is a duplicate of https://github.com/astral-sh/uv/issues/6612

**Closed** 2024-09-08 18:19 UTC
Labels: duplicate
