### ISSUE TITLE
Add `uv pip wheel` command

### ISSUE THREAD

**Issue by Warchant** [astral-sh/uv#7811] opened 2024-09-30 14:32 UTC
`pip wheel` command downloads all `*.whl` files of a specific module/requirements.txt/file.whl into a cwd.

This issue is a request to implement `uv pip wheel` command.

As of `uv 0.4.17` it is not there.

**Comment by notatallshaw-gts** [comment] 2024-09-30 15:55
Duplicate of https://github.com/astral-sh/uv/issues/1681

**Closed** 2024-09-30 16:30 UTC
