### ISSUE TITLE
uv install 0.5.0 sh: line 1027: _force_install_dir: unbound variable

### ISSUE THREAD

**Issue by fraser-langton** [astral-sh/uv#8917] opened 2024-11-08 05:19 UTC
Quite bizarre, the same install just started failing, without any changes, and it looks like it's the same version

before (30 mins ago)

```shell
downloading uv 0.5.0 x86_64-unknown-linux-musl-static
installing to /root/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
3.8s
```

now

```shell
downloading uv 0.5.0 x86_64-unknown-linux-musl-static

sh: line 1027: _force_install_dir: unbound variable
```

Edit:
seems to be a widespread issue with a later release of the 0.5.0 install.sh - because the release itself was about 6 hours ago, but only started seeing this an hour ago and I had a working version of 0.5.0 at some point 🤔

**Comment by GitHK** [comment] 2024-11-08 05:28
I'm also seeing this issue.

**Comment by fraser-langton** [comment] 2024-11-08 05:28
`curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.4.30/uv-installer.sh | sh` works, but downgrading also has breaking changes to PATH 🥺

**Comment by zanieb** [comment] 2024-11-08 05:38
Thanks for the report! Looks like this broke while patching a `uv self update` bug. I'll have a fix up quickly.

**Comment by areddy-qontigo** [comment] 2024-11-08 05:40
Inside docker file, I have updated the PATH as temporary workaround.

```
RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.4.30/uv-installer.sh | sh && \
    /root/.cargo/bin/uv python install ${PYTHON_VERSION} && \
    /root/.cargo/bin/uv venv /opt/venv --python ${PYTHON_VERSION}

```

**Comment by ChillarAnand** [comment] 2024-11-08 05:41
Inside docker file, I have updated the PATH as temporary workaround.

```
RUN curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.4.30/uv-installer.sh | sh && \
    /root/.cargo/bin/uv python install ${PYTHON_VERSION} && \
    /root/.cargo/bin/uv venv /opt/venv --python ${PYTHON_VERSION}
```

**Comment by zanieb** [comment] 2024-11-08 05:42
It should be fixed now. Let me know if not.

**Comment by fraser-langton** [comment] 2024-11-08 05:45
@zanieb I was about to share my hacky fix `curl -LsSf https://astral.sh/uv/install.sh | sed 's/^_force_install_dir="$_force_install_dir"/_force_install_dir="${_force_install_dir:-}"/' | sh` 😅

**Comment by ChillarAnand** [comment] 2024-11-08 05:48
@zanieb It is working now. Thanks for quick fix.

**Comment by zanieb** [comment] 2024-11-08 05:49
Thanks for the reports! Sorry about the disruption.

Caused by https://github.com/axodotdev/axoupdater/issues/210

**Closed by zanieb** 2024-11-08 05:49 UTC

**Comment by GitHK** [comment] 2024-11-08 05:50
something looks wired `~/.cargo/bin/uv` is no longer found after this while it used to work in the previous version

**Comment by fraser-langton** [comment] 2024-11-08 05:52
> @zanieb something looks wired `~/.cargo/bin/uv` is no longer found after the fix, while it used to work in the previous version

I believe that is intentional https://github.com/astral-sh/uv/releases/tag/0.5.0

> Previously, uv's installer used $CARGO_HOME or ~/.cargo/bin for its target install directory. It's been a longstanding complaint that uv uses this directory, as there's no relationship to Cargo. Now, uv will be installed into $XDG_BIN_HOME, $XDG_DATA_HOME/../bin, or ~/.local/bin (in that order). Note that $UV_INSTALL_DIR can always be used to override the target directory.

**Comment by zanieb** [comment] 2024-11-08 05:54
`uv self update` will preserve a previous install location, but new installs will use the new one 👍
