### ISSUE TITLE
build tool

### ISSUE THREAD

**Issue by confucuis** [astral-sh/uv#10019] opened 2024-12-19 02:56 UTC
Can the project come up with a java-like maven packaging feature that can package a python project and its dependencies into a single file. The packaged file can be run directly using the python interpreter. I've used a few packaging tools: zipapp, shiv, pex. none of them are very good. I'm looking forward to seeing this feature in the project.

**Comment by zanieb** [comment] 2024-12-19 04:01
We're interested, but it's not on the immediate roadmap.

Duplicate of https://github.com/astral-sh/uv/issues/5802

**Closed by zanieb** 2024-12-19 04:01 UTC

**Comment by confucuis** [comment] 2024-12-20 06:17
I mean just packaging the source code and dependencies of a python project into a package, like the standard library zipapp, but zipapp will have problems with dependencies not being found when packaging some three-way dependencies. For example, when using zipapp package to package a fastapi development project, there will be a problem that pydantic's three-way dependency can't be found
