### ISSUE TITLE
--no-binarry appears to be unsupported

### ISSUE THREAD

**Issue by ionelmc** [astral-sh/uv#2594] opened 2024-03-21 17:37 UTC
Using `uv 0.1.23`.

I have this requirements file (hereby named `test.in`):
```
--no-binary=psycopg2
psycopg2
```

Using `pip-compile test.in` produces this:
```
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile test.in
#
--no-binary psycopg2

psycopg2==2.9.9
    # via -r test.in
```

However, using `uv pip compile test.in` just errors with:
```
error: Unexpected '-', expected '-c', '-e', '-r' or the start of a requirement at test.in:1:1
```

**Comment by charliermarsh** [comment] 2024-03-21 17:39
Thanks, this is a duplicate of https://github.com/astral-sh/uv/issues/1461. We support `--no-binary` on the command-line, but not in a requirements file.

**Closed by charliermarsh** 2024-03-21 17:39 UTC
