### ISSUE TITLE
Unable to install `scikit-image==0.19.3`

### ISSUE THREAD

**Issue by pngwn** [astral-sh/uv#1813] opened 2024-02-21 14:45 UTC
When i try to install `scikit-image==0.19.3` (`uv pip install scikit-image==0.19.3`) i get the following error (truncated version) after a very very long time (probably around a minute or two).

```
error: Failed to download distributions
  Caused by: Failed to fetch wheel: scikit-image==0.19.3
  Caused by: Failed to build: scikit-image==0.19.3
  Caused by: Build backend failed to build wheel through `build_wheel()`:
```

Full logs are very long so I have put them here: https://app.warp.dev/block/aP3dM9N3p6kVKSj5bqOijF

The second time i run it, it fails much more quickly but with the same output.

Platform: macOS
Version: 0.1.6

**Comment by rth** [comment] 2024-02-21 16:19
The relevant error message from that log may be,
```
clang: error: unsupported option '-fopenmp'
```
It's a fairly old scikit-image release, are you sure you are able to rebuild it with pip, and it's not taking a wheel that was built with pip some time ago from the cache?

**Comment by zanieb** [comment] 2024-02-21 19:52
I reproduced this on my M1 Mac as well.

**Comment by charliermarsh** [comment] 2024-02-22 05:12
@zanieb - Can you see if this was fixed in v0.1.7?

**Comment by charliermarsh** [comment] 2024-03-08 20:56
Can anyone confirm that this is still an issue? Something we can repro?

**Comment by pngwn** [comment] 2024-03-08 21:02
I'll retest with the latest version.

**Comment by charliermarsh** [comment] 2024-03-08 21:09
Good news! I was able to reproduce by downgrading to Python 3.11, while `python -m pip` succeeded after a long build process in both cases. Will look into it.

**Comment by charliermarsh** [comment] 2024-03-08 21:11
Not immediately clear what could be going wrong, my guess is we're not propagating an environment variable or something.

**Comment by charliermarsh** [comment] 2024-03-08 21:34
Assigning to myself.

**Comment by charliermarsh** [comment] 2024-03-09 02:29
Ohhh the build doesn't actually fail, we just can't find the distribution filename because it's not at the end of the stdout...

```
...
scikit_image-0.19.3-cp311-cp311-macosx_14_0_arm64.whl
INFO:
########### EXT COMPILER OPTIMIZATION ###########
INFO: Platform      :
  Architecture: aarch64
  Compiler    : clang

CPU baseline  :
  Requested   : 'min'
  Enabled     : NEON NEON_FP16 NEON_VFPV4 ASIMD
  Flags       : none
  Extra checks: none

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : ASIMDHP ASIMDDP ASIMDFHM
  Generated   : none
INFO: CCompilerOpt.cache_flush[864] : write cache to path -> /private/var/folders/nt/6gf2v7_s3k13zq_t3944rwz40000gn/T/.tmp5ZPIbv/built-wheels-v0/pypi/scikit-image/0.19.3/hLW_f7wWeGDOPRlSazQXw/scikit-image-0.19.3.tar.gz/build/temp.macosx-12.6-arm64-3.11/ccompiler_opt_cache_ext.py
```

**Comment by charliermarsh** [comment] 2024-03-09 03:19
Fixed in https://github.com/astral-sh/uv/pull/2314.

**Closed** 2024-03-09 11:49 UTC
Labels: bug, installer
