### ISSUE TITLE
uv venv --seed creates pip command with wrong python version

### ISSUE THREAD

**Issue by wimglenn** [astral-sh/uv#1783] opened 2024-02-20 21:09 UTC
uv 0.1.6 on Linux.

python3 command is pointing at a Python 3.12.2 installation.

uv venv --seed creates a pip3.10 command for some reason.

```
$ python3 -VV
Python 3.12.2 (main, Feb 14 2024, 10:38:08) [GCC 13.2.0]
$ uv venv --seed
Using Python 3.12.2 interpreter at /path/to/Python-3.12.2/bin/python3.12
Creating virtualenv at: .venv
 + pip==24.0
Activate with: source .venv/bin/activate
$ ls .venv/bin/
activate  activate.bat  activate.csh  activate.fish  activate.nu  activate.ps1  activate_this.py  deactivate.bat  pip  pip3  pip3.10  pydoc.bat  python  python3  python3.12
$ .venv/bin/python3 -V
Python 3.12.2
$ .venv/bin/pip3.10 --version
pip 24.0 from /tmp/x/.venv/lib/python3.12/site-packages/pip (python 3.12)
```

Why is it named pip3.10?  Using `python3 -m venv .venv` creates `pip3.12` as expected.

```
$ rm -rf .venv
$ python3 -m venv .venv
$ ls .venv/bin/
activate  activate.csh  activate.fish  Activate.ps1  pip  pip3  pip3.12  python  python3  python3.12
```

**Comment by AlexWaygood** [comment] 2024-02-20 21:17
Thanks! Closing as a duplicate of  #1593

**Closed by AlexWaygood** 2024-02-20 21:17 UTC
