### ISSUE TITLE
[Error]stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by sdbds** [astral-sh/uv#8009] opened 2024-10-08 16:42 UTC
#7726 

command: uv pip install crcmod==1.7
platform:windows
version:uv 0.4.19 (a451fb685 2024-10-07)

```
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: crcmod==1.7
  Caused by: Failed to run `C:\Users\QINGLO~1\AppData\Local\Temp\.tmpSyOjmr\builds-v0\.tmps5aMOw\Scripts\python.exe`
  Caused by: stream did not contain valid UTF-8
```

**Comment by BurntSushi** [comment] 2024-10-08 16:49
Can you share the output of running `chcp`? That should print the codepage you're using.

**Comment by konstin** [comment] 2024-10-08 16:51
Additionally, which terminal/shell are you using? I couldn't reproduce this on my windows machine (german locale, codepage 850, powershell)

**Comment by sdbds** [comment] 2024-10-08 17:02
> Can you share the output of running `chcp`? That should print the codepage you're using.

Chinese locale, codepage 936, powershell 7.4.5

**Comment by sdbds** [comment] 2024-10-08 17:47
crcmod==1.7
    # via oss2
oss2==2.19.0
    # via funasr
funasr==1.1.5
    # via fish-speech (./pyproject.toml)

**Comment by kahojyun** [comment] 2024-10-09 02:20
Please try install with `pip install -v --no-cache-dir crcmod==1.7` and `uv pip install -vv -n crdmod==1.7`. It should print the output of build script like:
```
❯ .venv\Scripts\pip.exe install --no-cache-dir -v crcmod==1.7
Using pip 24.2 from E:\tt\.venv\lib\site-packages\pip (python 3.8)
Collecting crcmod==1.7
  Downloading crcmod-1.7.tar.gz (89 kB)
  Running command python setup.py egg_info
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: crcmod
  Running command python setup.py bdist_wheel
  _crcfunext.c
     Creating library build\temp.win-amd64-cpython-38\Release\python3\src\_crcfunext.cp38-win_amd64.lib and object build\temp.win-amd64-cpython-38\Release\python3\src\_crcfunext.cp38-win_amd64.exp
  Generating code
  Finished generating code
  E:\tt\.venv\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
  !!

          ********************************************************************************
          Please avoid running ``setup.py`` directly.
          Instead, use pypa/build, pypa/installer or other
          standards-based tools.

          See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
          ********************************************************************************

  !!
    self.initialize_options()
  E:\tt\.venv\lib\site-packages\setuptools\command\bdist_wheel.py:115: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
    if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
  Building wheel for crcmod (setup.py) ... done
  Created wheel for crcmod: filename=crcmod-1.7-cp38-cp38-win_amd64.whl size=25415 sha256=777a3c9daadf2c05407249df3af462e8da226d1099a33f1f34328c1238e164e1
  Stored in directory: C:\Users\kahoj\AppData\Local\Temp\pip-ephem-wheel-cache-5cky5nzg\wheels\ca\5a\02\f3acf982a026f3319fb3e798a8dca2d48fafee7761788562e9
Successfully built crcmod
Installing collected packages: crcmod
Successfully installed crcmod-1.7
```

**Comment by jfcherng** [comment] 2024-10-11 03:28
I believe this is the same issue with https://github.com/astral-sh/uv/issues/7549, which was not fixed but closed.

**Comment by kahojyun** [comment] 2024-10-11 12:57
I think the non-UTF8 bytes come from the MSVC compiler output. It seems that the output of the compiler bypasses the `PYTHONIOENCODING` setting and writes directly to `stdout`/`stderr` using system default encoding.

**Comment by BurntSushi** [comment] 2024-10-11 13:10
@sdbds With #8120 merged, when the next release comes out, could you let us know whether this issue is resolved or not? Thanks!

**Comment by Super1Windcloud** [comment] 2024-10-11 15:15
> I think the non-UTF8 bytes come from the MSVC compiler output. It seems that the output of the compiler bypasses the `PYTHONIOENCODING` setting and writes directly to `stdout`/`stderr` using system default encoding.我认为非 UTF8 字节来自 MSVC 编译器输出。编译器的输出似乎绕过了`PYTHONIOENCODING`设置并使用系统默认编码直接写入`stdout` / `stderr` 。
#  very    nice , how  do you  find   this reason ?

**Comment by sdbds** [comment] 2024-10-12 11:12
> @sdbds With #8120 merged, when the next release comes out, could you let us know whether this issue is resolved or not? Thanks!

I need to check lastest release version for this because my environment dont have rust...
wait for fixing version for python wheel.

**Comment by konstin** [comment] 2024-10-12 18:36
I'm going to close this since #8120 is merged. Please report if the next release still doesn't work, we'll reopen and try to find and another solution in that case.

**Closed by konstin** 2024-10-12 18:36 UTC
Labels: bug
