### ISSUE TITLE
`uv build` command?

### ISSUE THREAD

**Issue by nekitdev** [astral-sh/uv#5507] opened 2024-07-27 10:58 UTC
I've searched through issues in this repository but I couldn't find anything concrete.
What's the progress/roadmap for this command? The only time I've seen it mentioned is in the [blog](https://astral.sh/blog/uv).

**Comment by chrisrodrigue** [comment] 2024-08-05 15:32
Semi-related: #3957

**Comment by lambda-science** [comment] 2024-08-21 06:05
> I've searched through issues in this repository but I couldn't find anything concrete. What's the progress/roadmap for this command? The only time I've seen it mentioned is in the [blog](https://astral.sh/blog/uv).

Interested as well to switch from Rye to uv, we need build publish command. Any news ?

**Comment by samypr100** [comment] 2024-08-25 21:26
Re-publish, see https://github.com/astral-sh/uv/issues/6278

**Comment by zanieb** [comment] 2024-08-26 17:05
I think this is a duplicate of #1510 — and yes we intend to do it.

**Closed by zanieb** 2024-08-26 17:05 UTC

**Comment by purajit** [comment] 2024-09-06 00:37
It's here now! I switched all our workflows to `uv build` from 0.4.5. Works like a charm.

**Comment by charliermarsh** [comment] 2024-09-06 00:41
Amazing!
