### ISSUE TITLE
Configure constraints file in config files

### ISSUE THREAD

**Issue by robertschweizer** [astral-sh/uv#7336] opened 2024-09-12 16:43 UTC
Thanks a lot for this great project!

It would be cool if `uv.toml` and `pyproject.toml` allowed specifying 

```toml
constraint = "https://host.local/my-global-constraints.txt
```

`uv` currently only allows passing this as environment variable or with the `--constraint` CLI argument.

In our team, we have a shared global constraints file that's used by all our projects. This way we can quickly exclude broken upstream package versions across all our projects. 

With pip, we set the `PIP_CONSTRAINT` variable in all CI pipelines, and for local development, every engineer has `constraint = https://host.local/my-global-constraints.txt` in their global `pip.conf` file. With `uv`, this is not possible right now. If it were supported in config files, we might just configure it in every project's `pyproject.toml`.

The same thing would be useful for us in build constraints.

**Comment by zanieb** [comment] 2024-09-12 16:57
This is roughly a duplicate of https://github.com/astral-sh/uv/issues/6518

You probably want to read the discussion there regarding constraints from URLs.

**Comment by pabarcgar** [comment] 2024-09-13 09:22
Hi @zanieb , thank you for the quick reply. The issue @robertschweizer mentions is for projects we build using 'uv pip install'.  In #6518 you say that 'constraint-dependencies' setting is applied to every single uv command and therefore passing a URL to it is not desirable. 

Would it be possible to support 'constraint' and 'build-constraint' settings in the [tool.uv.pip] pyproject.toml section instead?

**Comment by charliermarsh** [comment] 2024-09-13 13:06
I'm pretty sure that `constraint-dependencies` in `[tool.uv]` is respected within the current workspace for `uv pip` commands. So if the `pyproject.toml` in the current directory has:

```toml
[tool.uv]
constraint-dependencies = ["anyio>3"]
```

Then `uv pip` commands in that directory will respect the `anyio>3` constraint.

**Comment by pabarcgar** [comment] 2024-09-13 17:42
Hi @charliermarsh , thank you for your reply, I think you are right, but what we need is to be able to pass an URL. In the related issue #6518 this is discussed, but URL support is dismissed because that config is used for every uv command and that URL would be accessed unnecessarily. That is reasonable, and that is why we ask to add 'constraint' settings in the [tool.uv.pip] (so the URL is only accessed for URL commands). Does it make sense?

**Comment by charliermarsh** [comment] 2024-11-20 00:39
Let's combine with #6518.

**Closed by charliermarsh** 2024-11-20 00:39 UTC
Labels: duplicate
