### ISSUE TITLE
Feature request: indicate if/when a requirement came from an extra

### ISSUE THREAD

**Issue by wimglenn** [astral-sh/uv#2498] opened 2024-03-17 19:26 UTC
For example:

```
echo 'structlog[docs,tests]' | ./uv pip compile -
```

I would like the output to indicate if/when a requirement comes from an extra, e.g.

```
furo==2024.1.29
    # via structlog[docs]
...
simplejson==3.19.2
    # via structlog[tests]
```

Additionally, the top-level req itself should probably mention the extras requested, in this case it would be `structlog[docs,tests]==24.1.0`

**Comment by zanieb** [comment] 2024-03-17 19:29
Hi this is a duplicate of https://github.com/astral-sh/uv/issues/1595

**Closed by zanieb** 2024-03-17 19:29 UTC
