### ISSUE TITLE
Feature Request: Read from `.env` file in a project

### ISSUE THREAD

**Issue by pythonweb2** [astral-sh/uv#7743] opened 2024-09-27 17:57 UTC
If a machine with multiple projects pulls dependencies from multiple indexes, right now you would have to either `export` the index URL for each project before running command, or pass in the index URL via CLI arguments.

It would be nice if uv first tried to read from the `.env` file inside of a project, and then from the system environment variables, so if I had a file like this

`.env`
```
UV_INDEX_URL=asdf.
```

Then running `uv add` or `uv sync` would read from that file in my project directory.

**Comment by charliermarsh** [comment] 2024-09-27 18:03
I think this is a duplicate of https://github.com/astral-sh/uv/issues/1384.

**Closed by charliermarsh** 2024-09-27 18:03 UTC

**Comment by pythonweb2** [comment] 2024-09-27 18:26
Oh sorry about that, I searched the issues for .env but did not see that one.
