### ISSUE TITLE
Use a single python process across all steps of building a source dist

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#846] opened 2024-01-09 14:21 UTC
Starting python is slow (10ms on my machine), and importing a build backend is even slower. Instead, we should start a python interpreter once and keep reusing it. We avoid the startup cost and cached import are free.

PEP 517 says you _should_ use a fresh subprocess each time, but i don't see why keeping the process running shouldn't work.

> Frontends should call each hook in a fresh subprocess, so that backends are free to change process global state (such as environment variables or the working directory). A Python library will be provided which frontends can use to easily call hooks this way.

Ad-hoc Benchmarks:

```
$ hyperfine 'python3.12 -c "import sys; print(sys.version)"'
Benchmark 1: python3.12 -c "import sys; print(sys.version)"
  Time (mean ± σ):       8.8 ms ±   3.9 ms    [User: 7.1 ms, System: 1.9 ms]
  Range (min … max):     3.8 ms …  21.8 ms    128 runs
$ hyperfine 'python -c "import setuptools; print(setuptools.__version__)"'
Benchmark 1: python -c "import setuptools; print(setuptools.__version__)"
  Time (mean ± σ):      48.9 ms ±   3.8 ms    [User: 44.3 ms, System: 4.7 ms]
  Range (min … max):    46.5 ms …  71.9 ms    40 runs
$ hyperfine 'python -c "import poetry.core.masonry.api"'
Benchmark 1: python -c "import poetry.core.masonry.api"
  Time (mean ± σ):      30.3 ms ±   2.6 ms    [User: 26.1 ms, System: 4.3 ms]
  Range (min … max):    29.0 ms …  49.2 ms    59 runs
```

**Comment by bschoenmaeckers** [comment] 2024-03-18 12:37
Is it possible to dynamically load the correct libpython.so using ldopen (or some platform variant) and run the python code in the current process?

**Comment by konstin** [comment] 2024-03-18 12:54
Not really unfortunately. We would attach the python interpreter state to the current process (breaking isolation between builds) and we'd still pay the python initialization cost.

**Comment by zanieb** [comment] 2024-03-18 14:25
For bookkeeping I implemented this in #895 and we did not see a significant improvement.

Should we close this?

**Closed** 2024-03-18 14:30 UTC
Labels: performance

**Comment by charliermarsh** [comment] 2024-03-18 14:36
It’s a minor optimization. It should still save ~30-50ms from source distribution building but I don’t feel strongly about doing it (and it shouldn’t be prioritized).

**Comment by zanieb** [comment] 2024-03-18 14:42
The problem is that it's costly (and technically dubious) to reset the Python modules on each call which is necessary because new packages are installed in-between calls and libraries (e.g. setuptools) have dynamic behavior depending on what is available at import-time.
