### ISSUE TITLE
uv sync --activate

### ISSUE THREAD

**Issue by dbrtly** [astral-sh/uv#8715] opened 2024-10-31 02:01 UTC
Sometimes it would be convenient to sync and activate a virtual environment in one command. This has probably been discussed before but I didn't find it. Apologies if so.

**Comment by samypr100** [comment] 2024-10-31 03:47
Can you provide an example of the commands you used that didn't behave as expected? Did you try `uv sync` and it didn't work on your virtual environment?

**Comment by dbrtly** [comment] 2024-10-31 03:51
```
uv sync

```

Is a thing of beauty. I love it. 


I'd like the option to do 

```
uv sync --activate

```

As an alternative to 

```
uv sync
source .venv/bin/activate || source .venv/Scripts/activate

```

**Comment by samypr100** [comment] 2024-10-31 04:04
Ah, I see. Thanks for the examples. I'd consider this a dupe of https://github.com/astral-sh/uv/issues/8106

**Comment by dbrtly** [comment] 2024-10-31 04:09
Ah. I see. 

Do you think a bash alias would work?

Like

```
alias uv-sync='uv sync && source .venv/bin/activate'

```

**Comment by zanieb** [comment] 2024-10-31 04:40
I guess so?

```
❯ alias test-example="echo 'hi' && source .venv/bin/activate"
❯ test-example
hi
❯ which python
/Users/zb/workspace/uv/.venv/bin/python
❯ deactivate
❯ test-example
hi
❯ which python
/Users/zb/workspace/uv/.venv/bin/python
```

Surprised me though tbh.

Anyway, we can't add support for this in uv directly.

**Closed by zanieb** 2024-10-31 04:40 UTC
Labels: question
