### ISSUE TITLE
Don't fail on incompatible file system setups

### ISSUE THREAD

**Issue by bra-fsn** [astral-sh/uv#1513] opened 2024-02-16 16:58 UTC
Consider the following scenario, where `/root/.cache` is a persistent volume in a container:

```shell
docker run --rm -ti -v cachevol:/root/.cache python:3.11 bash
pip install uv
mkdir /venvs
cd /venvs
uv venv test
export VIRTUAL_ENV=/venvs/test
uv pip install nvidia-cusolver-cu12
```

Running the above gives the following error:
```
error: Failed to install: nvidia_cublas_cu12-12.3.4.1-py3-none-manylinux1_x86_64.whl (nvidia-cublas-cu12==12.3.4.1)
  Caused by: failed to rename file from /venvs/test/lib/python3.11/site-packages/.tmpeSt2og/__init__.py to /venvs/test/lib/python3.11/site-packages/nvidia/__init__.py
  Caused by: No such file or directory (os error 2)
```

Using `uv pip install --link-mode copy nvidia-cusolver-cu12` works as most of the other packages, so I think on the code path, which produces the above error `uv` should fall back to the `copy` mode.

**Comment by zanieb** [comment] 2024-02-16 17:05
Thanks for the report!

I believe this is a duplicate of https://github.com/astral-sh/uv/issues/1444

**Comment by charliermarsh** [comment] 2024-02-16 17:49
It might be a bit different, since that's on macOS and this is on Linux.

**Comment by bra-fsn** [comment] 2024-02-16 18:29
> Thanks for the report!
> 
> I believe this is a duplicate of #1444

Haven't checked the code, but the other error says it's a cross device link (hardlink, which of course doesn't work between file systems), while this one is a failed rename on the same FS, so I don't think they are (exactly) the same. Might share a common root cause however.

**Comment by charliermarsh** [comment] 2024-02-16 22:03
This _may_ be fixed by https://github.com/astral-sh/uv/pull/1546.

**Comment by charliermarsh** [comment] 2024-02-17 01:20
v0.1.3 is out now. Do you mind retrying? (It may not solve it, but it could.)

**Comment by cebtenzzre** [comment] 2024-02-17 21:21
This is what I saw on uv 0.1.0:
```
$ pip install torch
Resolved 22 packages in 527ms
Downloaded 19 packages in 1m 15s
error: Failed to install: nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (nvidia-nvtx-cu12==12.1.105)
  Caused by: failed to rename file from /home/jared/.venv/lib/python3.11/site-packages/.tmpGJtW6w/__init__.py to /home/jared/.venv/lib/python3.11/site-packages/nvidia/__init__.py
  Caused by: No such file or directory (os error 2)
```

Updating to uv 0.1.3 fixed the problem.

**Comment by charliermarsh** [comment] 2024-02-17 21:22
Awesome. I'm going to close for now since we haven't seen this again. Will reopen if it comes up!

**Closed by charliermarsh** 2024-02-17 21:22 UTC
Labels: bug, linux
