### ISSUE TITLE
uv can't understand requirements.txt file that is valid for pip

### ISSUE THREAD

**Issue by karpetrosyan** [astral-sh/uv#2132] opened 2024-03-02 17:21 UTC
Hi! First and foremost, thank you for this fantastic tool!

I am trying to use uv in a library that uses such syntax in the requirements.txt file:

```
file:./libs/path_where_pyprojecttoml
```

When using pip, all works fine, but uv fails with the following exception:

```
error: Error parsing included file in `build/pip/dev_requirements.txt` at position 0
  Caused by: Unsupported requirement in build/pip/base_requirements.txt at position 467
  Caused by: URL requirement must be preceded by a package name. Add the name of the package before the URL (e.g., `package_name @ https://...`).
file:./libs/path_where_pyprojecttoml
```

Is this a feature defined by the PEP but not supported by the uv? I couldn't find any references to such a functionality; perhaps pip decided to include it without any specification.

Simple repro (you have already installed uv):

```shell
git clone https://github.com/astral-sh/ruff-lsp

uv pip install "file:./ruff-lsp"  # fails
pip install "file:./ruff-lsp" # ok
```

**Comment by AlexWaygood** [comment] 2024-03-02 17:49
Thanks! Closing as a duplicate of https://github.com/astral-sh/uv/issues/313 :)

**Closed by AlexWaygood** 2024-03-02 17:49 UTC

**Comment by charliermarsh** [comment] 2024-03-22 21:27
This is supported as of `v0.1.24`. You can `uv pip install file:./libs/path_where_pyprojecttoml` directly, without including a package name.
