### ISSUE TITLE
Download Progress Bar for Large Files

### ISSUE THREAD

**Issue by Aydinhamedi** [astral-sh/uv#2667] opened 2024-03-26 09:54 UTC
I would like to request a feature for the `uv` package: a download progress bar for large files during installation. This would enhance the user experience by providing visual feedback on the download status, especially when installing sizable packages like `torch` using the command `uv pip install torch`.

**Comment by charliermarsh** [comment] 2024-03-26 13:16
I'm open to something like this but we need it to work with highly concurrent downloads.

**Comment by zanieb** [comment] 2024-03-26 14:45
This is a duplicate of https://github.com/astral-sh/uv/issues/1209

**Closed by zanieb** 2024-03-26 14:45 UTC
Labels: wish, cli
