### ISSUE TITLE
Spurious test failures related to Windows permissions on temporary directory

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6940] opened 2024-09-02 18:21 UTC
```
running 1 test
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: uv_run_isolate
Source: E:\uv:533
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 2
    2     2 │ ----- stdout -----
    3       │-Success
    4     3 │ 
    5     4 │ ----- stderr -----
    6     5 │ Using Python 3.12.[X] interpreter at: [PYTHON-3.12]
    7     6 │ Creating virtualenv at: .venv
    8     7 │ Resolved 8 packages in [TIME]
    9       │-Prepared 7 packages in [TIME]
   10       │-Installed 7 packages in [TIME]
   11       │- + albatross==0.1.0 (from file://[TEMP_DIR]/albatross-root-workspace)
   12       │- + anyio==4.3.0
   13       │- + bird-feeder==1.0.0 (from file://[TEMP_DIR]/albatross-root-workspace/packages/bird-feeder)
   14       │- + idna==3.6
   15       │- + seeds==1.0.0 (from file://[TEMP_DIR]/albatross-root-workspace/packages/seeds)
   16       │- + sniffio==1.3.1
   17       │- + tqdm==4.66.2
          8 │+error: Failed to prepare distributions
          9 │+  Caused by: Failed to fetch wheel: seeds @ file://[TEMP_DIR]/albatross-root-workspace/packages/seeds
         10 │+  Caused by: Build backend failed to build wheel through `build_editable()` with exit code: 1
         11 │+--- stdout:
         12 │+
         13 │+--- stderr:
         14 │+Traceback (most recent call last):
         15 │+  File "<string>", line 11, in <module>
         16 │+  File "[CACHE_DIR]/builds-v0/[TMP]/build.py", line 83, in build_editable
         17 │+    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
         18 │+                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         19 │+  File "[CACHE_DIR]/builds-v0/[TMP]/interface.py", line 90, in build
         20 │+    self.metadata.validate_fields()
         21 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 259, in validate_fields
         22 │+    _ = self.version
         23 │+        ^^^^^^^^^^^^
         24 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 143, in version
         25 │+    self._version = self._get_version()
         26 │+                    ^^^^^^^^^^^^^^^^^^^
         27 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 248, in _get_version
         28 │+    from packaging.version import InvalidVersion, Version
         29 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         30 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         31 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         32 │+  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
         33 │+  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
         34 │+  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
         35 │+PermissionError: [Errno 13] Permission denied: 'E:\/uv-tmp\/[TMP]/version.py'
         36 │+---
────────────┴──────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test test_uv_run_isolate ... FAILED
```

**Comment by zanieb** [comment] 2024-09-03 14:47
Duplicate of https://github.com/astral-sh/uv/issues/6789 — better title though.

**Comment by zanieb** [comment] 2024-09-03 14:49
Maybe since https://github.com/astral-sh/uv/pull/6680 ?

I wonder if this is a real bug that's just surfaced now?

**Comment by samypr100** [comment] 2024-09-05 14:21
Shouldn't the temp dir need to be created before tests start to run?

**Comment by zanieb** [comment] 2024-09-05 14:42
Oh is this related to #6929 ?

Why would it work sometimes?

**Comment by samypr100** [comment] 2024-09-05 15:15
Thats the first difference from before and after I can think about. C: drive already had a temp drive ahead of time, where as the dev drive doesn't. Assuming it started happening after that change. Given env:tmp_dir does not ensure the dir exists, I assumed this being a potential cause.

**Comment by zanieb** [comment] 2024-10-18 19:19
Another example

```
         13 │+[stderr]
         14 │+Traceback (most recent call last):
         15 │+  File "<string>", line 11, in <module>
         16 │+  File "[CACHE_DIR]/builds-v0/[TMP]/build.py", line 83, in build_editable
         17 │+    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
         18 │+                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         19 │+  File "[CACHE_DIR]/builds-v0/[TMP]/interface.py", line 90, in build
         20 │+    self.metadata.validate_fields()
         21 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 260, in validate_fields
         22 │+    self.core.validate_fields()
         23 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1352, in validate_fields
         24 │+    getattr(self, attribute)
         25 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1223, in dependencies
         26 │+    self._dependencies = list(self.dependencies_complex)
         27 │+                              ^^^^^^^^^^^^^^^^^^^^^^^^^
         28 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1174, in dependencies_complex
         29 │+    from packaging.requirements import InvalidRequirement, Requirement
         30 │+  File "[CACHE_DIR]/builds-v0/[TMP]/requirements.py", line 9, in <module>
         31 │+    from .markers import Marker, _normalize_extra_values
         32 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         33 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         34 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         35 │+  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
         36 │+  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
         37 │+  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
         38 │+PermissionError: [Errno 13] Permission denied: 'E:\/uv-tmp\/[TMP]/markers.py'
```

**Comment by zanieb** [comment] 2024-10-18 22:35
```
Snapshot file: crates\uv\tests\it\snapshots\it__ecosystem__saleor-uv-lock-output.snap
Snapshot: saleor-uv-lock-output
Source: E:\uv:124
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 1
    2     2 │ ----- stdout -----
    3     3 │ 
    4     4 │ ----- stderr -----
    5       │-Resolved 170 packages in [TIME]
          5 │+  × Failed to download and build `html2text==2024.2.26`
          6 │+  ╰─▶ Build backend failed to determine metadata through `prepare_metadata_for_build_wheel` (exit code: 1)
          7 │+
          8 │+      [stdout]
          9 │+      running dist_info
         10 │+      creating [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/html2text.egg-info
         11 │+      writing [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/PKG-INFO
         12 │+      writing dependency_links to [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/dependency_links.txt
         13 │+      writing entry points to [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/entry_points.txt
         14 │+      writing top-level names to [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/top_level.txt
         15 │+      writing manifest file '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/SOURCES.txt'
         16 │+      reading manifest file '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/SOURCES.txt'
         17 │+      reading manifest template 'MANIFEST.in'
         18 │+      adding license file 'COPYING'
         19 │+      adding license file 'AUTHORS.rst'
         20 │+      writing manifest file '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/SOURCES.txt'
         21 │+      creating '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/html2text-2024.2.26.dist-info'
         22 │+
         23 │+      [stderr]
         24 │+      error: [Errno 13] Permission denied: 'E:\/uv\/target\/ecosystem-test-caches\/saleor\/builds-v0\/[TMP]/util.py'
```

**Comment by zanieb** [comment] 2024-10-18 22:36
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: uv_run_virtual_workspace_root
Source: E:\uv:430
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 2
    2     2 │ ----- stdout -----
    3       │-Success
    4     3 │ 
    5     4 │ ----- stderr -----
    6     5 │ warning: `VIRTUAL_ENV=[VENV]/` does not match the project environment path `.venv` and will be ignored
    7     6 │ Using CPython 3.12.[X] interpreter at: [PYTHON-3.12]
    8     7 │ Creating virtual environment at: .venv
    9     8 │ Resolved 8 packages in [TIME]
   10       │-Prepared 7 packages in [TIME]
   11       │-Installed 7 packages in [TIME]
   12       │- + albatross==0.1.0 (from file://[TEMP_DIR]/albatross-virtual-workspace/packages/albatross)
   13       │- + anyio==4.3.0
   14       │- + bird-feeder==1.0.0 (from file://[TEMP_DIR]/albatross-virtual-workspace/packages/bird-feeder)
   15       │- + idna==3.6
   16       │- + seeds==1.0.0 (from file://[TEMP_DIR]/albatross-virtual-workspace/packages/seeds)
   17       │- + sniffio==1.3.1
   18       │- + tqdm==4.66.2
          9 │+error: Failed to prepare distributions
         10 │+  Caused by: Failed to fetch wheel: bird-feeder @ file://[TEMP_DIR]/albatross-virtual-workspace/packages/bird-feeder
         11 │+  Caused by: Build backend failed to build editable through `build_editable` (exit code: 1)
         12 │+
         13 │+[stderr]
         14 │+Traceback (most recent call last):
         15 │+  File "<string>", line 11, in <module>
         16 │+  File "[CACHE_DIR]/builds-v0/[TMP]/build.py", line 83, in build_editable
         17 │+    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
         18 │+                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         19 │+  File "[CACHE_DIR]/builds-v0/[TMP]/interface.py", line 155, in build
         20 │+    artifact = version_api[version](directory, **build_data)
         21 │+               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         22 │+  File "[CACHE_DIR]/builds-v0/[TMP]/wheel.py", line 434, in build_editable
         23 │+    return self.build_editable_detection(directory, **build_data)
         24 │+           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         25 │+  File "[CACHE_DIR]/builds-v0/[TMP]/wheel.py", line 437, in build_editable_detection
         26 │+    from editables import EditableProject
         27 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         28 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         29 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         30 │+  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
         31 │+  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
         32 │+  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
         33 │+PermissionError: [Errno 13] Permission denied: 'E:\/uv-tmp\/[TMP]/__init__.py'
```

**Comment by zanieb** [comment] 2024-10-18 22:37
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: require_hashes_find_links_no_hash-4
Source: E:\uv:4621
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 2
    2     2 │ ----- stdout -----
    3     3 │ 
    4     4 │ ----- stderr -----
    5     5 │ Resolved 1 package in [TIME]
    6       │-Prepared 1 package in [TIME]
    7       │-Uninstalled 1 package in [TIME]
    8       │-Installed 1 package in [TIME]
    9       │- ~ example-a-961b4c22==1.0.0
          6 │+error: Failed to prepare distributions
          7 │+  Caused by: Failed to fetch wheel: example-a-961b4c22==1.0.0
          8 │+  Caused by: Failed to install requirements from `build-system.requires`
          9 │+  Caused by: Failed to prepare distributions
         10 │+  Caused by: Failed to fetch wheel: trove-classifiers==2024.3.3
         11 │+  Caused by: Build backend failed to build wheel through `build_wheel` (exit code: 1)
         12 │+
         13 │+[stderr]
         14 │+Traceback (most recent call last):
         15 │+  File "<string>", line 11, in <module>
         16 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/build_meta.py", line 410, in build_wheel
         17 │+    return self._build_with_temp_dir(
         18 │+           ^^^^^^^^^^^^^^^^^^^^^^^^^^
         19 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
         20 │+    self.run_setup()
         21 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/build_meta.py", line 311, in run_setup
         22 │+    exec(code, locals())
         23 │+  File "<string>", line 12, in <module>
         24 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/__init__.py", line 104, in setup
         25 │+    return distutils.core.setup(**attrs)
         26 │+           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         27 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/_distutils/core.py", line 172, in setup
         28 │+    ok = dist.parse_command_line()
         29 │+         ^^^^^^^^^^^^^^^^^^^^^^^^^
         30 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/_distutils/dist.py", line 475, in parse_command_line
         31 │+    args = self._parse_command_opts(parser, args)
         32 │+           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         33 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/dist.py", line 869, in _parse_command_opts
         34 │+    nargs = _Distribution._parse_command_opts(self, parser, args)
         35 │+            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         36 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/_distutils/dist.py", line 534, in _parse_command_opts
         37 │+    cmd_class = self.get_command_class(command)
         38 │+                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         39 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/setuptools/dist.py", line 714, in get_command_class
40 │+    self.cmdclass[command] = cmdclass = ep.load()
         41 │+                                        ^^^^^^^^^
         42 │+  File "C:/hostedtoolcache/windows/Python/3.12.7/x64/Lib/importlib/metadata/__init__.py", line 205, in load
         43 │+    module = import_module(match.group('module'))
         44 │+             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         45 │+  File "C:/hostedtoolcache/windows/Python/3.12.7/x64/Lib/importlib/__init__.py", line 90, in import_module
         46 │+    return _bootstrap._gcd_import(name[level:], package, level)
         47 │+           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         48 │+  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
         49 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         50 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         51 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         52 │+  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
         53 │+  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
         54 │+  File "E:/uv-tmp\.tmpV76s9s/cache/builds-v0\.tmpZcJQUN/Lib/site-packages/wheel/bdist_wheel.py", line 27, in <module>
         55 │+    from .macosx_libfile import calculate_macosx_platform_tag
         56 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         57 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         58 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         59 │+  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
         60 │+  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
         61 │+  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
         62 │+PermissionError: [Errno 13] Permission denied: 'E:\/uv-tmp\\.tmpV76s9s\/cache\/builds-v0\\.tmpZcJQUN\/Lib\/site-packages\/wheel\/macosx_libfile.py'
────────────┴──────────────────────────────────────────────────────────────────
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
test pip_sync::require_hashes_find_links_no_hash ... FAILED
```

**Comment by zanieb** [comment] 2024-10-18 22:39
Some observations

1. The failures are common, but not limited to the workspace tests.
2. The failures occur with both setuptools and hatchling build backends.
3. The failures are always in `importlib._bootstrap_external.get_data` reading a file to resolve an import.

**Comment by zanieb** [comment] 2024-10-18 22:44
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot: uv_run_virtual_workspace_root
Source: E:\uv:430
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 2
    2     2 │ ----- stdout -----
    3       │-Success
    4     3 │ 
    5     4 │ ----- stderr -----
    6     5 │ warning: `VIRTUAL_ENV=[VENV]/` does not match the project environment path `.venv` and will be ignored
    7     6 │ Using CPython 3.12.[X] interpreter at: [PYTHON-3.12]
    8     7 │ Creating virtual environment at: .venv
    9     8 │ Resolved 8 packages in [TIME]
   10       │-Prepared 7 packages in [TIME]
   11       │-Installed 7 packages in [TIME]
   12       │- + albatross==0.1.0 (from file://[TEMP_DIR]/albatross-virtual-workspace/packages/albatross)
   13       │- + anyio==4.3.0
   14       │- + bird-feeder==1.0.0 (from file://[TEMP_DIR]/albatross-virtual-workspace/packages/bird-feeder)
   15       │- + idna==3.6
   16       │- + seeds==1.0.0 (from file://[TEMP_DIR]/albatross-virtual-workspace/packages/seeds)
   17       │- + sniffio==1.3.1
   18       │- + tqdm==4.66.2
          9 │+error: Failed to prepare distributions
         10 │+  Caused by: Failed to fetch wheel: albatross @ file://[TEMP_DIR]/albatross-virtual-workspace/packages/albatross
         11 │+  Caused by: Build backend failed to build editable through `build_editable` (exit code: 1)
         12 │+
         13 │+[stderr]
         14 │+Traceback (most recent call last):
         15 │+  File "<string>", line 11, in <module>
         16 │+  File "[CACHE_DIR]/builds-v0/[TMP]/build.py", line 83, in build_editable
         17 │+    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
         18 │+                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         19 │+  File "[CACHE_DIR]/builds-v0/[TMP]/interface.py", line 90, in build
         20 │+    self.metadata.validate_fields()
         21 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 260, in validate_fields
         22 │+    self.core.validate_fields()
         23 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1352, in validate_fields
         24 │+    getattr(self, attribute)
         25 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1223, in dependencies
         26 │+    self._dependencies = list(self.dependencies_complex)
         27 │+                              ^^^^^^^^^^^^^^^^^^^^^^^^^
         28 │+  File "[CACHE_DIR]/builds-v0/[TMP]/core.py", line 1174, in dependencies_complex
         29 │+    from packaging.requirements import InvalidRequirement, Requirement
         30 │+  File "[CACHE_DIR]/builds-v0/[TMP]/requirements.py", line 7, in <module>
         31 │+    from ._parser import parse_requirement as _parse_requirement
         32 │+  File "[CACHE_DIR]/builds-v0/[TMP]/_parser.py", line 10, in <module>
         33 │+    from ._tokenizer import DEFAULT_RULES, Tokenizer
         34 │+  File "[CACHE_DIR]/builds-v0/[TMP]/_tokenizer.py", line 6, in <module>
         35 │+    from .specifiers import Specifier
         36 │+  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
         37 │+  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
         38 │+  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
         39 │+  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
         40 │+  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
         41 │+  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
         42 │+PermissionError: [Errno 13] Permission denied: 'E:\/uv-tmp\/[TMP]/specifiers.py'
```

**Comment by zanieb** [comment] 2024-10-18 22:46
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates\uv\tests\snapshots\ecosystem__saleor-uv-lock-output.snap
Snapshot: saleor-uv-lock-output
Source: E:\uv:128
───────────────────────────────────────────────────────────────────────────────
Expression: snapshot
───────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬──────────────────────────────────────────────────────────────────
    0       │-success: true
    1       │-exit_code: 0
          0 │+success: false
          1 │+exit_code: 2
    2     2 │ ----- stdout -----
    3     3 │ 
    4     4 │ ----- stderr -----
    5       │-Resolved 170 packages in [TIME]
          5 │+error: Failed to download and build `rx==1.6.3`
          6 │+  Caused by: Build backend failed to determine metadata through `prepare_metadata_for_build_wheel` with exit code: 1
          7 │+--- stdout:
          8 │+running dist_info
          9 │+creating [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/Rx.egg-info
         10 │+writing [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/PKG-INFO
         11 │+writing dependency_links to [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/dependency_links.txt
         12 │+writing top-level names to [WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/top_level.txt
         13 │+writing manifest file '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/SOURCES.txt'
         14 │+reading manifest file '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/SOURCES.txt'
         15 │+adding license file 'LICENSE'
         16 │+writing manifest file '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/SOURCES.txt'
         17 │+creating '[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/Rx-1.6.3.dist-info'
         18 │+--- stderr:
         19 │+[WORKSPACE]/target/ecosystem-test-caches/saleor/builds-v0/[TMP]/dist.py:268: UserWarning: Unknown distribution option: 'test_suite'
         20 │+  warnings.warn(msg)
         21 │+error: [Errno 13] Permission denied: 'E:\/uv\/target\/ecosystem-test-caches\/saleor\/builds-v0\/[TMP]/wheelfile.py'
         22 │+---
────────────┴─────────────────────────────────────────────────────────────────
```

**Closed** 2024-10-20 18:37 UTC
Labels: testing
